// SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0
// SPDX-FileCopyrightText: Copyright (c) 2024-present ESEngine Team
/**
 * @file    MaterialConstants.hpp
 * @brief   Binding points for per-material shader constants — the second tier of the
 *          engine's constant-buffer layering (after per-frame FrameConstants at binding 0).
 * @details A material shader authored with `#pragma param` gets a `layout(std140) uniform
 *          MaterialConstants { ... }` block auto-generated by ShaderParser; Shader::compile
 *          links it to MATERIAL_CONSTANTS_BINDING, and the render path binds the material's
 *          UBO there per draw. Material texture parameters get sampler units starting at
 *          MATERIAL_TEXTURE_UNIT_BASE, above the batch path's 0..7 multi-texture slots.
 */
#pragma once

#include "../core/Types.hpp"

namespace esengine {

/** @brief Indexed UBO binding point for the per-material MaterialConstants block. */
inline constexpr u32 MATERIAL_CONSTANTS_BINDING = 1;

/** @brief GLSL block name; must match ShaderParser's generated block + Shader::compile lookup. */
inline constexpr const char* MATERIAL_CONSTANTS_BLOCK = "MaterialConstants";

/** @brief First sampler unit a material texture parameter may use (batch owns units 0..7). */
inline constexpr u32 MATERIAL_TEXTURE_UNIT_BASE = 8;

}  // namespace esengine
