// AUTO-GENERATED by tests/ui-widget-prefabs.gen.test.ts — do not edit by hand.
import type { PrefabData } from '../../../prefab/types';

export const BUILTIN_UI_PREFABS: Record<string, PrefabData> = {
  "Button": {
    "version": "2",
    "name": "Button",
    "rootEntityId": "0",
    "entities": [
      {
        "prefabEntityId": "0",
        "name": "Button",
        "parent": null,
        "children": [
          "1"
        ],
        "components": [
          {
            "type": "Transform",
            "data": {
              "position": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "rotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "scale": {
                "x": 1,
                "y": 1,
                "z": 1
              },
              "worldPosition": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldRotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldScale": {
                "x": 1,
                "y": 1,
                "z": 1
              }
            }
          },
          {
            "type": "UINode",
            "data": {
              "position": 0,
              "display": 0,
              "width": {
                "value": 140,
                "unit": 0
              },
              "height": {
                "value": 40,
                "unit": 0
              },
              "minWidth": {
                "value": 0,
                "unit": 2
              },
              "minHeight": {
                "value": 0,
                "unit": 2
              },
              "maxWidth": {
                "value": 0,
                "unit": 2
              },
              "maxHeight": {
                "value": 0,
                "unit": 2
              },
              "flexGrow": 0,
              "flexShrink": 1,
              "flexBasis": {
                "value": 0,
                "unit": 2
              },
              "alignSelf": 0,
              "marginLeft": {
                "value": 0,
                "unit": 0
              },
              "marginTop": {
                "value": 0,
                "unit": 0
              },
              "marginRight": {
                "value": 0,
                "unit": 0
              },
              "marginBottom": {
                "value": 0,
                "unit": 0
              },
              "insetLeft": {
                "value": 0,
                "unit": 2
              },
              "insetTop": {
                "value": 0,
                "unit": 2
              },
              "insetRight": {
                "value": 0,
                "unit": 2
              },
              "insetBottom": {
                "value": 0,
                "unit": 2
              }
            }
          },
          {
            "type": "UIVisual",
            "data": {
              "visualType": 1,
              "texture": 0,
              "color": {
                "r": 1,
                "g": 1,
                "b": 1,
                "a": 1
              },
              "uvOffset": {
                "x": 0,
                "y": 0
              },
              "uvScale": {
                "x": 1,
                "y": 1
              },
              "sliceBorder": {
                "x": 0,
                "y": 0,
                "z": 0,
                "w": 0
              },
              "tileSize": {
                "x": 32,
                "y": 32
              },
              "fillMethod": 0,
              "fillOrigin": 0,
              "fillAmount": 1,
              "material": 0,
              "enabled": true
            }
          },
          {
            "type": "Interactable",
            "data": {
              "enabled": true,
              "blockRaycast": true,
              "raycastTarget": true
            }
          },
          {
            "type": "Focusable",
            "data": {
              "tabIndex": 0,
              "isFocused": false
            }
          },
          {
            "type": "UIController",
            "data": {
              "controllers": [
                {
                  "name": "$interaction",
                  "pages": [
                    "normal",
                    "hover",
                    "pressed",
                    "disabled",
                    "focused"
                  ],
                  "current": "normal"
                }
              ]
            }
          },
          {
            "type": "UIGear",
            "data": {
              "bindings": [
                {
                  "controller": "$interaction",
                  "component": "UIVisual",
                  "property": "color",
                  "pages": {
                    "normal": {
                      "r": 0.22,
                      "g": 0.22,
                      "b": 0.26,
                      "a": 1
                    },
                    "hover": {
                      "r": 0.28,
                      "g": 0.28,
                      "b": 0.32,
                      "a": 1
                    },
                    "pressed": {
                      "r": 0.18,
                      "g": 0.18,
                      "b": 0.22,
                      "a": 1
                    },
                    "disabled": {
                      "r": 0.22,
                      "g": 0.22,
                      "b": 0.26,
                      "a": 0.5
                    },
                    "focused": {
                      "r": 0.28,
                      "g": 0.28,
                      "b": 0.32,
                      "a": 1
                    }
                  }
                }
              ]
            }
          },
          {
            "type": "ThemeStyle",
            "data": {
              "states": {
                "normal": "control",
                "hover": "controlHover",
                "pressed": "controlActive",
                "disabled": "control",
                "focused": "controlHover"
              }
            }
          }
        ],
        "visible": true
      },
      {
        "prefabEntityId": "1",
        "name": "Label",
        "parent": "0",
        "children": [],
        "components": [
          {
            "type": "Transform",
            "data": {
              "position": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "rotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "scale": {
                "x": 1,
                "y": 1,
                "z": 1
              },
              "worldPosition": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldRotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldScale": {
                "x": 1,
                "y": 1,
                "z": 1
              }
            }
          },
          {
            "type": "UINode",
            "data": {
              "position": 1,
              "display": 0,
              "width": {
                "value": 0,
                "unit": 2
              },
              "height": {
                "value": 0,
                "unit": 2
              },
              "minWidth": {
                "value": 0,
                "unit": 2
              },
              "minHeight": {
                "value": 0,
                "unit": 2
              },
              "maxWidth": {
                "value": 0,
                "unit": 2
              },
              "maxHeight": {
                "value": 0,
                "unit": 2
              },
              "flexGrow": 0,
              "flexShrink": 1,
              "flexBasis": {
                "value": 0,
                "unit": 2
              },
              "alignSelf": 0,
              "marginLeft": {
                "value": 0,
                "unit": 0
              },
              "marginTop": {
                "value": 0,
                "unit": 0
              },
              "marginRight": {
                "value": 0,
                "unit": 0
              },
              "marginBottom": {
                "value": 0,
                "unit": 0
              },
              "insetLeft": {
                "value": 0,
                "unit": 0
              },
              "insetTop": {
                "value": 0,
                "unit": 0
              },
              "insetRight": {
                "value": 0,
                "unit": 0
              },
              "insetBottom": {
                "value": 0,
                "unit": 0
              }
            }
          },
          {
            "type": "Text",
            "data": {
              "content": "Button",
              "i18nKey": "",
              "fontFamily": "Arial",
              "fontSize": 14,
              "color": {
                "r": 0.92,
                "g": 0.92,
                "b": 0.94,
                "a": 1
              },
              "align": 1,
              "verticalAlign": 1,
              "wordWrap": false,
              "overflow": 0,
              "lineHeight": 1.2,
              "bold": false,
              "italic": false,
              "strokeColor": {
                "r": 0,
                "g": 0,
                "b": 0,
                "a": 1
              },
              "strokeWidth": 0,
              "shadowColor": {
                "r": 0,
                "g": 0,
                "b": 0,
                "a": 1
              },
              "shadowBlur": 0,
              "shadowOffsetX": 0,
              "shadowOffsetY": 0,
              "richText": false,
              "renderMode": 0,
              "enabled": true
            }
          },
          {
            "type": "ThemeStyle",
            "data": {
              "text": "text"
            }
          }
        ],
        "visible": true
      }
    ]
  },
  "Toggle": {
    "version": "2",
    "name": "Toggle",
    "rootEntityId": "0",
    "entities": [
      {
        "prefabEntityId": "0",
        "name": "Toggle",
        "parent": null,
        "children": [
          "1"
        ],
        "components": [
          {
            "type": "Transform",
            "data": {
              "position": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "rotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "scale": {
                "x": 1,
                "y": 1,
                "z": 1
              },
              "worldPosition": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldRotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldScale": {
                "x": 1,
                "y": 1,
                "z": 1
              }
            }
          },
          {
            "type": "UINode",
            "data": {
              "position": 0,
              "display": 0,
              "width": {
                "value": 28,
                "unit": 0
              },
              "height": {
                "value": 28,
                "unit": 0
              },
              "minWidth": {
                "value": 0,
                "unit": 2
              },
              "minHeight": {
                "value": 0,
                "unit": 2
              },
              "maxWidth": {
                "value": 0,
                "unit": 2
              },
              "maxHeight": {
                "value": 0,
                "unit": 2
              },
              "flexGrow": 0,
              "flexShrink": 1,
              "flexBasis": {
                "value": 0,
                "unit": 2
              },
              "alignSelf": 0,
              "marginLeft": {
                "value": 0,
                "unit": 0
              },
              "marginTop": {
                "value": 0,
                "unit": 0
              },
              "marginRight": {
                "value": 0,
                "unit": 0
              },
              "marginBottom": {
                "value": 0,
                "unit": 0
              },
              "insetLeft": {
                "value": 0,
                "unit": 2
              },
              "insetTop": {
                "value": 0,
                "unit": 2
              },
              "insetRight": {
                "value": 0,
                "unit": 2
              },
              "insetBottom": {
                "value": 0,
                "unit": 2
              }
            }
          },
          {
            "type": "UIVisual",
            "data": {
              "visualType": 1,
              "texture": 0,
              "color": {
                "r": 1,
                "g": 1,
                "b": 1,
                "a": 1
              },
              "uvOffset": {
                "x": 0,
                "y": 0
              },
              "uvScale": {
                "x": 1,
                "y": 1
              },
              "sliceBorder": {
                "x": 0,
                "y": 0,
                "z": 0,
                "w": 0
              },
              "tileSize": {
                "x": 32,
                "y": 32
              },
              "fillMethod": 0,
              "fillOrigin": 0,
              "fillAmount": 1,
              "material": 0,
              "enabled": true
            }
          },
          {
            "type": "Interactable",
            "data": {
              "enabled": true,
              "blockRaycast": true,
              "raycastTarget": true
            }
          },
          {
            "type": "Focusable",
            "data": {
              "tabIndex": 0,
              "isFocused": false
            }
          },
          {
            "type": "UIController",
            "data": {
              "controllers": [
                {
                  "name": "$interaction",
                  "pages": [
                    "normal",
                    "hover",
                    "pressed",
                    "disabled",
                    "focused"
                  ],
                  "current": "normal"
                }
              ]
            }
          },
          {
            "type": "UIGear",
            "data": {
              "bindings": [
                {
                  "controller": "$interaction",
                  "component": "UIVisual",
                  "property": "color",
                  "pages": {
                    "normal": {
                      "r": 0.22,
                      "g": 0.22,
                      "b": 0.26,
                      "a": 1
                    },
                    "hover": {
                      "r": 0.28,
                      "g": 0.28,
                      "b": 0.32,
                      "a": 1
                    },
                    "pressed": {
                      "r": 0.18,
                      "g": 0.18,
                      "b": 0.22,
                      "a": 1
                    },
                    "disabled": {
                      "r": 0.22,
                      "g": 0.22,
                      "b": 0.26,
                      "a": 0.5
                    },
                    "focused": {
                      "r": 0.28,
                      "g": 0.28,
                      "b": 0.32,
                      "a": 1
                    }
                  }
                }
              ]
            }
          },
          {
            "type": "ThemeStyle",
            "data": {
              "states": {
                "normal": "control",
                "hover": "controlHover",
                "pressed": "controlActive",
                "disabled": "control",
                "focused": "controlHover"
              }
            }
          },
          {
            "type": "UIToggle",
            "data": {
              "isOn": true,
              "check": "1"
            }
          }
        ],
        "visible": true
      },
      {
        "prefabEntityId": "1",
        "name": "Node",
        "parent": "0",
        "children": [],
        "components": [
          {
            "type": "Transform",
            "data": {
              "position": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "rotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "scale": {
                "x": 1,
                "y": 1,
                "z": 1
              },
              "worldPosition": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldRotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldScale": {
                "x": 1,
                "y": 1,
                "z": 1
              }
            }
          },
          {
            "type": "UINode",
            "data": {
              "position": 1,
              "display": 0,
              "width": {
                "value": 0,
                "unit": 2
              },
              "height": {
                "value": 0,
                "unit": 2
              },
              "minWidth": {
                "value": 0,
                "unit": 2
              },
              "minHeight": {
                "value": 0,
                "unit": 2
              },
              "maxWidth": {
                "value": 0,
                "unit": 2
              },
              "maxHeight": {
                "value": 0,
                "unit": 2
              },
              "flexGrow": 0,
              "flexShrink": 1,
              "flexBasis": {
                "value": 0,
                "unit": 2
              },
              "alignSelf": 0,
              "marginLeft": {
                "value": 0,
                "unit": 0
              },
              "marginTop": {
                "value": 0,
                "unit": 0
              },
              "marginRight": {
                "value": 0,
                "unit": 0
              },
              "marginBottom": {
                "value": 0,
                "unit": 0
              },
              "insetLeft": {
                "value": 0,
                "unit": 0
              },
              "insetTop": {
                "value": 0,
                "unit": 0
              },
              "insetRight": {
                "value": 0,
                "unit": 0
              },
              "insetBottom": {
                "value": 0,
                "unit": 0
              }
            }
          },
          {
            "type": "UIVisual",
            "data": {
              "visualType": 1,
              "texture": 0,
              "color": {
                "r": 0.25,
                "g": 0.56,
                "b": 0.96,
                "a": 1
              },
              "uvOffset": {
                "x": 0,
                "y": 0
              },
              "uvScale": {
                "x": 1,
                "y": 1
              },
              "sliceBorder": {
                "x": 0,
                "y": 0,
                "z": 0,
                "w": 0
              },
              "tileSize": {
                "x": 32,
                "y": 32
              },
              "fillMethod": 0,
              "fillOrigin": 0,
              "fillAmount": 1,
              "material": 0,
              "enabled": true
            }
          },
          {
            "type": "ThemeStyle",
            "data": {
              "visual": "primary"
            }
          }
        ],
        "visible": true
      }
    ]
  },
  "Slider": {
    "version": "2",
    "name": "Slider",
    "rootEntityId": "0",
    "entities": [
      {
        "prefabEntityId": "0",
        "name": "Slider",
        "parent": null,
        "children": [
          "2",
          "1"
        ],
        "components": [
          {
            "type": "Transform",
            "data": {
              "position": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "rotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "scale": {
                "x": 1,
                "y": 1,
                "z": 1
              },
              "worldPosition": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldRotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldScale": {
                "x": 1,
                "y": 1,
                "z": 1
              }
            }
          },
          {
            "type": "UINode",
            "data": {
              "position": 0,
              "display": 0,
              "width": {
                "value": 200,
                "unit": 0
              },
              "height": {
                "value": 18,
                "unit": 0
              },
              "minWidth": {
                "value": 0,
                "unit": 2
              },
              "minHeight": {
                "value": 0,
                "unit": 2
              },
              "maxWidth": {
                "value": 0,
                "unit": 2
              },
              "maxHeight": {
                "value": 0,
                "unit": 2
              },
              "flexGrow": 0,
              "flexShrink": 1,
              "flexBasis": {
                "value": 0,
                "unit": 2
              },
              "alignSelf": 0,
              "marginLeft": {
                "value": 0,
                "unit": 0
              },
              "marginTop": {
                "value": 0,
                "unit": 0
              },
              "marginRight": {
                "value": 0,
                "unit": 0
              },
              "marginBottom": {
                "value": 0,
                "unit": 0
              },
              "insetLeft": {
                "value": 0,
                "unit": 2
              },
              "insetTop": {
                "value": 0,
                "unit": 2
              },
              "insetRight": {
                "value": 0,
                "unit": 2
              },
              "insetBottom": {
                "value": 0,
                "unit": 2
              }
            }
          },
          {
            "type": "UIVisual",
            "data": {
              "visualType": 1,
              "texture": 0,
              "color": {
                "r": 0.15,
                "g": 0.15,
                "b": 0.15,
                "a": 1
              },
              "uvOffset": {
                "x": 0,
                "y": 0
              },
              "uvScale": {
                "x": 1,
                "y": 1
              },
              "sliceBorder": {
                "x": 0,
                "y": 0,
                "z": 0,
                "w": 0
              },
              "tileSize": {
                "x": 32,
                "y": 32
              },
              "fillMethod": 0,
              "fillOrigin": 0,
              "fillAmount": 1,
              "material": 0,
              "enabled": true
            }
          },
          {
            "type": "ThemeStyle",
            "data": {
              "visual": "track"
            }
          },
          {
            "type": "Interactable",
            "data": {
              "enabled": true,
              "blockRaycast": true,
              "raycastTarget": true
            }
          },
          {
            "type": "Focusable",
            "data": {
              "tabIndex": 0,
              "isFocused": false
            }
          },
          {
            "type": "UISlider",
            "data": {
              "min": 0,
              "max": 100,
              "step": 1,
              "value": 50,
              "fill": "2",
              "handle": "1"
            }
          }
        ],
        "visible": true
      },
      {
        "prefabEntityId": "1",
        "name": "Node",
        "parent": "0",
        "children": [],
        "components": [
          {
            "type": "Transform",
            "data": {
              "position": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "rotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "scale": {
                "x": 1,
                "y": 1,
                "z": 1
              },
              "worldPosition": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldRotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldScale": {
                "x": 1,
                "y": 1,
                "z": 1
              }
            }
          },
          {
            "type": "UINode",
            "data": {
              "position": 1,
              "display": 0,
              "width": {
                "value": 14,
                "unit": 0
              },
              "height": {
                "value": 0,
                "unit": 2
              },
              "minWidth": {
                "value": 0,
                "unit": 2
              },
              "minHeight": {
                "value": 0,
                "unit": 2
              },
              "maxWidth": {
                "value": 0,
                "unit": 2
              },
              "maxHeight": {
                "value": 0,
                "unit": 2
              },
              "flexGrow": 0,
              "flexShrink": 1,
              "flexBasis": {
                "value": 0,
                "unit": 2
              },
              "alignSelf": 0,
              "marginLeft": {
                "value": -7,
                "unit": 0
              },
              "marginTop": {
                "value": 0,
                "unit": 0
              },
              "marginRight": {
                "value": 0,
                "unit": 0
              },
              "marginBottom": {
                "value": 0,
                "unit": 0
              },
              "insetLeft": {
                "value": 50,
                "unit": 1
              },
              "insetTop": {
                "value": 0,
                "unit": 0
              },
              "insetRight": {
                "value": 0,
                "unit": 2
              },
              "insetBottom": {
                "value": 0,
                "unit": 0
              }
            }
          },
          {
            "type": "UIVisual",
            "data": {
              "visualType": 1,
              "texture": 0,
              "color": {
                "r": 1,
                "g": 1,
                "b": 1,
                "a": 1
              },
              "uvOffset": {
                "x": 0,
                "y": 0
              },
              "uvScale": {
                "x": 1,
                "y": 1
              },
              "sliceBorder": {
                "x": 0,
                "y": 0,
                "z": 0,
                "w": 0
              },
              "tileSize": {
                "x": 32,
                "y": 32
              },
              "fillMethod": 0,
              "fillOrigin": 0,
              "fillAmount": 1,
              "material": 0,
              "enabled": true
            }
          },
          {
            "type": "ThemeStyle",
            "data": {
              "visual": "onPrimary"
            }
          }
        ],
        "visible": true
      },
      {
        "prefabEntityId": "2",
        "name": "Node",
        "parent": "0",
        "children": [],
        "components": [
          {
            "type": "Transform",
            "data": {
              "position": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "rotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "scale": {
                "x": 1,
                "y": 1,
                "z": 1
              },
              "worldPosition": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldRotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldScale": {
                "x": 1,
                "y": 1,
                "z": 1
              }
            }
          },
          {
            "type": "UINode",
            "data": {
              "position": 1,
              "display": 0,
              "width": {
                "value": 0,
                "unit": 2
              },
              "height": {
                "value": 0,
                "unit": 2
              },
              "minWidth": {
                "value": 0,
                "unit": 2
              },
              "minHeight": {
                "value": 0,
                "unit": 2
              },
              "maxWidth": {
                "value": 0,
                "unit": 2
              },
              "maxHeight": {
                "value": 0,
                "unit": 2
              },
              "flexGrow": 0,
              "flexShrink": 1,
              "flexBasis": {
                "value": 0,
                "unit": 2
              },
              "alignSelf": 0,
              "marginLeft": {
                "value": 0,
                "unit": 0
              },
              "marginTop": {
                "value": 0,
                "unit": 0
              },
              "marginRight": {
                "value": 0,
                "unit": 0
              },
              "marginBottom": {
                "value": 0,
                "unit": 0
              },
              "insetLeft": {
                "value": 0,
                "unit": 0
              },
              "insetTop": {
                "value": 0,
                "unit": 0
              },
              "insetRight": {
                "value": 0,
                "unit": 0
              },
              "insetBottom": {
                "value": 0,
                "unit": 0
              }
            }
          },
          {
            "type": "UIVisual",
            "data": {
              "visualType": 5,
              "texture": 0,
              "color": {
                "r": 0.25,
                "g": 0.56,
                "b": 0.96,
                "a": 1
              },
              "uvOffset": {
                "x": 0,
                "y": 0
              },
              "uvScale": {
                "x": 1,
                "y": 1
              },
              "sliceBorder": {
                "x": 0,
                "y": 0,
                "z": 0,
                "w": 0
              },
              "tileSize": {
                "x": 32,
                "y": 32
              },
              "fillMethod": 0,
              "fillOrigin": 0,
              "fillAmount": 0.5,
              "material": 0,
              "enabled": true
            }
          },
          {
            "type": "ThemeStyle",
            "data": {
              "visual": "primary"
            }
          }
        ],
        "visible": true
      }
    ]
  },
  "Dialog": {
    "version": "2",
    "name": "Dialog",
    "rootEntityId": "0",
    "entities": [
      {
        "prefabEntityId": "0",
        "name": "Dialog",
        "parent": null,
        "children": [
          "1"
        ],
        "components": [
          {
            "type": "Transform",
            "data": {
              "position": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "rotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "scale": {
                "x": 1,
                "y": 1,
                "z": 1
              },
              "worldPosition": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldRotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldScale": {
                "x": 1,
                "y": 1,
                "z": 1
              }
            }
          },
          {
            "type": "UINode",
            "data": {
              "position": 1,
              "display": 0,
              "width": {
                "value": 0,
                "unit": 2
              },
              "height": {
                "value": 0,
                "unit": 2
              },
              "minWidth": {
                "value": 0,
                "unit": 2
              },
              "minHeight": {
                "value": 0,
                "unit": 2
              },
              "maxWidth": {
                "value": 0,
                "unit": 2
              },
              "maxHeight": {
                "value": 0,
                "unit": 2
              },
              "flexGrow": 0,
              "flexShrink": 1,
              "flexBasis": {
                "value": 0,
                "unit": 2
              },
              "alignSelf": 0,
              "marginLeft": {
                "value": 0,
                "unit": 0
              },
              "marginTop": {
                "value": 0,
                "unit": 0
              },
              "marginRight": {
                "value": 0,
                "unit": 0
              },
              "marginBottom": {
                "value": 0,
                "unit": 0
              },
              "insetLeft": {
                "value": 0,
                "unit": 0
              },
              "insetTop": {
                "value": 0,
                "unit": 0
              },
              "insetRight": {
                "value": 0,
                "unit": 0
              },
              "insetBottom": {
                "value": 0,
                "unit": 0
              }
            }
          },
          {
            "type": "UIVisual",
            "data": {
              "visualType": 1,
              "texture": 0,
              "color": {
                "r": 0,
                "g": 0,
                "b": 0,
                "a": 0.5
              },
              "uvOffset": {
                "x": 0,
                "y": 0
              },
              "uvScale": {
                "x": 1,
                "y": 1
              },
              "sliceBorder": {
                "x": 0,
                "y": 0,
                "z": 0,
                "w": 0
              },
              "tileSize": {
                "x": 32,
                "y": 32
              },
              "fillMethod": 0,
              "fillOrigin": 0,
              "fillAmount": 1,
              "material": 0,
              "enabled": true
            }
          },
          {
            "type": "ThemeStyle",
            "data": {
              "visual": "backdrop"
            }
          },
          {
            "type": "Interactable",
            "data": {
              "enabled": true,
              "blockRaycast": true,
              "raycastTarget": true
            }
          },
          {
            "type": "UIDialog",
            "data": {
              "closeOnEscape": true,
              "closeOnBackdrop": true
            }
          }
        ],
        "visible": true
      },
      {
        "prefabEntityId": "1",
        "name": "Node",
        "parent": "0",
        "children": [],
        "components": [
          {
            "type": "Transform",
            "data": {
              "position": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "rotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "scale": {
                "x": 1,
                "y": 1,
                "z": 1
              },
              "worldPosition": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldRotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldScale": {
                "x": 1,
                "y": 1,
                "z": 1
              }
            }
          },
          {
            "type": "UINode",
            "data": {
              "position": 1,
              "display": 0,
              "width": {
                "value": 400,
                "unit": 0
              },
              "height": {
                "value": 300,
                "unit": 0
              },
              "minWidth": {
                "value": 0,
                "unit": 2
              },
              "minHeight": {
                "value": 0,
                "unit": 2
              },
              "maxWidth": {
                "value": 0,
                "unit": 2
              },
              "maxHeight": {
                "value": 0,
                "unit": 2
              },
              "flexGrow": 0,
              "flexShrink": 1,
              "flexBasis": {
                "value": 0,
                "unit": 2
              },
              "alignSelf": 0,
              "marginLeft": {
                "value": -200,
                "unit": 0
              },
              "marginTop": {
                "value": -150,
                "unit": 0
              },
              "marginRight": {
                "value": 0,
                "unit": 0
              },
              "marginBottom": {
                "value": 0,
                "unit": 0
              },
              "insetLeft": {
                "value": 50,
                "unit": 1
              },
              "insetTop": {
                "value": 50,
                "unit": 1
              },
              "insetRight": {
                "value": 0,
                "unit": 2
              },
              "insetBottom": {
                "value": 0,
                "unit": 2
              }
            }
          },
          {
            "type": "UIVisual",
            "data": {
              "visualType": 1,
              "texture": 0,
              "color": {
                "r": 0.16,
                "g": 0.16,
                "b": 0.18,
                "a": 1
              },
              "uvOffset": {
                "x": 0,
                "y": 0
              },
              "uvScale": {
                "x": 1,
                "y": 1
              },
              "sliceBorder": {
                "x": 0,
                "y": 0,
                "z": 0,
                "w": 0
              },
              "tileSize": {
                "x": 32,
                "y": 32
              },
              "fillMethod": 0,
              "fillOrigin": 0,
              "fillAmount": 1,
              "material": 0,
              "enabled": true
            }
          },
          {
            "type": "ThemeStyle",
            "data": {
              "visual": "surface"
            }
          },
          {
            "type": "Interactable",
            "data": {
              "enabled": true,
              "blockRaycast": true,
              "raycastTarget": true
            }
          }
        ],
        "visible": true
      }
    ]
  },
  "TextInput": {
    "version": "2",
    "name": "TextInput",
    "rootEntityId": "0",
    "entities": [
      {
        "prefabEntityId": "0",
        "name": "TextInput",
        "parent": null,
        "children": [],
        "components": [
          {
            "type": "Transform",
            "data": {
              "position": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "rotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "scale": {
                "x": 1,
                "y": 1,
                "z": 1
              },
              "worldPosition": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldRotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldScale": {
                "x": 1,
                "y": 1,
                "z": 1
              }
            }
          },
          {
            "type": "UINode",
            "data": {
              "position": 0,
              "display": 0,
              "width": {
                "value": 220,
                "unit": 0
              },
              "height": {
                "value": 32,
                "unit": 0
              },
              "minWidth": {
                "value": 0,
                "unit": 2
              },
              "minHeight": {
                "value": 0,
                "unit": 2
              },
              "maxWidth": {
                "value": 0,
                "unit": 2
              },
              "maxHeight": {
                "value": 0,
                "unit": 2
              },
              "flexGrow": 0,
              "flexShrink": 1,
              "flexBasis": {
                "value": 0,
                "unit": 2
              },
              "alignSelf": 0,
              "marginLeft": {
                "value": 0,
                "unit": 0
              },
              "marginTop": {
                "value": 0,
                "unit": 0
              },
              "marginRight": {
                "value": 0,
                "unit": 0
              },
              "marginBottom": {
                "value": 0,
                "unit": 0
              },
              "insetLeft": {
                "value": 0,
                "unit": 2
              },
              "insetTop": {
                "value": 0,
                "unit": 2
              },
              "insetRight": {
                "value": 0,
                "unit": 2
              },
              "insetBottom": {
                "value": 0,
                "unit": 2
              }
            }
          },
          {
            "type": "Interactable",
            "data": {
              "enabled": true,
              "blockRaycast": true,
              "raycastTarget": true
            }
          },
          {
            "type": "Focusable",
            "data": {
              "tabIndex": 0,
              "isFocused": false
            }
          },
          {
            "type": "TextInput",
            "data": {
              "value": "",
              "placeholder": "Text…",
              "placeholderColor": {
                "r": 0.92,
                "g": 0.92,
                "b": 0.94,
                "a": 0.5
              },
              "fontFamily": "Arial",
              "fontSize": 14,
              "color": {
                "r": 0.92,
                "g": 0.92,
                "b": 0.94,
                "a": 1
              },
              "backgroundColor": {
                "r": 0.22,
                "g": 0.22,
                "b": 0.26,
                "a": 1
              },
              "padding": 6,
              "maxLength": 0,
              "multiline": false,
              "password": false,
              "readOnly": false,
              "focused": false,
              "cursorPos": 0,
              "dirty": true,
              "renderMode": 0
            }
          },
          {
            "type": "ThemeStyle",
            "data": {
              "input": {
                "background": "control",
                "text": "text",
                "placeholder": "text"
              }
            }
          }
        ],
        "visible": true
      }
    ]
  },
  "Progress": {
    "version": "2",
    "name": "Progress",
    "rootEntityId": "0",
    "entities": [
      {
        "prefabEntityId": "0",
        "name": "Progress",
        "parent": null,
        "children": [
          "1"
        ],
        "components": [
          {
            "type": "Transform",
            "data": {
              "position": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "rotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "scale": {
                "x": 1,
                "y": 1,
                "z": 1
              },
              "worldPosition": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldRotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldScale": {
                "x": 1,
                "y": 1,
                "z": 1
              }
            }
          },
          {
            "type": "UINode",
            "data": {
              "position": 0,
              "display": 0,
              "width": {
                "value": 200,
                "unit": 0
              },
              "height": {
                "value": 14,
                "unit": 0
              },
              "minWidth": {
                "value": 0,
                "unit": 2
              },
              "minHeight": {
                "value": 0,
                "unit": 2
              },
              "maxWidth": {
                "value": 0,
                "unit": 2
              },
              "maxHeight": {
                "value": 0,
                "unit": 2
              },
              "flexGrow": 0,
              "flexShrink": 1,
              "flexBasis": {
                "value": 0,
                "unit": 2
              },
              "alignSelf": 0,
              "marginLeft": {
                "value": 0,
                "unit": 0
              },
              "marginTop": {
                "value": 0,
                "unit": 0
              },
              "marginRight": {
                "value": 0,
                "unit": 0
              },
              "marginBottom": {
                "value": 0,
                "unit": 0
              },
              "insetLeft": {
                "value": 0,
                "unit": 2
              },
              "insetTop": {
                "value": 0,
                "unit": 2
              },
              "insetRight": {
                "value": 0,
                "unit": 2
              },
              "insetBottom": {
                "value": 0,
                "unit": 2
              }
            }
          },
          {
            "type": "UIVisual",
            "data": {
              "visualType": 1,
              "texture": 0,
              "color": {
                "r": 0.15,
                "g": 0.15,
                "b": 0.15,
                "a": 1
              },
              "uvOffset": {
                "x": 0,
                "y": 0
              },
              "uvScale": {
                "x": 1,
                "y": 1
              },
              "sliceBorder": {
                "x": 0,
                "y": 0,
                "z": 0,
                "w": 0
              },
              "tileSize": {
                "x": 32,
                "y": 32
              },
              "fillMethod": 0,
              "fillOrigin": 0,
              "fillAmount": 1,
              "material": 0,
              "enabled": true
            }
          },
          {
            "type": "ThemeStyle",
            "data": {
              "visual": "track"
            }
          }
        ],
        "visible": true
      },
      {
        "prefabEntityId": "1",
        "name": "Node",
        "parent": "0",
        "children": [],
        "components": [
          {
            "type": "Transform",
            "data": {
              "position": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "rotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "scale": {
                "x": 1,
                "y": 1,
                "z": 1
              },
              "worldPosition": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldRotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldScale": {
                "x": 1,
                "y": 1,
                "z": 1
              }
            }
          },
          {
            "type": "UINode",
            "data": {
              "position": 1,
              "display": 0,
              "width": {
                "value": 0,
                "unit": 2
              },
              "height": {
                "value": 0,
                "unit": 2
              },
              "minWidth": {
                "value": 0,
                "unit": 2
              },
              "minHeight": {
                "value": 0,
                "unit": 2
              },
              "maxWidth": {
                "value": 0,
                "unit": 2
              },
              "maxHeight": {
                "value": 0,
                "unit": 2
              },
              "flexGrow": 0,
              "flexShrink": 1,
              "flexBasis": {
                "value": 0,
                "unit": 2
              },
              "alignSelf": 0,
              "marginLeft": {
                "value": 0,
                "unit": 0
              },
              "marginTop": {
                "value": 0,
                "unit": 0
              },
              "marginRight": {
                "value": 0,
                "unit": 0
              },
              "marginBottom": {
                "value": 0,
                "unit": 0
              },
              "insetLeft": {
                "value": 0,
                "unit": 0
              },
              "insetTop": {
                "value": 0,
                "unit": 0
              },
              "insetRight": {
                "value": 0,
                "unit": 0
              },
              "insetBottom": {
                "value": 0,
                "unit": 0
              }
            }
          },
          {
            "type": "UIVisual",
            "data": {
              "visualType": 5,
              "texture": 0,
              "color": {
                "r": 0.25,
                "g": 0.56,
                "b": 0.96,
                "a": 1
              },
              "uvOffset": {
                "x": 0,
                "y": 0
              },
              "uvScale": {
                "x": 1,
                "y": 1
              },
              "sliceBorder": {
                "x": 0,
                "y": 0,
                "z": 0,
                "w": 0
              },
              "tileSize": {
                "x": 32,
                "y": 32
              },
              "fillMethod": 0,
              "fillOrigin": 0,
              "fillAmount": 0.4,
              "material": 0,
              "enabled": true
            }
          },
          {
            "type": "ThemeStyle",
            "data": {
              "visual": "primary"
            }
          }
        ],
        "visible": true
      }
    ]
  },
  "Dropdown": {
    "version": "2",
    "name": "Dropdown",
    "rootEntityId": "0",
    "entities": [
      {
        "prefabEntityId": "0",
        "name": "Dropdown",
        "parent": null,
        "children": [
          "1"
        ],
        "components": [
          {
            "type": "Transform",
            "data": {
              "position": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "rotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "scale": {
                "x": 1,
                "y": 1,
                "z": 1
              },
              "worldPosition": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldRotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldScale": {
                "x": 1,
                "y": 1,
                "z": 1
              }
            }
          },
          {
            "type": "UINode",
            "data": {
              "position": 0,
              "display": 0,
              "width": {
                "value": 150,
                "unit": 0
              },
              "height": {
                "value": 34,
                "unit": 0
              },
              "minWidth": {
                "value": 0,
                "unit": 2
              },
              "minHeight": {
                "value": 0,
                "unit": 2
              },
              "maxWidth": {
                "value": 0,
                "unit": 2
              },
              "maxHeight": {
                "value": 0,
                "unit": 2
              },
              "flexGrow": 0,
              "flexShrink": 1,
              "flexBasis": {
                "value": 0,
                "unit": 2
              },
              "alignSelf": 0,
              "marginLeft": {
                "value": 0,
                "unit": 0
              },
              "marginTop": {
                "value": 0,
                "unit": 0
              },
              "marginRight": {
                "value": 0,
                "unit": 0
              },
              "marginBottom": {
                "value": 0,
                "unit": 0
              },
              "insetLeft": {
                "value": 0,
                "unit": 2
              },
              "insetTop": {
                "value": 0,
                "unit": 2
              },
              "insetRight": {
                "value": 0,
                "unit": 2
              },
              "insetBottom": {
                "value": 0,
                "unit": 2
              }
            }
          },
          {
            "type": "UIVisual",
            "data": {
              "visualType": 1,
              "texture": 0,
              "color": {
                "r": 0.22,
                "g": 0.22,
                "b": 0.26,
                "a": 1
              },
              "uvOffset": {
                "x": 0,
                "y": 0
              },
              "uvScale": {
                "x": 1,
                "y": 1
              },
              "sliceBorder": {
                "x": 0,
                "y": 0,
                "z": 0,
                "w": 0
              },
              "tileSize": {
                "x": 32,
                "y": 32
              },
              "fillMethod": 0,
              "fillOrigin": 0,
              "fillAmount": 1,
              "material": 0,
              "enabled": true
            }
          },
          {
            "type": "Interactable",
            "data": {
              "enabled": true,
              "blockRaycast": true,
              "raycastTarget": true
            }
          },
          {
            "type": "Focusable",
            "data": {
              "tabIndex": 0,
              "isFocused": false
            }
          },
          {
            "type": "UIController",
            "data": {
              "controllers": [
                {
                  "name": "$interaction",
                  "pages": [
                    "normal",
                    "hover",
                    "pressed"
                  ],
                  "current": "normal"
                }
              ]
            }
          },
          {
            "type": "UIGear",
            "data": {
              "bindings": [
                {
                  "controller": "$interaction",
                  "component": "UIVisual",
                  "property": "color",
                  "pages": {
                    "normal": {
                      "r": 0.22,
                      "g": 0.22,
                      "b": 0.26,
                      "a": 1
                    },
                    "hover": {
                      "r": 0.28,
                      "g": 0.28,
                      "b": 0.32,
                      "a": 1
                    },
                    "pressed": {
                      "r": 0.18,
                      "g": 0.18,
                      "b": 0.22,
                      "a": 1
                    }
                  }
                }
              ]
            }
          },
          {
            "type": "ThemeStyle",
            "data": {
              "states": {
                "normal": "control",
                "hover": "controlHover",
                "pressed": "controlActive"
              }
            }
          },
          {
            "type": "UIDropdown",
            "data": {
              "options": [
                "One",
                "Two",
                "Three"
              ],
              "selectedIndex": 0,
              "optionHeight": 30,
              "label": "1"
            }
          }
        ],
        "visible": true
      },
      {
        "prefabEntityId": "1",
        "name": "Label",
        "parent": "0",
        "children": [],
        "components": [
          {
            "type": "Transform",
            "data": {
              "position": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "rotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "scale": {
                "x": 1,
                "y": 1,
                "z": 1
              },
              "worldPosition": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldRotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldScale": {
                "x": 1,
                "y": 1,
                "z": 1
              }
            }
          },
          {
            "type": "UINode",
            "data": {
              "position": 1,
              "display": 0,
              "width": {
                "value": 0,
                "unit": 2
              },
              "height": {
                "value": 0,
                "unit": 2
              },
              "minWidth": {
                "value": 0,
                "unit": 2
              },
              "minHeight": {
                "value": 0,
                "unit": 2
              },
              "maxWidth": {
                "value": 0,
                "unit": 2
              },
              "maxHeight": {
                "value": 0,
                "unit": 2
              },
              "flexGrow": 0,
              "flexShrink": 1,
              "flexBasis": {
                "value": 0,
                "unit": 2
              },
              "alignSelf": 0,
              "marginLeft": {
                "value": 0,
                "unit": 0
              },
              "marginTop": {
                "value": 0,
                "unit": 0
              },
              "marginRight": {
                "value": 0,
                "unit": 0
              },
              "marginBottom": {
                "value": 0,
                "unit": 0
              },
              "insetLeft": {
                "value": 0,
                "unit": 0
              },
              "insetTop": {
                "value": 0,
                "unit": 0
              },
              "insetRight": {
                "value": 0,
                "unit": 0
              },
              "insetBottom": {
                "value": 0,
                "unit": 0
              }
            }
          },
          {
            "type": "Text",
            "data": {
              "content": "One",
              "i18nKey": "",
              "fontFamily": "Arial",
              "fontSize": 14,
              "color": {
                "r": 0.92,
                "g": 0.92,
                "b": 0.94,
                "a": 1
              },
              "align": 1,
              "verticalAlign": 1,
              "wordWrap": false,
              "overflow": 0,
              "lineHeight": 1.2,
              "bold": false,
              "italic": false,
              "strokeColor": {
                "r": 0,
                "g": 0,
                "b": 0,
                "a": 1
              },
              "strokeWidth": 0,
              "shadowColor": {
                "r": 0,
                "g": 0,
                "b": 0,
                "a": 1
              },
              "shadowBlur": 0,
              "shadowOffsetX": 0,
              "shadowOffsetY": 0,
              "richText": false,
              "renderMode": 0,
              "enabled": true
            }
          },
          {
            "type": "ThemeStyle",
            "data": {
              "text": "text"
            }
          }
        ],
        "visible": true
      }
    ]
  },
  "ListView": {
    "version": "2",
    "name": "ListView",
    "rootEntityId": "0",
    "entities": [
      {
        "prefabEntityId": "0",
        "name": "ListView",
        "parent": null,
        "children": [
          "1"
        ],
        "components": [
          {
            "type": "Transform",
            "data": {
              "position": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "rotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "scale": {
                "x": 1,
                "y": 1,
                "z": 1
              },
              "worldPosition": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldRotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldScale": {
                "x": 1,
                "y": 1,
                "z": 1
              }
            }
          },
          {
            "type": "UINode",
            "data": {
              "position": 0,
              "display": 0,
              "width": {
                "value": 240,
                "unit": 0
              },
              "height": {
                "value": 320,
                "unit": 0
              },
              "minWidth": {
                "value": 0,
                "unit": 2
              },
              "minHeight": {
                "value": 0,
                "unit": 2
              },
              "maxWidth": {
                "value": 0,
                "unit": 2
              },
              "maxHeight": {
                "value": 0,
                "unit": 2
              },
              "flexGrow": 0,
              "flexShrink": 1,
              "flexBasis": {
                "value": 0,
                "unit": 2
              },
              "alignSelf": 0,
              "marginLeft": {
                "value": 0,
                "unit": 0
              },
              "marginTop": {
                "value": 0,
                "unit": 0
              },
              "marginRight": {
                "value": 0,
                "unit": 0
              },
              "marginBottom": {
                "value": 0,
                "unit": 0
              },
              "insetLeft": {
                "value": 0,
                "unit": 2
              },
              "insetTop": {
                "value": 0,
                "unit": 2
              },
              "insetRight": {
                "value": 0,
                "unit": 2
              },
              "insetBottom": {
                "value": 0,
                "unit": 2
              }
            }
          },
          {
            "type": "UIVisual",
            "data": {
              "visualType": 1,
              "texture": 0,
              "color": {
                "r": 0.22,
                "g": 0.22,
                "b": 0.26,
                "a": 1
              },
              "uvOffset": {
                "x": 0,
                "y": 0
              },
              "uvScale": {
                "x": 1,
                "y": 1
              },
              "sliceBorder": {
                "x": 0,
                "y": 0,
                "z": 0,
                "w": 0
              },
              "tileSize": {
                "x": 32,
                "y": 32
              },
              "fillMethod": 0,
              "fillOrigin": 0,
              "fillAmount": 1,
              "material": 0,
              "enabled": true
            }
          },
          {
            "type": "ThemeStyle",
            "data": {
              "visual": "control"
            }
          },
          {
            "type": "UIMask",
            "data": {
              "enabled": true,
              "mode": 0
            }
          },
          {
            "type": "Interactable",
            "data": {
              "enabled": true,
              "blockRaycast": true,
              "raycastTarget": true
            }
          }
        ],
        "visible": true
      },
      {
        "prefabEntityId": "1",
        "name": "Label",
        "parent": "0",
        "children": [],
        "components": [
          {
            "type": "Transform",
            "data": {
              "position": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "rotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "scale": {
                "x": 1,
                "y": 1,
                "z": 1
              },
              "worldPosition": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldRotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldScale": {
                "x": 1,
                "y": 1,
                "z": 1
              }
            }
          },
          {
            "type": "UINode",
            "data": {
              "position": 1,
              "display": 0,
              "width": {
                "value": 0,
                "unit": 2
              },
              "height": {
                "value": 0,
                "unit": 2
              },
              "minWidth": {
                "value": 0,
                "unit": 2
              },
              "minHeight": {
                "value": 0,
                "unit": 2
              },
              "maxWidth": {
                "value": 0,
                "unit": 2
              },
              "maxHeight": {
                "value": 0,
                "unit": 2
              },
              "flexGrow": 0,
              "flexShrink": 1,
              "flexBasis": {
                "value": 0,
                "unit": 2
              },
              "alignSelf": 0,
              "marginLeft": {
                "value": 0,
                "unit": 0
              },
              "marginTop": {
                "value": 0,
                "unit": 0
              },
              "marginRight": {
                "value": 0,
                "unit": 0
              },
              "marginBottom": {
                "value": 0,
                "unit": 0
              },
              "insetLeft": {
                "value": 0,
                "unit": 0
              },
              "insetTop": {
                "value": 0,
                "unit": 0
              },
              "insetRight": {
                "value": 0,
                "unit": 0
              },
              "insetBottom": {
                "value": 0,
                "unit": 0
              }
            }
          },
          {
            "type": "Text",
            "data": {
              "content": "List View",
              "i18nKey": "",
              "fontFamily": "Arial",
              "fontSize": 14,
              "color": {
                "r": 0.92,
                "g": 0.92,
                "b": 0.94,
                "a": 1
              },
              "align": 1,
              "verticalAlign": 1,
              "wordWrap": false,
              "overflow": 0,
              "lineHeight": 1.2,
              "bold": false,
              "italic": false,
              "strokeColor": {
                "r": 0,
                "g": 0,
                "b": 0,
                "a": 1
              },
              "strokeWidth": 0,
              "shadowColor": {
                "r": 0,
                "g": 0,
                "b": 0,
                "a": 1
              },
              "shadowBlur": 0,
              "shadowOffsetX": 0,
              "shadowOffsetY": 0,
              "richText": false,
              "renderMode": 0,
              "enabled": true
            }
          },
          {
            "type": "ThemeStyle",
            "data": {
              "text": "text"
            }
          }
        ],
        "visible": true
      }
    ]
  },
  "ScrollView": {
    "version": "2",
    "name": "ScrollView",
    "rootEntityId": "0",
    "entities": [
      {
        "prefabEntityId": "0",
        "name": "ScrollView",
        "parent": null,
        "children": [
          "1"
        ],
        "components": [
          {
            "type": "Transform",
            "data": {
              "position": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "rotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "scale": {
                "x": 1,
                "y": 1,
                "z": 1
              },
              "worldPosition": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldRotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldScale": {
                "x": 1,
                "y": 1,
                "z": 1
              }
            }
          },
          {
            "type": "UINode",
            "data": {
              "position": 0,
              "display": 0,
              "width": {
                "value": 240,
                "unit": 0
              },
              "height": {
                "value": 320,
                "unit": 0
              },
              "minWidth": {
                "value": 0,
                "unit": 2
              },
              "minHeight": {
                "value": 0,
                "unit": 2
              },
              "maxWidth": {
                "value": 0,
                "unit": 2
              },
              "maxHeight": {
                "value": 0,
                "unit": 2
              },
              "flexGrow": 0,
              "flexShrink": 1,
              "flexBasis": {
                "value": 0,
                "unit": 2
              },
              "alignSelf": 0,
              "marginLeft": {
                "value": 0,
                "unit": 0
              },
              "marginTop": {
                "value": 0,
                "unit": 0
              },
              "marginRight": {
                "value": 0,
                "unit": 0
              },
              "marginBottom": {
                "value": 0,
                "unit": 0
              },
              "insetLeft": {
                "value": 0,
                "unit": 2
              },
              "insetTop": {
                "value": 0,
                "unit": 2
              },
              "insetRight": {
                "value": 0,
                "unit": 2
              },
              "insetBottom": {
                "value": 0,
                "unit": 2
              }
            }
          },
          {
            "type": "UIVisual",
            "data": {
              "visualType": 1,
              "texture": 0,
              "color": {
                "r": 0.22,
                "g": 0.22,
                "b": 0.26,
                "a": 1
              },
              "uvOffset": {
                "x": 0,
                "y": 0
              },
              "uvScale": {
                "x": 1,
                "y": 1
              },
              "sliceBorder": {
                "x": 0,
                "y": 0,
                "z": 0,
                "w": 0
              },
              "tileSize": {
                "x": 32,
                "y": 32
              },
              "fillMethod": 0,
              "fillOrigin": 0,
              "fillAmount": 1,
              "material": 0,
              "enabled": true
            }
          },
          {
            "type": "ThemeStyle",
            "data": {
              "visual": "control"
            }
          },
          {
            "type": "UIMask",
            "data": {
              "enabled": true,
              "mode": 0
            }
          },
          {
            "type": "Interactable",
            "data": {
              "enabled": true,
              "blockRaycast": true,
              "raycastTarget": true
            }
          }
        ],
        "visible": true
      },
      {
        "prefabEntityId": "1",
        "name": "Node",
        "parent": "0",
        "children": [],
        "components": [
          {
            "type": "Transform",
            "data": {
              "position": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "rotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "scale": {
                "x": 1,
                "y": 1,
                "z": 1
              },
              "worldPosition": {
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldRotation": {
                "w": 1,
                "x": 0,
                "y": 0,
                "z": 0
              },
              "worldScale": {
                "x": 1,
                "y": 1,
                "z": 1
              }
            }
          },
          {
            "type": "UINode",
            "data": {
              "position": 1,
              "display": 0,
              "width": {
                "value": 240,
                "unit": 0
              },
              "height": {
                "value": 640,
                "unit": 0
              },
              "minWidth": {
                "value": 0,
                "unit": 2
              },
              "minHeight": {
                "value": 0,
                "unit": 2
              },
              "maxWidth": {
                "value": 0,
                "unit": 2
              },
              "maxHeight": {
                "value": 0,
                "unit": 2
              },
              "flexGrow": 0,
              "flexShrink": 1,
              "flexBasis": {
                "value": 0,
                "unit": 2
              },
              "alignSelf": 0,
              "marginLeft": {
                "value": 0,
                "unit": 0
              },
              "marginTop": {
                "value": 0,
                "unit": 0
              },
              "marginRight": {
                "value": 0,
                "unit": 0
              },
              "marginBottom": {
                "value": 0,
                "unit": 0
              },
              "insetLeft": {
                "value": 0,
                "unit": 0
              },
              "insetTop": {
                "value": 0,
                "unit": 0
              },
              "insetRight": {
                "value": 0,
                "unit": 2
              },
              "insetBottom": {
                "value": 0,
                "unit": 2
              }
            }
          }
        ],
        "visible": true
      }
    ]
  }
};

export const BUILTIN_UI_WIDGET_NAMES = ["Button","Toggle","Slider","Dialog","TextInput","Progress","Dropdown","ListView","ScrollView"] as const;
