"""Component metadata generator (component.generated.ts)."""

from typing import Dict, List, Optional
from ..data import Component, Enum, Property
from ..type_system import TypeSystem
from ..field_utils import (
    is_color_field, build_enum_value_map, convert_default_ts,
)


class MetadataGenerator:
    """Generates component.generated.ts with defaults and metadata."""

    def __init__(self, components: List[Component], enums: List[Enum]):
        self.components = components
        self.enums = enums
        self.types = TypeSystem(enums)
        self._enum_values = build_enum_value_map(enums)

    def _get_asset_fields(self, comp: Component) -> List[Dict[str, str]]:
        fields = []
        for prop in comp.properties:
            asset_type = prop.annotations.get('asset')
            if asset_type and asset_type not in ('spine_skeleton', 'spine_atlas'):
                fields.append({'field': prop.name, 'type': asset_type})
        return fields

    def _get_spine_descriptor(self, comp: Component) -> Optional[Dict[str, str]]:
        skel_field = atlas_field = None
        for prop in comp.properties:
            asset_type = prop.annotations.get('asset')
            if asset_type == 'spine_skeleton':
                skel_field = prop.name
            elif asset_type == 'spine_atlas':
                atlas_field = prop.name
        if skel_field and atlas_field:
            return {'skeletonField': skel_field, 'atlasField': atlas_field}
        return None

    def _get_entity_fields(self, comp: Component) -> List[str]:
        return [p.name for p in comp.properties if 'entity_ref' in p.annotations]

    def _get_color_fields(self, comp: Component) -> List[str]:
        return [p.name for p in comp.properties if is_color_field(p, self.types)]

    def _get_animatable_fields(self, comp: Component) -> List[str]:
        fields = []
        for prop in comp.properties:
            if 'animatable' not in prop.annotations:
                continue
            t = self.types.clean_type(prop.cpp_type)
            if t == 'glm::vec2':
                fields.extend([f'{prop.name}.x', f'{prop.name}.y'])
            elif t == 'glm::vec3':
                fields.extend([f'{prop.name}.x', f'{prop.name}.y', f'{prop.name}.z'])
            elif t == 'glm::vec4':
                if is_color_field(prop, self.types):
                    fields.extend([f'{prop.name}.r', f'{prop.name}.g', f'{prop.name}.b', f'{prop.name}.a'])
                else:
                    fields.extend([f'{prop.name}.x', f'{prop.name}.y', f'{prop.name}.z', f'{prop.name}.w'])
            elif t == 'glm::quat':
                fields.append(f'{prop.name}.z')
            else:
                fields.append(prop.name)
        return fields

    def generate(self) -> str:
        lines = [
            '/**',
            ' * @file    component.generated.ts',
            ' * @brief   Auto-generated component metadata',
            ' * @details Generated by EHT - DO NOT EDIT',
            ' */',
            '',
            "import type { AssetFieldType } from './scene';",
            '',
            'export interface AssetFieldMeta {',
            '    field: string;',
            '    type: AssetFieldType;',
            '}',
            '',
            'export interface SpineFieldMeta {',
            '    skeletonField: string;',
            '    atlasField: string;',
            '}',
            '',
            'export interface ComponentMetaEntry {',
            '    defaults: Record<string, unknown>;',
            '    assetFields: AssetFieldMeta[];',
            '    spine?: SpineFieldMeta;',
            '    entityFields: string[];',
            '    colorFields: string[];',
            '    animatableFields: string[];',
            '}',
            '',
            'export const COMPONENT_META: Record<string, ComponentMetaEntry> = {',
        ]

        for comp in self.components:
            if not comp.properties:
                continue

            asset_fields = self._get_asset_fields(comp)
            spine = self._get_spine_descriptor(comp)
            entity_fields = self._get_entity_fields(comp)
            color_fields = self._get_color_fields(comp)
            animatable = self._get_animatable_fields(comp)

            lines.append(f'    {comp.name}: {{')
            lines.append('        defaults: {')
            for prop in comp.properties:
                if self.types.is_skip(prop.cpp_type) and prop.cpp_type not in self.types.VECTOR_TYPES:
                    continue
                val = convert_default_ts(prop, self.types, self._enum_values)
                lines.append(f'            {prop.name}: {val},')
            lines.append('        },')

            if asset_fields:
                parts = ', '.join(
                    f"{{ field: '{f['field']}', type: '{f['type']}' as AssetFieldType }}"
                    for f in asset_fields
                )
                lines.append(f'        assetFields: [{parts}],')
            else:
                lines.append('        assetFields: [],')

            if spine:
                lines.append(
                    f"        spine: {{ skeletonField: '{spine['skeletonField']}', "
                    f"atlasField: '{spine['atlasField']}' }},"
                )

            if entity_fields:
                parts = ', '.join(f"'{f}'" for f in entity_fields)
                lines.append(f'        entityFields: [{parts}],')
            else:
                lines.append('        entityFields: [],')

            if color_fields:
                parts = ', '.join(f"'{f}'" for f in color_fields)
                lines.append(f'        colorFields: [{parts}],')
            else:
                lines.append('        colorFields: [],')

            if animatable:
                parts = ', '.join(f"'{f}'" for f in animatable)
                lines.append(f'        animatableFields: [{parts}],')
            else:
                lines.append('        animatableFields: [],')

            lines.append('    },')

        lines.append('};')
        lines.append('')
        return '\n'.join(lines)
