"""TypeScript type definitions generator."""

from typing import List
from ..data import Component, Enum
from ..type_system import TypeSystem


class TypeScriptGenerator:
    def __init__(self, components: List[Component], enums: List[Enum]):
        self.components = components
        self.enums = enums
        self.types = TypeSystem(enums)

    def generate(self) -> str:
        lines = self._gen_header()
        lines.extend(self._gen_enums())
        lines.extend(self._gen_components())
        lines.extend(self._gen_registry())
        lines.extend(self._gen_module())
        return '\n'.join(lines)

    def _gen_header(self) -> List[str]:
        return [
            '/**',
            ' * @file    wasm.generated.ts',
            ' * @brief   ESEngine WASM Bindings TypeScript Definitions',
            ' * @details Generated by EHT - DO NOT EDIT',
            ' */',
            '',
            "import type { Entity, Vec2, Vec3, Vec4, Quat } from './types';",
            '',
            '// Additional Math Types',
            'export interface UVec2 { x: number; y: number; }',
            'export interface Padding { left: number; top: number; right: number; bottom: number; }',
            'export type Mat4 = number[];',
            '',
            '// Emscripten Vector Types',
            'export interface VectorEntity {',
            '    size(): number;',
            '    get(index: number): number;',
            '    push_back(value: number): void;',
            '    set(index: number, value: number): boolean;',
            '    delete(): void;',
            '}',
            '',
        ]

    def _gen_enums(self) -> List[str]:
        if not self.enums:
            return []
        lines = ['// Enums', '']
        for enum in self.enums:
            lines.append(f'export enum {enum.name} {{')
            for i, val in enumerate(enum.values):
                lines.append(f'    {val} = {i},')
            lines.append('}')
            lines.append('')
        return lines

    def _gen_components(self) -> List[str]:
        lines = ['// Components', '']
        for comp in self.components:
            lines.append(f'export interface {comp.name} {{')
            for prop in comp.properties:
                if self.types.is_skip(prop.cpp_type):
                    continue
                ts = self.types.to_typescript(prop.cpp_type)
                lines.append(f'    {prop.name}: {ts};')
            lines.append('}')
            lines.append('')
        return lines

    def _gen_registry(self) -> List[str]:
        lines = [
            '// Registry',
            'export interface Registry {',
            '    create(): Entity;',
            '    destroy(entity: Entity): void;',
            '    valid(entity: Entity): boolean;',
            '    entityCount(): number;',
            '',
        ]
        for comp in self.components:
            n = comp.name
            lines.extend([
                f'    has{n}(entity: Entity): boolean;',
                f'    get{n}(entity: Entity): {n};',
                f'    add{n}(entity: Entity, component: {n}): void;',
                f'    remove{n}(entity: Entity): void;',
            ])
        lines.extend([
            '',
            '    // Hierarchy Utilities',
            '    setParent(child: Entity, parent: Entity): void;',
        ])
        lines.append('}')
        lines.append('')
        return lines

    def _gen_module(self) -> List[str]:
        lines = [
            '// Module',
            'export interface ESEngineModule {',
            '    Registry: new () => Registry;',
        ]
        for comp in self.components:
            lines.append(f'    {comp.name}: new () => {comp.name};')
        lines.extend(['}', ''])
        return lines
