export { Audio } from './Audio';
export { AudioBus, type AudioBusConfig } from './AudioBus';
export { AudioMixer, type AudioMixerConfig } from './AudioMixer';
export { AudioPool, type PooledAudioNode } from './AudioPool';
export { AudioPlugin, audioPlugin, type AudioPluginConfig } from './AudioPlugin';
export { AudioSource, AudioListener, type AudioSourceData, type AudioListenerData } from './AudioComponents';
export { createAudioBackend } from './AudioBackendFactory';
export { AttenuationModel, calculateAttenuation, calculatePanning, type SpatialAudioConfig } from './SpatialAudio';
export { WebAudioBackend, type WebAudioBackendOptions } from './WebAudioBackend';
export { WeChatAudioBackend } from './WeChatAudioBackend';
export type { AudioHandle, AudioBufferHandle, PlayConfig, PlatformAudioBackend } from './PlatformAudioBackend';
