/**
 * @file    wasm.generated.ts
 * @brief   ESEngine WASM Bindings TypeScript Definitions
 * @details Generated by EHT - DO NOT EDIT
 */

import type { Entity, Vec2, Vec3, Vec4, Quat } from '../types';

// Additional Math Types
export interface UVec2 { x: number; y: number; }
export interface Padding { left: number; top: number; right: number; bottom: number; }
export interface Dimension { value: number; unit: number; }
export type Mat4 = number[];

// Emscripten Vector Types
export interface VectorEntity {
    size(): number;
    get(index: number): number;
    push_back(value: number): void;
    set(index: number, value: number): boolean;
    delete(): void;
}

// Enums

export enum AlignContent {
    Start = 0,
    Center = 1,
    End = 2,
    Stretch = 3,
    SpaceBetween = 4,
    SpaceAround = 5,
}

export enum AlignItems {
    Start = 0,
    Center = 1,
    End = 2,
    Stretch = 3,
}

export enum AlignSelf {
    Auto = 0,
    Start = 1,
    Center = 2,
    End = 3,
    Stretch = 4,
}

export enum BodyType {
    Static = 0,
    Kinematic = 1,
    Dynamic = 2,
}

export enum CanvasScaleMode {
    FixedWidth = 0,
    FixedHeight = 1,
    Expand = 2,
    Shrink = 3,
    Match = 4,
}

export enum ClearFlags {
    Nothing = 0,
    Color = 1,
    Depth = 2,
    ColorAndDepth = 3,
}

export enum EmitterShape {
    Point = 0,
    Circle = 1,
    Rectangle = 2,
    Cone = 3,
}

export enum FlexDirection {
    Row = 0,
    Column = 1,
    RowReverse = 2,
    ColumnReverse = 3,
}

export enum FlexWrap {
    NoWrap = 0,
    Wrap = 1,
}

export enum ForceFieldType {
    Directional = 0,
    Point = 1,
    Vortex = 2,
    Drag = 3,
}

export enum JustifyContent {
    Start = 0,
    Center = 1,
    End = 2,
    SpaceBetween = 3,
    SpaceAround = 4,
    SpaceEvenly = 5,
}

export enum LightType {
    Point = 0,
    Directional = 1,
    Ambient = 2,
    Spot = 3,
}

export enum MaskMode {
    Scissor = 0,
    Stencil = 1,
}

export enum ParticleEasing {
    Linear = 0,
    EaseIn = 1,
    EaseOut = 2,
    EaseInOut = 3,
}

export enum ProjectionType {
    Perspective = 0,
    Orthographic = 1,
}

export enum ScrollMovement {
    Clamped = 0,
    Elastic = 1,
}

export enum ShapeType {
    Circle = 0,
    Capsule = 1,
    RoundedRect = 2,
}

export enum SimulationSpace {
    World = 0,
    Local = 1,
}

export enum SubEmitterTrigger {
    Death = 0,
    Birth = 1,
}

export enum TextAlign {
    Left = 0,
    Center = 1,
    Right = 2,
}

export enum TilemapOrientation {
    Orthogonal = 0,
    Isometric = 1,
    Staggered = 2,
    Hexagonal = 3,
}

export enum TilemapStaggerAxis {
    Y = 0,
    X = 1,
}

export enum TilemapStaggerIndex {
    Odd = 0,
    Even = 1,
}

export enum UIDisplay {
    Flex = 0,
    None = 1,
}

export enum UIFillMethod {
    Horizontal = 0,
    Vertical = 1,
    Radial360 = 2,
    Radial90 = 3,
    Radial180 = 4,
}

export enum UIFillOrigin {
    Left = 0,
    Right = 1,
    Bottom = 2,
    Top = 3,
}

export enum UIPointerEvents {
    Auto = 0,
    None = 1,
}

export enum UIPositionType {
    Relative = 0,
    Absolute = 1,
}

export enum UIVisualFit {
    Fill = 0,
    Contain = 1,
    Cover = 2,
}

export enum UIVisualType {
    None = 0,
    SolidColor = 1,
    Image = 2,
    NineSlice = 3,
    Tiled = 4,
    Filled = 5,
}

// Components

export interface BitmapText {
    text: string;
    color: Vec4;
    fontSize: number;
    align: number;
    spacing: number;
    parallax: Vec2;
    layer: number;
    font: number;
    enabled: boolean;
}

export interface BoxCollider {
    halfExtents: Vec2;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
    categoryBits: number;
    maskBits: number;
}

export interface BoxCollider3D {
    halfExtents: Vec3;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
}

export interface Camera {
    projectionType: number;
    fov: number;
    orthoSize: number;
    nearPlane: number;
    farPlane: number;
    aspectRatio: number;
    isActive: boolean;
    priority: number;
    viewport: Vec4;
    clearFlags: number;
    pixelPerfect: boolean;
    cullingMask: number;
}

export interface Canvas {
    designResolution: UVec2;
    pixelsPerUnit: number;
    scaleMode: number;
    matchWidthOrHeight: number;
    backgroundColor: Vec4;
    layer: number;
}

export interface CapsuleCollider {
    radius: number;
    halfHeight: number;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
    categoryBits: number;
    maskBits: number;
}

export interface CapsuleCollider3D {
    radius: number;
    halfHeight: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
}

export interface CharacterController3D {
    velocity: Vec3;
    radius: number;
    halfHeight: number;
    maxSlope: number;
    stepHeight: number;
    snapDown: number;
    mass: number;
    pushForce: number;
    enabled: boolean;
    layer: number;
    isOnFloor: boolean;
    floorNormal: Vec3;
    realVelocity: Vec3;
}

export interface Children {
    entities: VectorEntity;
}

export interface CircleCollider {
    radius: number;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
    categoryBits: number;
    maskBits: number;
}

export interface ConvexCollider3D {
    mesh: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
}

export interface Draggable {
    enabled: boolean;
    dragThreshold: number;
    lockX: boolean;
    lockY: boolean;
    constrainMin: boolean;
    constraintMin: Vec2;
    constrainMax: boolean;
    constraintMax: Vec2;
}

export interface DragonBonesAnimation {
    skeletonPath: string;
    atlasPath: string;
    armature: string;
    animation: string;
    timeScale: number;
    loop: boolean;
    playing: boolean;
    fadeInTime: number;
    flipX: boolean;
    flipY: boolean;
    color: Vec4;
    layer: number;
    skeletonScale: number;
    material: number;
    enabled: boolean;
}

export interface FlexContainer {
    direction: number;
    wrap: number;
    justifyContent: number;
    alignItems: number;
    alignContent: number;
    gap: Vec2;
    padding: Padding;
}

export interface Interactable {
    enabled: boolean;
    blockRaycast: boolean;
    raycastTarget: boolean;
}

export interface Light {
    type: number;
    color: Vec4;
    intensity: number;
    radius: number;
    innerAngle: number;
    outerAngle: number;
    shadowSoftness: number;
    sourceAngle: number;
    shadowDistance: number;
    meshShadows: boolean;
    shadowExtent: number;
    environment: number;
    drawEnvironment: boolean;
    enabled: boolean;
}

export interface MeshCollider3D {
    mesh: number;
    friction: number;
    restitution: number;
    layer: number;
    enabled: boolean;
}

export interface MeshRenderer {
    texture: number;
    normalMap: number;
    color: Vec4;
    layer: number;
    opaque: boolean;
    cullBackfaces: boolean;
    lit: boolean;
    parallax: Vec2;
    material: number;
    enabled: boolean;
    mesh: number;
}

export interface MeshSkin {
    joints: VectorEntity;
}

export interface Parent {
    entity: number;
}

export interface ParticleEmitter {
    rate: number;
    burstCount: number;
    burstInterval: number;
    duration: number;
    looping: boolean;
    playOnStart: boolean;
    maxParticles: number;
    lifetimeMin: number;
    lifetimeMax: number;
    shape: number;
    shapeRadius: number;
    shapeSize: Vec3;
    shapeAngle: number;
    speedMin: number;
    speedMax: number;
    angleSpreadMin: number;
    angleSpreadMax: number;
    startSizeMin: number;
    startSizeMax: number;
    endSizeMin: number;
    endSizeMax: number;
    sizeEasing: number;
    startColor: Vec4;
    endColor: Vec4;
    colorEasing: number;
    rotationMin: number;
    rotationMax: number;
    angularVelocityMin: number;
    angularVelocityMax: number;
    gravity: Vec3;
    damping: number;
    noiseStrength: number;
    noiseFrequency: number;
    noiseScrollSpeed: number;
    noiseOctaves: number;
    texture: number;
    spriteColumns: number;
    spriteRows: number;
    spriteFPS: number;
    spriteLoop: boolean;
    blendMode: number;
    layer: number;
    material: number;
    simulationSpace: number;
    enabled: boolean;
    subEmitterTrigger: number;
    subEmitterChance: number;
    subEmitterInheritVelocity: number;
    subEmitter: number;
    trailEnabled: boolean;
    trailWidth: number;
    trailPoints: number;
    trailMinDistance: number;
    collisionEnabled: boolean;
    collisionFloor: number;
    collisionBounce: number;
    collisionFriction: number;
    collisionLifetimeLoss: number;
}

export interface ParticleForceField {
    type: number;
    strength: number;
    radius: number;
    direction: Vec3;
    falloff: boolean;
    enabled: boolean;
}

export interface RigidBody {
    bodyType: number;
    gravityScale: number;
    linearDamping: number;
    angularDamping: number;
    fixedRotation: boolean;
    bullet: boolean;
    enabled: boolean;
}

export interface RigidBody3D {
    bodyType: number;
    gravityScale: number;
    linearDamping: number;
    angularDamping: number;
    fixedRotation: boolean;
    layer: number;
    continuousCollision: boolean;
    enabled: boolean;
}

export interface SegmentCollider {
    point1: Vec2;
    point2: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
    categoryBits: number;
    maskBits: number;
}

export interface ShadowCaster2D {
    size: Vec2;
    enabled: boolean;
}

export interface ShapeRenderer {
    shapeType: number;
    color: Vec4;
    size: Vec2;
    cornerRadius: number;
    layer: number;
    parallax: Vec2;
    enabled: boolean;
}

export interface SphereCollider3D {
    radius: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
}

export interface SpineAnimation {
    skeletonPath: string;
    atlasPath: string;
    skin: string;
    animation: string;
    timeScale: number;
    loop: boolean;
    playing: boolean;
    flipX: boolean;
    flipY: boolean;
    color: Vec4;
    layer: number;
    skeletonScale: number;
    material: number;
    enabled: boolean;
}

export interface Sprite {
    texture: number;
    color: Vec4;
    size: Vec2;
    pivot: Vec2;
    uvOffset: Vec2;
    uvScale: Vec2;
    layer: number;
    lit: boolean;
    flipX: boolean;
    flipY: boolean;
    tileSize: Vec2;
    tileSpacing: Vec2;
    parallax: Vec2;
    material: number;
    enabled: boolean;
}

export interface TilemapLayer {
    cellSize: Vec2;
    orientation: number;
    hexSideLength: number;
    staggerAxis: number;
    staggerIndex: number;
    originOffset: Vec2;
    tileset: number;
    tilesetColumns: number;
    renderLayer: number;
    tintColor: Vec4;
    opacity: number;
    parallaxFactor: Vec2;
    visible: boolean;
}

export interface TrailRenderer {
    time: number;
    minVertexDistance: number;
    emitting: boolean;
    startWidth: number;
    endWidth: number;
    startColor: Vec4;
    endColor: Vec4;
    texture: number;
    blendMode: number;
    layer: number;
    material: number;
    enabled: boolean;
}

export interface Transform {
    position: Vec3;
    rotation: Quat;
    scale: Vec3;
    worldPosition: Vec3;
    worldRotation: Quat;
    worldScale: Vec3;
}

export interface UIInteraction {
    hovered: boolean;
    pressed: boolean;
    justPressed: boolean;
    justReleased: boolean;
}

export interface UIMask {
    enabled: boolean;
    mode: number;
    alphaCutoff: number;
}

export interface UINode {
    position: number;
    display: number;
    opacity: number;
    pointerEvents: number;
    width: Dimension;
    height: Dimension;
    minWidth: Dimension;
    minHeight: Dimension;
    maxWidth: Dimension;
    maxHeight: Dimension;
    flexGrow: number;
    flexShrink: number;
    flexBasis: Dimension;
    alignSelf: number;
    marginLeft: Dimension;
    marginTop: Dimension;
    marginRight: Dimension;
    marginBottom: Dimension;
    insetLeft: Dimension;
    insetTop: Dimension;
    insetRight: Dimension;
    insetBottom: Dimension;
}

export interface UIScroll {
    enabled: boolean;
    content: number;
    horizontal: boolean;
    vertical: boolean;
    movement: number;
    wheelSpeed: number;
    dragScroll: boolean;
    decelerationRate: number;
}

export interface UIVisual {
    visualType: number;
    texture: number;
    color: Vec4;
    fit: number;
    uvOffset: Vec2;
    uvScale: Vec2;
    sliceBorder: Vec4;
    tileSize: Vec2;
    fillMethod: number;
    fillOrigin: number;
    fillAmount: number;
    material: number;
    enabled: boolean;
}

export interface Velocity {
    linear: Vec3;
    angular: Vec3;
}

// Registry
export interface Registry {
    create(): Entity;
    destroy(entity: Entity): void;
    valid(entity: Entity): boolean;
    entityCount(): number;

    hasBitmapText(entity: Entity): boolean;
    getBitmapText(entity: Entity): BitmapText;
    addBitmapText(entity: Entity, component: BitmapText): void;
    removeBitmapText(entity: Entity): void;
    hasBoxCollider(entity: Entity): boolean;
    getBoxCollider(entity: Entity): BoxCollider;
    addBoxCollider(entity: Entity, component: BoxCollider): void;
    removeBoxCollider(entity: Entity): void;
    hasBoxCollider3D(entity: Entity): boolean;
    getBoxCollider3D(entity: Entity): BoxCollider3D;
    addBoxCollider3D(entity: Entity, component: BoxCollider3D): void;
    removeBoxCollider3D(entity: Entity): void;
    hasCamera(entity: Entity): boolean;
    getCamera(entity: Entity): Camera;
    addCamera(entity: Entity, component: Camera): void;
    removeCamera(entity: Entity): void;
    hasCanvas(entity: Entity): boolean;
    getCanvas(entity: Entity): Canvas;
    addCanvas(entity: Entity, component: Canvas): void;
    removeCanvas(entity: Entity): void;
    hasCapsuleCollider(entity: Entity): boolean;
    getCapsuleCollider(entity: Entity): CapsuleCollider;
    addCapsuleCollider(entity: Entity, component: CapsuleCollider): void;
    removeCapsuleCollider(entity: Entity): void;
    hasCapsuleCollider3D(entity: Entity): boolean;
    getCapsuleCollider3D(entity: Entity): CapsuleCollider3D;
    addCapsuleCollider3D(entity: Entity, component: CapsuleCollider3D): void;
    removeCapsuleCollider3D(entity: Entity): void;
    hasCharacterController3D(entity: Entity): boolean;
    getCharacterController3D(entity: Entity): CharacterController3D;
    addCharacterController3D(entity: Entity, component: CharacterController3D): void;
    removeCharacterController3D(entity: Entity): void;
    hasChildren(entity: Entity): boolean;
    getChildren(entity: Entity): Children;
    addChildren(entity: Entity, component: Children): void;
    removeChildren(entity: Entity): void;
    hasCircleCollider(entity: Entity): boolean;
    getCircleCollider(entity: Entity): CircleCollider;
    addCircleCollider(entity: Entity, component: CircleCollider): void;
    removeCircleCollider(entity: Entity): void;
    hasConvexCollider3D(entity: Entity): boolean;
    getConvexCollider3D(entity: Entity): ConvexCollider3D;
    addConvexCollider3D(entity: Entity, component: ConvexCollider3D): void;
    removeConvexCollider3D(entity: Entity): void;
    hasDraggable(entity: Entity): boolean;
    getDraggable(entity: Entity): Draggable;
    addDraggable(entity: Entity, component: Draggable): void;
    removeDraggable(entity: Entity): void;
    hasDragonBonesAnimation(entity: Entity): boolean;
    getDragonBonesAnimation(entity: Entity): DragonBonesAnimation;
    addDragonBonesAnimation(entity: Entity, component: DragonBonesAnimation): void;
    removeDragonBonesAnimation(entity: Entity): void;
    hasFlexContainer(entity: Entity): boolean;
    getFlexContainer(entity: Entity): FlexContainer;
    addFlexContainer(entity: Entity, component: FlexContainer): void;
    removeFlexContainer(entity: Entity): void;
    hasInteractable(entity: Entity): boolean;
    getInteractable(entity: Entity): Interactable;
    addInteractable(entity: Entity, component: Interactable): void;
    removeInteractable(entity: Entity): void;
    hasLight(entity: Entity): boolean;
    getLight(entity: Entity): Light;
    addLight(entity: Entity, component: Light): void;
    removeLight(entity: Entity): void;
    hasMeshCollider3D(entity: Entity): boolean;
    getMeshCollider3D(entity: Entity): MeshCollider3D;
    addMeshCollider3D(entity: Entity, component: MeshCollider3D): void;
    removeMeshCollider3D(entity: Entity): void;
    hasMeshRenderer(entity: Entity): boolean;
    getMeshRenderer(entity: Entity): MeshRenderer;
    addMeshRenderer(entity: Entity, component: MeshRenderer): void;
    removeMeshRenderer(entity: Entity): void;
    hasMeshSkin(entity: Entity): boolean;
    getMeshSkin(entity: Entity): MeshSkin;
    addMeshSkin(entity: Entity, component: MeshSkin): void;
    removeMeshSkin(entity: Entity): void;
    hasParent(entity: Entity): boolean;
    getParent(entity: Entity): Parent;
    addParent(entity: Entity, component: Parent): void;
    removeParent(entity: Entity): void;
    hasParticleEmitter(entity: Entity): boolean;
    getParticleEmitter(entity: Entity): ParticleEmitter;
    addParticleEmitter(entity: Entity, component: ParticleEmitter): void;
    removeParticleEmitter(entity: Entity): void;
    hasParticleForceField(entity: Entity): boolean;
    getParticleForceField(entity: Entity): ParticleForceField;
    addParticleForceField(entity: Entity, component: ParticleForceField): void;
    removeParticleForceField(entity: Entity): void;
    hasRigidBody(entity: Entity): boolean;
    getRigidBody(entity: Entity): RigidBody;
    addRigidBody(entity: Entity, component: RigidBody): void;
    removeRigidBody(entity: Entity): void;
    hasRigidBody3D(entity: Entity): boolean;
    getRigidBody3D(entity: Entity): RigidBody3D;
    addRigidBody3D(entity: Entity, component: RigidBody3D): void;
    removeRigidBody3D(entity: Entity): void;
    hasSegmentCollider(entity: Entity): boolean;
    getSegmentCollider(entity: Entity): SegmentCollider;
    addSegmentCollider(entity: Entity, component: SegmentCollider): void;
    removeSegmentCollider(entity: Entity): void;
    hasShadowCaster2D(entity: Entity): boolean;
    getShadowCaster2D(entity: Entity): ShadowCaster2D;
    addShadowCaster2D(entity: Entity, component: ShadowCaster2D): void;
    removeShadowCaster2D(entity: Entity): void;
    hasShapeRenderer(entity: Entity): boolean;
    getShapeRenderer(entity: Entity): ShapeRenderer;
    addShapeRenderer(entity: Entity, component: ShapeRenderer): void;
    removeShapeRenderer(entity: Entity): void;
    hasSphereCollider3D(entity: Entity): boolean;
    getSphereCollider3D(entity: Entity): SphereCollider3D;
    addSphereCollider3D(entity: Entity, component: SphereCollider3D): void;
    removeSphereCollider3D(entity: Entity): void;
    hasSpineAnimation(entity: Entity): boolean;
    getSpineAnimation(entity: Entity): SpineAnimation;
    addSpineAnimation(entity: Entity, component: SpineAnimation): void;
    removeSpineAnimation(entity: Entity): void;
    hasSprite(entity: Entity): boolean;
    getSprite(entity: Entity): Sprite;
    addSprite(entity: Entity, component: Sprite): void;
    removeSprite(entity: Entity): void;
    hasTilemapLayer(entity: Entity): boolean;
    getTilemapLayer(entity: Entity): TilemapLayer;
    addTilemapLayer(entity: Entity, component: TilemapLayer): void;
    removeTilemapLayer(entity: Entity): void;
    hasTrailRenderer(entity: Entity): boolean;
    getTrailRenderer(entity: Entity): TrailRenderer;
    addTrailRenderer(entity: Entity, component: TrailRenderer): void;
    removeTrailRenderer(entity: Entity): void;
    hasTransform(entity: Entity): boolean;
    getTransform(entity: Entity): Transform;
    addTransform(entity: Entity, component: Transform): void;
    removeTransform(entity: Entity): void;
    hasUIInteraction(entity: Entity): boolean;
    getUIInteraction(entity: Entity): UIInteraction;
    addUIInteraction(entity: Entity, component: UIInteraction): void;
    removeUIInteraction(entity: Entity): void;
    hasUIMask(entity: Entity): boolean;
    getUIMask(entity: Entity): UIMask;
    addUIMask(entity: Entity, component: UIMask): void;
    removeUIMask(entity: Entity): void;
    hasUINode(entity: Entity): boolean;
    getUINode(entity: Entity): UINode;
    addUINode(entity: Entity, component: UINode): void;
    removeUINode(entity: Entity): void;
    hasUIScroll(entity: Entity): boolean;
    getUIScroll(entity: Entity): UIScroll;
    addUIScroll(entity: Entity, component: UIScroll): void;
    removeUIScroll(entity: Entity): void;
    hasUIVisual(entity: Entity): boolean;
    getUIVisual(entity: Entity): UIVisual;
    addUIVisual(entity: Entity, component: UIVisual): void;
    removeUIVisual(entity: Entity): void;
    hasVelocity(entity: Entity): boolean;
    getVelocity(entity: Entity): Velocity;
    addVelocity(entity: Entity, component: Velocity): void;
    removeVelocity(entity: Entity): void;

    // Hierarchy Utilities
    setParent(child: Entity, parent: Entity): void;
}

// Module
export interface ESEngineModule {
    Registry: new () => Registry;
    /**
     * Authoritative list of component names this WASM build exposes
     * on the Registry. Used by BuiltinBridge to detect drift between
     * the shipped SDK and the actual WASM module.
     */
    getBuiltinComponentNames(): string[];
    BitmapText: new () => BitmapText;
    BoxCollider: new () => BoxCollider;
    BoxCollider3D: new () => BoxCollider3D;
    Camera: new () => Camera;
    Canvas: new () => Canvas;
    CapsuleCollider: new () => CapsuleCollider;
    CapsuleCollider3D: new () => CapsuleCollider3D;
    CharacterController3D: new () => CharacterController3D;
    Children: new () => Children;
    CircleCollider: new () => CircleCollider;
    ConvexCollider3D: new () => ConvexCollider3D;
    Draggable: new () => Draggable;
    DragonBonesAnimation: new () => DragonBonesAnimation;
    FlexContainer: new () => FlexContainer;
    Interactable: new () => Interactable;
    Light: new () => Light;
    MeshCollider3D: new () => MeshCollider3D;
    MeshRenderer: new () => MeshRenderer;
    MeshSkin: new () => MeshSkin;
    Parent: new () => Parent;
    ParticleEmitter: new () => ParticleEmitter;
    ParticleForceField: new () => ParticleForceField;
    RigidBody: new () => RigidBody;
    RigidBody3D: new () => RigidBody3D;
    SegmentCollider: new () => SegmentCollider;
    ShadowCaster2D: new () => ShadowCaster2D;
    ShapeRenderer: new () => ShapeRenderer;
    SphereCollider3D: new () => SphereCollider3D;
    SpineAnimation: new () => SpineAnimation;
    Sprite: new () => Sprite;
    TilemapLayer: new () => TilemapLayer;
    TrailRenderer: new () => TrailRenderer;
    Transform: new () => Transform;
    UIInteraction: new () => UIInteraction;
    UIMask: new () => UIMask;
    UINode: new () => UINode;
    UIScroll: new () => UIScroll;
    UIVisual: new () => UIVisual;
    Velocity: new () => Velocity;
}
