// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (c) 2024-present ESEngine Team
/**
 * @file    codegen.ts
 * @brief   EIR -> C, against the SysCtx contract (docs/REARCH_AOT.md §10 Stage 2).
 *
 * @details The backend emits C rather than LLVM IR, and the reason is in §17:
 *          the LLVM half is a solved problem someone else maintains, and one C
 *          output serves clang for aarch64 and emcc for wasm at once. What is
 *          NOT solved anywhere is the half above it — EIR, and this lowering.
 *
 *          Two properties are the whole point, and both are visible in the
 *          output rather than asserted about it:
 *
 *          - **Zero calls.** A generated system's only external names are the
 *            static inlines in the runtime header. That is §6.5's empty import
 *            section, arrived at by construction rather than by trimming.
 *          - **Loads at constant offsets.** Every component field is
 *            `es_f32(base + ES_OFF_Comp_field)`, and the offset came from EHT.
 *            The offsets are macros so a debugger and a reader see the name.
 *
 *          Bit-for-bit agreement with node is a REQUIREMENT, not an aspiration,
 *          because the differential pixel gate compares frames. Three things
 *          here exist only for it: the Math shims (C's library disagrees with
 *          ECMAScript about `round`, `min` and `max` at zero and at ties), the
 *          storage width chosen by the shape rather than by the value, and
 *          `-ffp-contract=off` in CFLAGS — a fused multiply-add is more accurate
 *          than what JS computes, and more accurate is still different.
 */
import {
    CMD_DESPAWN, CMD_REMOVE, CMD_WORDS, QUERYROWS_WORDS,
    abiHash, planFor,
    type AbiLayout, type FieldOffsets, type Leaf, type SysPlan,
} from './abi';
import {
    BOOL, F64,
    type EirFn, type EirModule, type EirSystem, type EirType, type Expr, type Local,
    type MathFn, type Place, type Stmt,
} from './eir';

/**
 * Flags the generated C must be compiled with. Not advice: `-ffp-contract=off`
 * is load-bearing, and a build that omits it will disagree with the interpreter
 * in the last bit of a multiply-add and be very hard to explain.
 */
export const CFLAGS: readonly string[] = [
    '-std=c11', '-O2', '-ffp-contract=off', '-fexcess-precision=standard',
];

export interface CModule {
    /** `estella_abi.h` — the contract's C side, and the only thing the code calls. */
    readonly header: string;
    /** The translation unit: offsets, module functions, systems. */
    readonly source: string;
    /** Exported symbols, one per compiled system. */
    readonly symbols: readonly string[];
    /** The §2.5 handshake constant, also emitted into the source. */
    readonly hash: string;
}

// =============================================================================
// the runtime header — memory access, and the Math ECMAScript actually specifies
// =============================================================================

/**
 * Everything the generated code is allowed to reach. All of it is `static
 * inline`, so the object file has no undefined symbol and the wasm has no
 * import — §6.5 holds because there was never anything to import.
 */
export const RUNTIME_H = `/* GENERATED by @estella/compiler — do not edit. */
/* The Estella ABI, C side. docs/REARCH_AOT_ABI.md */
#ifndef ESTELLA_ABI_H
#define ESTELLA_ABI_H

#include <stdint.h>
#include <string.h>
#include <math.h>

/* A fused multiply-add is MORE accurate than the double rounding JS does, and
   more accurate is still a different number. GCC does not implement this pragma
   and warns about it, so the flag in CFLAGS is the one that has to be there;
   this is belt and braces for the compiler that does honour it. */
#if defined(__clang__)
#pragma STDC FP_CONTRACT OFF
#endif

/* An address in the ABI is a u32 offset into one linear memory. On wasm that
   memory starts at zero, so the offset already IS the pointer; natively the
   host owns a block and hands us its base. Same offsets either way — which is
   what lets one emitted source serve both back ends. */
#if defined(__wasm__)
#define ES_MEM ((unsigned char *)0)
#else
extern unsigned char *es_memory;
#define ES_MEM es_memory
#endif

/* memcpy, not a cast: the image is a byte block, and a u32 read through an
   aligned pointer is undefined if the host ever hands us an odd base. */
static inline uint32_t es_u32(uint32_t a) { uint32_t v; memcpy(&v, ES_MEM + a, 4); return v; }
static inline void es_set_u32(uint32_t a, uint32_t v) { memcpy(ES_MEM + a, &v, 4); }
static inline double es_f32(uint32_t a) { float v; memcpy(&v, ES_MEM + a, 4); return (double)v; }
static inline void es_set_f32(uint32_t a, double v) { float f = (float)v; memcpy(ES_MEM + a, &f, 4); }
static inline double es_f64(uint32_t a) { double v; memcpy(&v, ES_MEM + a, 8); return v; }
static inline void es_set_f64(uint32_t a, double v) { memcpy(ES_MEM + a, &v, 8); }

/* ---------------------------------------------------------------------------
   Math. Only the operations ECMAScript specifies EXACTLY are in the subset, but
   "exactly specified" is not the same as "what libm does" — three of them
   differ, and each difference is one bit of one pixel that would take a day to
   find. So each is written out rather than forwarded.
   --------------------------------------------------------------------------- */
static inline double es_abs(double x) { return fabs(x); }
static inline double es_floor(double x) { return floor(x); }
static inline double es_ceil(double x) { return ceil(x); }
static inline double es_trunc(double x) { return trunc(x); }
static inline double es_sqrt(double x) { return sqrt(x); }

/* Math.sign returns x itself for NaN and for both zeroes, so the sign of zero
   survives — and the sign of zero is a distinct bit pattern in the image. */
static inline double es_sign(double x) {
    if (isnan(x) || x == 0.0) return x;
    return x > 0.0 ? 1.0 : -1.0;
}

/* C's round() breaks ties AWAY from zero; ECMAScript breaks them toward +Inf.
   And floor(x + 0.5) — the usual fix — is wrong for the double just below 0.5,
   where the addition itself rounds up to 1. Subtracting the floor is exact for
   every finite x, so the comparison sees the true fraction. */
static inline double es_round(double x) {
    if (!isfinite(x) || x == 0.0) return x;
    double f = floor(x);
    double r = (x - f) < 0.5 ? f : f + 1.0;
    /* Math.round(-0.2) is -0, and -0 is not the same bytes as +0. */
    return (r == 0.0 && x < 0.0) ? -0.0 : r;
}

/* fmin/fmax return the non-NaN operand and are free to pick either zero;
   Math.min/max propagate NaN and distinguish -0 from +0. */
static inline double es_min(double a, double b) {
    if (isnan(a) || isnan(b)) return (double)NAN;
    if (a == b) return signbit(a) ? a : b;
    return a < b ? a : b;
}
static inline double es_max(double a, double b) {
    if (isnan(a) || isnan(b)) return (double)NAN;
    if (a == b) return signbit(a) ? b : a;
    return a > b ? a : b;
}

/* JS % on doubles is the truncated remainder, which is fmod. */
static inline double es_rem(double a, double b) { return fmod(a, b); }

#endif /* ESTELLA_ABI_H */
`;

// =============================================================================
// naming and types
// =============================================================================

/** A C identifier from an EIR name. The id keeps distinct locals distinct even
 *  after the inliner has minted two temporaries from the same parameter. */
function cName(l: Local): string {
    return `${l.name.replace(/[^A-Za-z0-9_]/g, '_')}_${l.id}`;
}

function cFn(name: string): string {
    return `es_fn_${name.replace(/[^A-Za-z0-9_]/g, '_')}`;
}

export function cSymbol(system: string): string {
    return `es_sys_${system.replace(/[^A-Za-z0-9_]/g, '_')}`;
}

function offsetMacro(owner: string, path: readonly string[]): string {
    return `ES_OFF_${owner}_${path.join('_')}`.replace(/[^A-Za-z0-9_]/g, '_');
}

function cType(t: EirType): string {
    switch (t.k) {
        case 'f64': return 'double';
        case 'bool': return 'int';
        case 'entity': return 'uint32_t';
        case 'comp': case 'res': return 'uint32_t';
        default: throw new Error(`codegen: a ${t.k} is not a C value`);
    }
}

/** Three representations, so a coercion is a lookup rather than a case tree. */
type Repr = 'double' | 'int' | 'uint32_t';

function repr(t: EirType): Repr {
    return cType(t) as Repr;
}

/** Convert `text` from one EIR type's representation to another's. */
function coerce(text: string, from: EirType, to: EirType): string {
    const a = repr(from);
    const b = repr(to);
    if (a === b) return text;
    if (b === 'double') return `((double)(${text}))`;
    if (b === 'int') return a === 'double' ? `((${text}) != 0.0)` : `((${text}) != 0u)`;
    return `((uint32_t)(${text}))`;
}

/**
 * A double literal C parses back to the same bits. Two traps: an integer-valued
 * constant printed bare makes `(5 / 3)` INTEGER division in C, and `-0`
 * stringifies as "0" in JS while being a different bit pattern in the image.
 */
function num(v: number): string {
    if (Number.isNaN(v)) return '((double)NAN)';
    if (!Number.isFinite(v)) return v > 0 ? '((double)INFINITY)' : '(-(double)INFINITY)';
    if (Object.is(v, -0)) return '(-0.0)';
    // toString gives the shortest decimal that round-trips, and strtod is
    // correctly rounded, so the bits survive the trip through the source file.
    const s = v.toString();
    return /[.eE]/.test(s) ? s : `${s}.0`;
}

const MATH_C: Record<MathFn, string> = {
    abs: 'es_abs', floor: 'es_floor', ceil: 'es_ceil', round: 'es_round',
    trunc: 'es_trunc', sqrt: 'es_sqrt', sign: 'es_sign', min: 'es_min', max: 'es_max',
};

// =============================================================================
// which locals are read — so the output has no variable the compiler warns about
// =============================================================================

function readsOf(stmts: readonly Stmt[], out: Set<number>): void {
    const place = (p: Place): void => {
        if (p.p === 'local') { out.add(p.id); return; }
        place(p.base);
    };
    const expr = (e: Expr): void => {
        switch (e.e) {
            case 'const': break;
            case 'read': place(e.place); break;
            case 'neg': case 'not': expr(e.v); break;
            case 'bin': case 'logic': expr(e.l); expr(e.r); break;
            case 'select': expr(e.cond); expr(e.then); expr(e.otherwise); break;
            case 'call': for (const a of e.args) expr(a); break;
        }
    };
    for (const s of stmts) {
        switch (s.s) {
            case 'let': case 'return': expr(s.value); break;
            // A field target READS its base to compute the address; a local
            // target does not, which is exactly the distinction that decides
            // whether a bound row local is dead.
            case 'assign':
                if (s.target.p === 'field') place(s.target.base);
                expr(s.value);
                break;
            case 'emit': place(s.channel); for (const a of s.args) expr(a); break;
            case 'if': expr(s.cond); readsOf(s.then, out); readsOf(s.otherwise, out); break;
            case 'rowLoop': place(s.query); readsOf(s.body, out); break;
        }
    }
}

/** Locals a rowLoop binds; they are declared per iteration, not per function. */
function loopBound(stmts: readonly Stmt[], out: Set<number>): void {
    for (const s of stmts) {
        if (s.s === 'rowLoop') {
            if (s.entity !== null) out.add(s.entity);
            for (const b of s.binds) out.add(b);
            loopBound(s.body, out);
        } else if (s.s === 'if') {
            loopBound(s.then, out);
            loopBound(s.otherwise, out);
        }
    }
}

function hasEmit(stmts: readonly Stmt[]): boolean {
    return stmts.some((s) => s.s === 'emit'
        || (s.s === 'rowLoop' && hasEmit(s.body))
        || (s.s === 'if' && (hasEmit(s.then) || hasEmit(s.otherwise))));
}

function zeroOf(t: EirType): string {
    switch (repr(t)) {
        case 'double': return '0.0';
        case 'int': return '0';
        default: return '0u';
    }
}

// =============================================================================
// the emitter
// =============================================================================

class Emitter {
    private readonly lines: string[] = [];
    private readonly byId = new Map<number, Local>();
    private readonly owners = new Map<number, string>();
    private depth = 0;

    constructor(
        private readonly layout: AbiLayout,
        /** Offset macros this translation unit turned out to need. */
        private readonly offsets: Map<string, number>,
        private readonly plan: SysPlan | null,
    ) {}

    get text(): string { return this.lines.join('\n'); }

    private bind(locals: readonly Local[]): void {
        for (const l of locals) {
            this.byId.set(l.id, l);
            if (l.type.k === 'comp' || l.type.k === 'res') this.owners.set(l.id, l.type.name);
        }
    }

    private line(indent: number, text: string): void {
        this.lines.push(`${'    '.repeat(indent)}${text}`);
    }

    private local(id: number): Local {
        const l = this.byId.get(id);
        if (!l) throw new Error(`codegen: local %${id} is used but never declared`);
        return l;
    }

    /** `base + ES_OFF_Comp_field` — one add against a constant, which is the point. */
    private address(base: Place, path: readonly string[]): { addr: string; leaf: Leaf } {
        if (base.p !== 'local') throw new Error('codegen: a field base must be a local');
        const owner = this.owners.get(base.id);
        if (!owner) throw new Error(`codegen: local %${base.id} owns no fields`);
        const shape: FieldOffsets | undefined =
            this.layout.comps.get(owner) ?? this.layout.resources.get(owner);
        const leaf = shape?.leaves.get(path.join('.'));
        if (!leaf) throw new Error(`codegen: '${owner}' has no field '${path.join('.')}'`);
        const macro = offsetMacro(owner, path);
        this.offsets.set(macro, leaf.byteOffset);
        return { addr: `${cName(this.local(base.id))} + ${macro}`, leaf };
    }

    /** Read a place; the result's C type is `cType(type)`. */
    private read(p: Place, type: EirType): string {
        if (p.p === 'local') return cName(this.local(p.id));
        const { addr, leaf } = this.address(p.base, p.path);
        const load = leaf.bits === 64 ? `es_f64(${addr})` : `es_f32(${addr})`;
        return coerce(load, F64, type);
    }

    /** An expression, parenthesised so composition never needs precedence rules. */
    expr(e: Expr): string {
        switch (e.e) {
            case 'const':
                return typeof e.value === 'boolean' ? (e.value ? '1' : '0') : num(e.value);
            case 'read':
                return this.read(e.place, e.type);
            case 'neg':
                return `(-${coerce(this.expr(e.v), e.v.type, F64)})`;
            case 'not':
                return `(!${coerce(this.expr(e.v), e.v.type, BOOL)})`;
            case 'logic':
                return `(${coerce(this.expr(e.l), e.l.type, BOOL)} ${e.op} `
                    + `${coerce(this.expr(e.r), e.r.type, BOOL)})`;
            case 'select':
                return `(${coerce(this.expr(e.cond), e.cond.type, BOOL)} ? `
                    + `${coerce(this.expr(e.then), e.then.type, e.type)} : `
                    + `${coerce(this.expr(e.otherwise), e.otherwise.type, e.type)})`;
            case 'bin': {
                const l = coerce(this.expr(e.l), e.l.type, F64);
                const r = coerce(this.expr(e.r), e.r.type, F64);
                // `%` is a call because C's % is integer-only; JS's is fmod.
                if (e.op === '%') return `es_rem(${l}, ${r})`;
                return `(${l} ${e.op} ${r})`;
            }
            case 'call': {
                const args = e.args.map((a) => coerce(this.expr(a), a.type, F64));
                if (e.target.k === 'math') return `${MATH_C[e.target.fn]}(${args.join(', ')})`;
                return `${cFn(e.target.name)}(${args.join(', ')})`;
            }
        }
    }

    stmts(list: readonly Stmt[], indent: number): void {
        for (const s of list) this.stmt(s, indent);
    }

    private stmt(s: Stmt, indent: number): void {
        switch (s.s) {
            case 'let': {
                const l = this.local(s.id);
                this.line(indent, `${cName(l)} = ${coerce(this.expr(s.value), s.value.type, l.type)};`);
                break;
            }
            case 'return':
                this.line(indent, `return ${this.expr(s.value)};`);
                break;
            case 'assign': {
                if (s.target.p === 'local') {
                    const l = this.local(s.target.id);
                    this.line(indent, `${cName(l)} = ${coerce(this.expr(s.value), s.value.type, l.type)};`);
                    break;
                }
                const { addr, leaf } = this.address(s.target.base, s.target.path);
                const store = leaf.bits === 64 ? 'es_set_f64' : 'es_set_f32';
                this.line(indent, `${store}(${addr}, ${coerce(this.expr(s.value), s.value.type, F64)});`);
                break;
            }
            case 'if': {
                this.line(indent, `if (${coerce(this.expr(s.cond), s.cond.type, BOOL)}) {`);
                this.stmts(s.then, indent + 1);
                if (s.otherwise.length > 0) {
                    this.line(indent, '} else {');
                    this.stmts(s.otherwise, indent + 1);
                }
                this.line(indent, '}');
                break;
            }
            case 'emit':
                this.emitCommand(s, indent);
                break;
            case 'rowLoop':
                this.rowLoop(s, indent);
                break;
        }
    }

    /**
     * A command is four words written into the host's buffer and a counter
     * bumped — no call, and nothing read back. The `cap` guard is the
     * contract's: §3 forbids writing past it, and the host is what sized it.
     */
    private emitCommand(s: Stmt & { s: 'emit' }, indent: number): void {
        const kind = s.record === 'despawn' ? CMD_DESPAWN : CMD_REMOVE;
        this.line(indent, 'if (es_cmd_n < es_cmd_cap) {');
        this.line(indent + 1, `const uint32_t es_at = es_cmd_buf + es_cmd_n * ${CMD_WORDS * 4}u;`);
        this.line(indent + 1, `es_set_u32(es_at, ${kind}u); /* ${s.record} */`);
        for (let i = 1; i < CMD_WORDS; i++) {
            const a = s.args[i - 1];
            const v = a ? coerce(this.expr(a), a.type, { k: 'entity' }) : '0u';
            this.line(indent + 1, `es_set_u32(es_at + ${i * 4}u, ${v});`);
        }
        this.line(indent + 1, 'es_cmd_n += 1u;');
        this.line(indent, '}');
    }

    /**
     * The op EIR exists to keep (§4.2): a strided walk of a packed row array.
     * One `es_u32` per component per row and no lookup — the host already did
     * the lookup once, in C++, which is where it is cheap.
     */
    private rowLoop(s: Stmt & { s: 'rowLoop' }, indent: number): void {
        if (s.query.p !== 'local') throw new Error('codegen: a rowLoop walks a query local');
        const slot = this.plan?.slots.get(s.query.id);
        if (!slot || slot.table !== 'query') throw new Error('codegen: that local is not a declared query');
        const q = this.plan!.queries[slot.slot]!;
        const d = this.depth++;
        const stride = 1 + q.length;
        const at = slot.slot * QUERYROWS_WORDS * 4;
        const reads = new Set<number>();
        readsOf(s.body, reads);
        this.line(indent, '{');
        this.line(indent + 1, `const uint32_t es_rows${d} = es_u32(es_queries + ${at}u);`);
        this.line(indent + 1, `const uint32_t es_n${d} = es_u32(es_queries + ${at + 4}u);`);
        this.line(indent + 1, `for (uint32_t es_i${d} = 0u; es_i${d} < es_n${d}; ++es_i${d}) {`);
        this.line(indent + 2, `const uint32_t es_row${d} = es_rows${d} + es_i${d} * ${stride * 4}u;`);
        if (s.entity !== null && reads.has(s.entity)) {
            this.line(indent + 2, `const uint32_t ${cName(this.local(s.entity))} = es_u32(es_row${d});`);
        }
        s.binds.forEach((id, i) => {
            // A bound component nobody reads is not loaded. The row is still
            // strided past it, because the row's shape is the query's, not the
            // body's — dropping the load is free, dropping the column is not.
            if (!reads.has(id)) return;
            this.line(indent + 2,
                `const uint32_t ${cName(this.local(id))} = es_u32(es_row${d} + ${(i + 1) * 4}u);`);
        });
        this.stmts(s.body, indent + 2);
        this.line(indent + 1, '}');
        this.line(indent, '}');
        this.depth--;
    }

    /** A module-level pure function: numbers in, one number out, no world. */
    fn(f: EirFn): void {
        this.bind([...f.params, ...f.locals]);
        const params = f.params.map((p) => `${cType(p.type)} ${cName(p)}`).join(', ');
        this.line(0, `static ${cType(f.ret)} ${cFn(f.name)}(${params || 'void'}) {`);
        this.declare(f.locals, null, 1);
        this.stmts(f.body, 1);
        this.line(0, '}');
        this.line(0, '');
    }

    /** `void es_sys_<Name>(uint32_t ctx)` — §2.1's one exported symbol. */
    system(sys: EirSystem): void {
        const plan = this.plan!;
        this.bind([...sys.params, ...sys.locals]);
        const reads = new Set<number>();
        readsOf(sys.body, reads);
        const bound = new Set<number>();
        loopBound(sys.body, bound);

        this.line(0, `void ${cSymbol(sys.name)}(uint32_t es_ctx) {`);
        if (plan.queries.length > 0) this.line(1, 'const uint32_t es_queries = es_u32(es_ctx);');
        const usesRes = sys.params.some((p) => plan.slots.get(p.id)!.table === 'res' && reads.has(p.id));
        if (usesRes) this.line(1, 'const uint32_t es_resources = es_u32(es_ctx + 4u);');
        const emits = hasEmit(sys.body);
        if (emits) {
            this.line(1, 'const uint32_t es_cmd_buf = es_u32(es_ctx + 8u);');
            this.line(1, 'const uint32_t es_cmd_cap = es_u32(es_ctx + 12u);');
            this.line(1, 'const uint32_t es_cmd_at = es_u32(es_ctx + 16u);');
            this.line(1, 'uint32_t es_cmd_n = es_u32(es_cmd_at);');
        }
        // A resource base is one indirection, resolved once at entry rather than
        // per row: the host already put the address in the table.
        for (const p of sys.params) {
            const slot = plan.slots.get(p.id)!;
            if (slot.table !== 'res' || !reads.has(p.id)) continue;
            this.line(1, `const uint32_t ${cName(p)} = es_u32(es_resources + ${slot.slot * 4}u);`);
        }
        this.declare(sys.locals.filter((l) => !bound.has(l.id)), reads, 1);
        this.stmts(sys.body, 1);
        if (emits) this.line(1, 'es_set_u32(es_cmd_at, es_cmd_n);');
        this.line(0, '}');
        this.line(0, '');
    }

    /**
     * Function-scope locals. A declared local nobody reads would draw a warning,
     * and a warning in generated code is a warning nobody will ever read — so it
     * is spelled `(void)` here rather than silenced at the compiler.
     */
    private declare(locals: readonly Local[], reads: ReadonlySet<number> | null, indent: number): void {
        for (const l of locals) {
            this.line(indent, `${cType(l.type)} ${cName(l)} = ${zeroOf(l.type)};`);
            if (reads && !reads.has(l.id)) this.line(indent, `(void)${cName(l)};`);
        }
    }
}

// =============================================================================
// the module
// =============================================================================

/**
 * Emit C for the given systems. The caller decides which — `verifySystem` has to
 * have passed first, because this lowering is total over VALID EIR and its
 * reaction to invalid EIR is to throw, which is the right reaction to a compiler
 * bug and the wrong one to a source file outside the subset.
 */
export function emitC(module: EirModule, layout: AbiLayout, systems: readonly EirSystem[]): CModule {
    const offsets = new Map<string, number>();
    const plans = systems.map((s) => planFor(s));
    const bodies: string[] = [];

    // Module functions first: a system may call one, and C wants it declared
    // before the call. Only the ones still reachable after the inliner ran are
    // emitted, because an unreferenced static would warn.
    for (const name of calledFns(module, systems)) {
        const e = new Emitter(layout, offsets, null);
        e.fn(module.fns.get(name)!);
        bodies.push(e.text);
    }
    systems.forEach((sys, i) => {
        const e = new Emitter(layout, offsets, plans[i]!);
        e.system(sys);
        bodies.push(e.text);
    });

    const hash = abiHash(layout, plans);
    const macros = [...offsets].sort(([a], [b]) => (a < b ? -1 : 1)).map(([k, v]) => `#define ${k} ${v}u`);
    const source = [
        '/* GENERATED by @estella/compiler — do not edit. */',
        '/* docs/REARCH_AOT_ABI.md: this file calls the engine zero times. */',
        '#include "estella_abi.h"',
        '',
        '/* §2.5: the loader compares this before it maps anything. A mismatch is',
        '   not a wrong answer, it is a read of a different field. */',
        `const uint64_t es_abi_hash = 0x${hash}ULL;`,
        '',
        '/* Component and resource field offsets, from EHT. */',
        ...macros,
        '',
        ...bodies,
    ].join('\n');

    return { header: RUNTIME_H, source, symbols: systems.map((s) => cSymbol(s.name)), hash };
}

/** Module functions still called after the inliner ran, in declaration order. */
function calledFns(module: EirModule, systems: readonly EirSystem[]): string[] {
    const want = new Set<string>();
    const visitExpr = (e: Expr): void => {
        switch (e.e) {
            case 'call':
                if (e.target.k === 'fn' && !want.has(e.target.name)) {
                    want.add(e.target.name);
                    const def = module.fns.get(e.target.name);
                    if (def) visit(def.body);
                }
                for (const a of e.args) visitExpr(a);
                break;
            case 'bin': case 'logic': visitExpr(e.l); visitExpr(e.r); break;
            case 'neg': case 'not': visitExpr(e.v); break;
            case 'select': visitExpr(e.cond); visitExpr(e.then); visitExpr(e.otherwise); break;
            default: break;
        }
    };
    const visit = (stmts: readonly Stmt[]): void => {
        for (const s of stmts) {
            switch (s.s) {
                case 'let': case 'return': case 'assign': visitExpr(s.value); break;
                case 'emit': for (const a of s.args) visitExpr(a); break;
                case 'if': visitExpr(s.cond); visit(s.then); visit(s.otherwise); break;
                case 'rowLoop': visit(s.body); break;
            }
        }
    };
    for (const sys of systems) visit(sys.body);
    // Declaration order, so a helper that calls a helper is defined first.
    return [...module.fns.keys()].filter((n) => want.has(n));
}
