// SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0
// SPDX-FileCopyrightText: Copyright (c) 2024-present ESEngine Team
/**
 * @file  Game export (REARCH_EDITOR_REALM Phase S / REARCH_EXPORT). Produces a
 *        self-contained build of the open project, parameterized by platform:
 *
 *          web     → a static-servable web build (cooked assets + manifest, the
 *                    esbuild'd game host, the SDK + wasm runtime, index.html).
 *          desktop → the SAME web build under `app/`, wrapped in a runnable
 *                    Electron app (main.cjs serving it over a custom `game://`
 *                    scheme — file:// blocks the runtime's asset/wasm fetches),
 *                    plus a package.json wired for `electron-builder`.
 *
 *        The web payload is identical across targets and boots the SAME runtime
 *        the editor's play realm uses (gameHost → initPlayRealmRuntime), so the
 *        shipped game is what was played (play == ship). The host is origin-
 *        agnostic (relative fetch + import.meta.url), so the desktop scheme needs
 *        no host changes.
 *
 *        Pure Node (esbuild + fs) — IPC wiring is in main.ts.
 */
import { build, type BuildOptions } from 'esbuild';
import { writeFile, mkdir, cp } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { cookAssets } from './cookAssets';
import { IMPORT_MAP_JSON, IMPORT_MAP_CSP_HASH } from './buildPlayRealm';
import { exportWeChat } from './exportWeChat';
import { exportPlayable } from './exportPlayable';
import type { OnExportProgress } from './exportProgress';
import { ESENGINE_EXTERNAL } from './esengineResolve';

export type ExportPlatform = 'web' | 'desktop' | 'wechat' | 'playable';

export interface ExportGameResult {
  ok: boolean;
  platform: ExportPlatform;
  outDir: string;
  /** Count of assets included (reachable from the entry scene). */
  included: number;
  warnings: string[];
  errors: string[];
}

function indexHtml(title: string): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      http-equiv="Content-Security-Policy"
      content="default-src 'self'; script-src 'self' 'unsafe-eval' blob: '${IMPORT_MAP_CSP_HASH}'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self' data: blob:; worker-src 'self' blob:;"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
    <title>${title}</title>
    <script type="importmap">${IMPORT_MAP_JSON}</script>
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      html, body { width: 100%; height: 100%; overflow: hidden; background: #0e121b; }
      #canvas { display: block; width: 100%; height: 100%; touch-action: none; }
    </style>
  </head>
  <body>
    <canvas id="canvas"></canvas>
    <script type="module" src="./game.js"></script>
  </body>
</html>
`;
}

/** A filesystem-safe slug for the app id / package name. */
function slugify(title: string): string {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'game';
}

/** The Electron main process for an exported desktop game: serve the bundled web
 *  payload (./app) over a stable, fetch-enabled `game://` scheme and show it in a
 *  window. Mirrors the editor's estella:// scheme (file:// blocks fetch of sibling
 *  assets + wasm streaming, which the runtime needs). */
function desktopMain(title: string): string {
  return `'use strict';
// Generated by Estella exportGame — the desktop shell for this game.
const { app, protocol, BrowserWindow, net } = require('electron');
const path = require('node:path');
const { pathToFileURL } = require('node:url');

const SCHEME = 'game';
const ROOT = path.join(__dirname, 'app');
const MIME = {
  html: 'text/html', js: 'text/javascript', mjs: 'text/javascript', css: 'text/css',
  json: 'application/json', wasm: 'application/wasm', map: 'application/json',
  png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', webp: 'image/webp',
  svg: 'image/svg+xml', ktx2: 'image/ktx2',
  ogg: 'audio/ogg', mp3: 'audio/mpeg', wav: 'audio/wav', m4a: 'audio/mp4', aac: 'audio/aac',
  fnt: 'text/plain', ttf: 'font/ttf', woff: 'font/woff', woff2: 'font/woff2',
};

// Emscripten/embind glue JIT-compiles call bridges (new Function) → needs unsafe-eval.
process.env['ELECTRON_DISABLE_SECURITY_WARNINGS'] = 'true';

protocol.registerSchemesAsPrivileged([
  { scheme: SCHEME, privileges: { standard: true, secure: true, supportFetchAPI: true, corsEnabled: true, stream: true } },
]);

function createWindow() {
  const win = new BrowserWindow({
    width: 1280,
    height: 720,
    backgroundColor: '#0e121b',
    title: ${JSON.stringify(title)},
    webPreferences: { contextIsolation: true, sandbox: true },
  });
  win.removeMenu();
  win.loadURL(SCHEME + '://app/index.html');
}

app.whenReady().then(() => {
  protocol.handle(SCHEME, async (req) => {
    let rel = decodeURIComponent(new URL(req.url).pathname).replace(/^\\/+/, '') || 'index.html';
    const filePath = path.join(ROOT, rel);
    // Contain within ROOT (no path traversal out of the bundled payload).
    if (filePath !== ROOT && !filePath.startsWith(ROOT + path.sep)) {
      return new Response('forbidden', { status: 403 });
    }
    try {
      const res = await net.fetch(pathToFileURL(filePath).toString());
      const ext = path.extname(filePath).slice(1).toLowerCase();
      const headers = new Headers(res.headers);
      headers.set('content-type', MIME[ext] || 'application/octet-stream');
      return new Response(res.body, { status: res.status, headers });
    } catch {
      return new Response('not found', { status: 404 });
    }
  });
  createWindow();
  app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) createWindow(); });
});

app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
`;
}

function desktopPackageJson(title: string, appId?: string, productName?: string): string {
  const slug = slugify(productName || title);
  return JSON.stringify({
    name: slug,
    version: '1.0.0',
    private: true,
    main: 'main.cjs',
    scripts: { start: 'electron .', dist: 'electron-builder' },
    devDependencies: { electron: '^42.0.0', 'electron-builder': '^25.0.0' },
    build: {
      appId: appId || `com.estella.${slug}`,
      productName: productName || title,
      files: ['main.cjs', 'app/**/*'],
      directories: { output: 'installer' },
      mac: { target: 'dmg' },
      win: { target: 'nsis' },
      linux: { target: 'AppImage' },
    },
  }, null, 2) + '\n';
}

function desktopReadme(title: string): string {
  return `# ${title}

A desktop build exported from Estella. The game (\`app/\`) is the same play==ship
runtime served over a \`game://\` scheme by the Electron shell (\`main.cjs\`).

## Run it

    npm install
    npm start

## Package a native installer (.dmg / .exe / AppImage)

    npm install
    npm run dist

The installer is written to \`installer/\`. Build each OS's installer on that OS
(electron-builder doesn't cross-compile reliably).
`;
}

/** Stage the Electron shell around the web payload already built under `<absOut>/app`. */
async function stageDesktopApp(absOut: string, title: string, appId?: string, productName?: string): Promise<void> {
  const display = productName || title;
  await writeFile(path.join(absOut, 'main.cjs'), desktopMain(display));
  await writeFile(path.join(absOut, 'package.json'), desktopPackageJson(title, appId, productName));
  await writeFile(path.join(absOut, 'README.md'), desktopReadme(display));
}

/**
 * Export the open project. `entryScene` is the project-relative scene to boot;
 * `gameHostEntry` the gameHost.ts source; `wasmDir` the engine runtime to copy.
 * `platform` selects the target (default web).
 */
export async function exportGame(opts: {
  root: string;
  entryScene: string;
  gameHostEntry: string;
  /** Project-relative startup entry (e.g. src/main.ts) → bundled to scripts.mjs. */
  scriptsEntry?: string;
  sdkDistDir: string;
  wasmDir: string;
  outDir: string;
  title?: string;
  platform?: ExportPlatform;
  /** Playable host source (src/playableHost.ts). */
  playableHostEntry?: string;
  /** Desktop installer id (Project Settings → Packaging → Desktop); default com.estella.<slug>. */
  desktopAppId?: string;
  /** Desktop product/display name (Project Settings); default the project title. */
  desktopProductName?: string;
  /** WeChat appid / orientation (Project Settings → Packaging → WeChat). */
  wechatAppid?: string;
  wechatOrientation?: 'portrait' | 'landscape';
  /** Per-phase progress (build log). */
  onProgress?: OnExportProgress;
  /** Shipping config: minify the bundles, no sourcemap. Default off (dev). */
  minify?: boolean;
  sourcemap?: boolean;
}): Promise<ExportGameResult> {
  const platform = opts.platform ?? 'web';
  const title = opts.title ?? 'Game';
  const progress = opts.onProgress ?? (() => {});

  // WeChat has no import maps + a different module/asset model → its own pipeline.
  if (platform === 'wechat') {
    return exportWeChat({
      root: opts.root,
      entryScene: opts.entryScene,
      scriptsEntry: opts.scriptsEntry,
      sdkDir: opts.sdkDistDir,
      wasmDir: opts.wasmDir,
      outDir: opts.outDir,
      title,
      appid: opts.wechatAppid,
      orientation: opts.wechatOrientation,
      minify: opts.minify,
      onProgress: opts.onProgress,
    });
  }

  // Playable ads are a single inlined HTML (SINGLE_FILE glue + base64 assets).
  if (platform === 'playable') {
    return exportPlayable({
      root: opts.root,
      entryScene: opts.entryScene,
      scriptsEntry: opts.scriptsEntry,
      playableHostEntry: opts.playableHostEntry ?? path.join(path.dirname(opts.gameHostEntry), 'playableHost.ts'),
      sdkDir: opts.sdkDistDir,
      wasmDir: opts.wasmDir,
      outDir: opts.outDir,
      title,
      minify: opts.minify,
      onProgress: opts.onProgress,
    });
  }

  const absOut = path.isAbsolute(opts.outDir) ? opts.outDir : path.join(opts.root, opts.outDir);
  // Desktop nests the web build under app/; the Electron shell sits beside it.
  const payloadDir = platform === 'desktop' ? path.join(absOut, 'app') : absOut;
  const warnings: string[] = [];
  const errors: string[] = [];
  await mkdir(payloadDir, { recursive: true });
  const common: BuildOptions = {
    bundle: true,
    format: 'esm',
    platform: 'browser',
    target: 'es2020',
    external: ESENGINE_EXTERNAL,
    minify: opts.minify ?? false,
    sourcemap: opts.sourcemap ?? false,
    write: true,
    logLevel: 'silent',
  };

  // 1. Cook reachable assets + manifest (the entry scene file is staged too).
  progress({ phase: 'Cooking assets' });
  const cook = await cookAssets(opts.root, { entryScenes: [opts.entryScene], outDir: payloadDir });
  warnings.push(...cook.warnings);
  progress({ phase: 'Cooking assets', detail: `${cook.included.length} reachable` });

  try {
    // 2. Game host — esengine EXTERNAL (resolved by the index.html import map),
    //    so the shipped game shares one SDK with the project bundle and runs
    //    custom systems (same shape as the play realm).
    progress({ phase: 'Bundling game host' });
    const host = await build({ ...common, entryPoints: [opts.gameHostEntry], outfile: path.join(payloadDir, 'game.js') });
    errors.push(...host.errors.map((e) => e.text));
    // 3. Project bundle (defineComponent/defineSystem) → scripts.mjs, esengine external.
    const scriptsAbs = opts.scriptsEntry ? path.join(opts.root, opts.scriptsEntry) : null;
    if (scriptsAbs && existsSync(scriptsAbs)) {
      progress({ phase: 'Bundling project scripts' });
      const proj = await build({ ...common, entryPoints: [scriptsAbs], outfile: path.join(payloadDir, 'scripts.mjs') });
      errors.push(...proj.errors.map((e) => e.text));
    }
  } catch (err) {
    const e = err as { errors?: { text: string }[]; message?: string };
    errors.push(...(e.errors?.map((x) => x.text) ?? [String(e.message ?? err)]));
    return { ok: false, platform, outDir: absOut, included: cook.included.length, warnings, errors };
  }

  // 4. SDK (import-map target) + wasm runtime.
  progress({ phase: 'Copying SDK + runtime' });
  if (existsSync(opts.sdkDistDir)) await cp(opts.sdkDistDir, path.join(payloadDir, 'sdk'), { recursive: true });
  else warnings.push(`sdk dist not found: ${opts.sdkDistDir}`);
  if (existsSync(opts.wasmDir)) await cp(opts.wasmDir, path.join(payloadDir, 'wasm'), { recursive: true });
  else warnings.push(`wasm runtime dir not found: ${opts.wasmDir}`);

  // 5. Host page + entry-scene config.
  progress({ phase: 'Writing host page' });
  await writeFile(path.join(payloadDir, 'index.html'), indexHtml(title));
  await writeFile(
    path.join(payloadDir, 'game.config.json'),
    JSON.stringify({ entryScene: opts.entryScene }, null, 2) + '\n',
  );

  // 6. Desktop: wrap the payload in a runnable Electron app.
  if (platform === 'desktop') { progress({ phase: 'Staging Electron app' }); await stageDesktopApp(absOut, title, opts.desktopAppId, opts.desktopProductName); }

  return { ok: errors.length === 0, platform, outDir: absOut, included: cook.included.length, warnings, errors };
}
