// SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0
// SPDX-FileCopyrightText: Copyright (c) 2024-present ESEngine Team
/**
 * @file  WeChat MiniGame export (REARCH_EXPORT E2). Assembles a project into the
 *        exact shape the SHIPPED runtime `initWeChatRuntime` consumes — it's
 *        correct-by-construction against that contract (this sandbox has no WeChat
 *        devtools, so runtime correctness is validated by the user in devtools):
 *
 *          asset-manifest.json  AddressableManifest (groups.<g>.assets[uuid] = {path,…});
 *                               the WeChat path resolver keys by uuid → path.
 *          scenes/<name>.json   the entry scene with @uuid: refs STRIPPED to bare
 *                               uuids (the resolver looks up bare uuids, not @uuid:).
 *          game-bundle.js       esbuild CJS of [wechat SDK (esengine aliased to the
 *                               wechat build) + project scripts + a boot()] — one
 *                               esengine instance so custom components/systems run.
 *          game.js              the MiniGame entry: require the wasm factory + boot.
 *          wasm/                the -t wechat engine runtime (WXWebAssembly glue).
 *          game.json / project.config.json   MiniGame config.
 *
 *        Unlike web/desktop (which share the import-map web payload), WeChat has no
 *        import maps and a different module/asset model, so this is its own path.
 *        Pure Node (esbuild + fs) — IPC wiring is in main.ts.
 */
import { build } from 'esbuild';
import { writeFile, mkdir, cp, readFile, stat, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { cookAssets } from './cookAssets';
import type { OnExportProgress } from './exportProgress';

export interface ExportWeChatResult {
  ok: boolean;
  platform: 'wechat';
  outDir: string;
  included: number;
  warnings: string[];
  errors: string[];
}

interface CookManifest {
  entries: { uuid: string; path: string; type: string }[];
}

// Editor asset type → AddressableAssetType (sdk/src/assetTypes.ts). The WeChat
// path resolver ignores type (keys by uuid → path); this only feeds the Catalog,
// so an unmapped type degrading to 'binary' is harmless.
const ADDRESSABLE_TYPE: Record<string, string> = {
  texture: 'texture', material: 'material', audio: 'audio', 'bitmap-font': 'bitmap-font',
  prefab: 'prefab', 'spine-atlas': 'spine', 'spine-skeleton': 'spine',
  scene: 'json', 'anim-clip': 'json', tilemap: 'json', timeline: 'json', json: 'json', shader: 'text',
};
const addrType = (editorType: string): string => ADDRESSABLE_TYPE[editorType] ?? 'binary';

const UUID_PREFIX = '@uuid:';

/** Strip @uuid: asset refs to the bare (lowercased) uuid the WeChat resolver keys
 *  by. Deep, value-only — any string starting with @uuid: is a ref. */
function stripUuidRefs(v: unknown): unknown {
  if (typeof v === 'string') return v.startsWith(UUID_PREFIX) ? v.slice(UUID_PREFIX.length).toLowerCase() : v;
  if (Array.isArray(v)) return v.map(stripUuidRefs);
  if (v && typeof v === 'object') {
    const o: Record<string, unknown> = {};
    for (const k of Object.keys(v as Record<string, unknown>)) o[k] = stripUuidRefs((v as Record<string, unknown>)[k]);
    return o;
  }
  return v;
}

function gameJson(): string {
  return JSON.stringify({ deviceOrientation: 'portrait', showStatusBar: false }, null, 2) + '\n';
}

function projectConfigJson(title: string): string {
  return JSON.stringify({
    miniprogramRoot: './',
    projectname: title,
    appid: '', // fill in your WeChat MiniGame appid in devtools
    setting: { es6: false, minified: false },
    compileType: 'game',
  }, null, 2) + '\n';
}

/** The MiniGame entry WeChat runs: hand the wasm factory to the bundle's boot(). */
function gameEntryJs(): string {
  return `'use strict';
// Generated by Estella exportGame (WeChat MiniGame entry).
const factory = require('./wasm/esengine.js');
const bundle = require('./game-bundle.js');
bundle.boot(typeof factory === 'function' ? factory : (factory && factory.default) || factory);
`;
}

/** Read the web cook's flat manifest → AddressableManifest the WeChat runtime reads. */
async function buildAddressableManifest(absOut: string): Promise<string> {
  const cook = JSON.parse(await readFile(path.join(absOut, 'assets.manifest.json'), 'utf8')) as CookManifest;
  const assets: Record<string, { path: string; type: string; size: number; labels: string[] }> = {};
  for (const e of cook.entries) {
    let size = 0;
    try { size = (await stat(path.join(absOut, e.path))).size; } catch { /* missing file → 0 */ }
    assets[e.uuid.toLowerCase()] = { path: e.path, type: addrType(e.type), size, labels: [] };
  }
  return JSON.stringify({ version: '2.0', groups: { main: { bundleMode: 'local', labels: [], assets } } }, null, 2) + '\n';
}

/**
 * Export the open project as a WeChat MiniGame into `outDir`. `wechatSdkEntry` is
 * the built wechat SDK (dist/index.wechat.js) the bundle aliases `esengine` to;
 * `wasmDir` the -t wechat engine runtime to copy.
 */
export async function exportWeChat(opts: {
  root: string;
  entryScene: string;
  scriptsEntry?: string;
  wechatSdkEntry: string;
  wasmDir: string;
  outDir: string;
  title?: string;
  minify?: boolean;
  onProgress?: OnExportProgress;
}): Promise<ExportWeChatResult> {
  const title = opts.title ?? 'Game';
  const absOut = path.isAbsolute(opts.outDir) ? opts.outDir : path.join(opts.root, opts.outDir);
  const progress = opts.onProgress ?? (() => {});
  const warnings: string[] = [];
  const errors: string[] = [];
  await mkdir(absOut, { recursive: true });

  // 1. Cook reachable assets (paths preserved) + the flat manifest.
  progress({ phase: 'Cooking assets' });
  const cook = await cookAssets(opts.root, { entryScenes: [opts.entryScene], outDir: absOut });
  warnings.push(...cook.warnings);

  // 2. Flat manifest → AddressableManifest (asset-manifest.json); drop the web one.
  progress({ phase: 'Building manifest' });
  try {
    await writeFile(path.join(absOut, 'asset-manifest.json'), await buildAddressableManifest(absOut));
    await rm(path.join(absOut, 'assets.manifest.json'), { force: true });
  } catch (err) {
    errors.push(`manifest: ${err instanceof Error ? err.message : String(err)}`);
  }

  // 3. Entry scene → scenes/<name>.json with @uuid: refs stripped to bare uuids.
  progress({ phase: 'Transforming scene' });
  const sceneName = path.basename(opts.entryScene).replace(/\.[^.]+$/, '');
  try {
    const raw = JSON.parse(await readFile(path.join(absOut, opts.entryScene), 'utf8'));
    await mkdir(path.join(absOut, 'scenes'), { recursive: true });
    await writeFile(path.join(absOut, 'scenes', `${sceneName}.json`), JSON.stringify(stripUuidRefs(raw)) + '\n');
  } catch (err) {
    errors.push(`scene transform: ${err instanceof Error ? err.message : String(err)}`);
  }

  // 4. game-bundle.js — wechat SDK (esengine aliased) + project scripts + boot(),
  //    one esengine instance so the project's defineComponent/defineSystem run.
  const scriptsAbs = opts.scriptsEntry ? path.join(opts.root, opts.scriptsEntry) : null;
  const entrySrc =
    `import { initWeChatRuntime } from 'esengine';\n` +
    (scriptsAbs && existsSync(scriptsAbs) ? `import ${JSON.stringify(scriptsAbs)};\n` : '') +
    `export function boot(engineFactory) {\n` +
    `  return initWeChatRuntime({ engineFactory, sceneNames: ${JSON.stringify([sceneName])}, firstScene: ${JSON.stringify(sceneName)} });\n` +
    `}\n`;
  progress({ phase: 'Bundling game' });
  try {
    const res = await build({
      stdin: { contents: entrySrc, resolveDir: opts.root, loader: 'js', sourcefile: 'wechat-entry.js' },
      bundle: true,
      format: 'cjs',
      platform: 'browser',
      target: 'es2020',
      alias: { esengine: opts.wechatSdkEntry },
      minify: opts.minify ?? false,
      sourcemap: false,
      outfile: path.join(absOut, 'game-bundle.js'),
      logLevel: 'silent',
      write: true,
    });
    errors.push(...res.errors.map((e) => e.text));
  } catch (err) {
    const e = err as { errors?: { text: string }[]; message?: string };
    errors.push(...(e.errors?.map((x) => x.text) ?? [String(e.message ?? err)]));
  }

  // 5. Entry + config.
  await writeFile(path.join(absOut, 'game.js'), gameEntryJs());
  await writeFile(path.join(absOut, 'game.json'), gameJson());
  await writeFile(path.join(absOut, 'project.config.json'), projectConfigJson(title));

  // 6. The -t wechat engine runtime (WXWebAssembly glue + binary + side modules).
  progress({ phase: 'Copying runtime' });
  if (existsSync(opts.wasmDir)) await cp(opts.wasmDir, path.join(absOut, 'wasm'), { recursive: true });
  else warnings.push(`wechat wasm runtime dir not found: ${opts.wasmDir}`);

  return { ok: errors.length === 0, platform: 'wechat', outDir: absOut, included: cook.included.length, warnings, errors };
}
