// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (c) 2024-present ESEngine Team
/**
 * @file  pluginPackage.ts — a plugin as one file you can hand to someone.
 *
 * `.esplugin` is a ZIP, written through the repo's own zip module (the same one
 * that writes runtime templates and playable bundles) rather than a second
 * implementation. Renaming one to `.zip` opens it in any tool, which is the point:
 * a package format nobody but us can read is a format nobody audits.
 *
 * IMPORT IS THE DANGEROUS DIRECTION. A `.esplugin` is a file someone was handed,
 * so the order here is deliberate and the whole design:
 *
 *   1. INSPECT from the central directory alone — nothing is inflated, nothing is
 *      written. That is what lets the UI show what is inside before the user
 *      commits, and what makes the size check meaningful (a small archive that
 *      claims to expand to gigabytes is refused before it can).
 *   2. EXTRACT only after they say yes. `extractZip` verifies every CRC and rejects
 *      `../` names, so a corrupt or hostile archive fails instead of landing.
 *   3. LAND UNTRUSTED. Installing is not approving. The plugin appears in the panel
 *      needing trust, exactly as a folder someone copied in by hand would — the one
 *      thing an import must never do is decide the trust question for the user.
 */
import { existsSync } from 'node:fs';
import { readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import path from 'node:path';
import { makeZip, zipTree, listZip, readZip, extractZip } from '../../build-tools/utils/zip.js';
import { validateManifest, resolveLocalized, type PluginManifest } from '../src/plugins/manifest';
import { PLUGIN_TYPES_DIR } from '../../pipeline/src/project/pluginPaths';

/** The extension, spelled once. */
export const PLUGIN_PACKAGE_EXT = 'esplugin';

/**
 * Never packed. `node_modules` is vendored input that esbuild already bundles at
 * load time, `dist` is build output, `.types` is regenerated by the editor on every
 * open, and `.git` is somebody's whole history. Shipping any of them makes the
 * package big and the diff meaningless.
 */
const EXCLUDED_DIRS = new Set(['node_modules', 'dist', 'out', '.git', PLUGIN_TYPES_DIR]);

/**
 * Refused before inflating. A plugin is source: the biggest legitimate one is a few
 * megabytes of icons. This is a bomb guard, not a quality judgement, so it sits far
 * above anything real rather than at a tasteful limit.
 */
const MAX_UNPACKED_BYTES = 128 * 1024 * 1024;

export interface PluginPackageEntry {
  name: string;
  size: number;
}

/** What an `.esplugin` says it is, read without extracting a byte of it. */
export interface PluginPackageInfo {
  ok: boolean;
  /** Why it cannot be installed. Set whenever `ok` is false. */
  error?: string;
  manifest?: PluginManifest;
  /** Display name for the manifest's locale-agnostic name field. */
  name?: string;
  /** Every file the archive claims to contain, for the pre-install preview. */
  files?: PluginPackageEntry[];
  /** Declared capabilities — shown BEFORE installing, not only at the trust gate. */
  capabilities?: string[];
}

export interface InstallPluginResult {
  ok: boolean;
  error?: string;
  id?: string;
  /** Absolute folder written. */
  dir?: string;
}

// =============================================================================
// Export
// =============================================================================

/**
 * Pack a plugin folder into `.esplugin` bytes.
 *
 * The manifest is re-validated on the way out: exporting a plugin whose plugin.json
 * has drifted into invalid would produce a file that cannot be installed anywhere,
 * and the moment to say so is while the author still has it open.
 */
export async function packPlugin(dir: string): Promise<{ ok: boolean; error?: string; data?: Buffer }> {
  const manifestFile = path.join(dir, 'plugin.json');
  if (!existsSync(manifestFile)) return { ok: false, error: 'folder has no plugin.json' };
  try {
    const parsed: unknown = JSON.parse(await readFile(manifestFile, 'utf8'));
    const result = validateManifest(parsed);
    if ('error' in result) return { ok: false, error: `plugin.json is not valid: ${result.error}` };

    const entries = zipTree(dir, '', (name, isDirectory) => {
      const base = name.split('/').pop() ?? name;
      return !(isDirectory && EXCLUDED_DIRS.has(base));
    });
    if (entries.length === 0) return { ok: false, error: 'nothing to pack' };
    return { ok: true, data: makeZip(entries) };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
}

/** A filename that is recognizably this plugin at this version. */
export function packageFileName(manifest: PluginManifest): string {
  return `${manifest.id}-${manifest.version}.${PLUGIN_PACKAGE_EXT}`;
}

// =============================================================================
// Import
// =============================================================================

/**
 * Read what an `.esplugin` contains WITHOUT extracting it — the preview the user
 * decides on. Never throws: a file that is not an archive at all is reported the
 * same way a bad manifest is, because from the user's side those are one question
 * ("can I install this?") with one answer.
 */
export function inspectPluginPackage(buf: Buffer): PluginPackageInfo {
  let listing;
  try {
    listing = listZip(buf);
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }

  const unpacked = listing.reduce((n, e) => n + e.size, 0);
  if (unpacked > MAX_UNPACKED_BYTES) {
    return { ok: false, error: `package expands to ${Math.round(unpacked / 1e6)} MB — refusing to unpack it` };
  }
  // Checked here as well as in extractZip: this runs first, and a file list shown
  // with `../` in it would be a preview of an attack presented as a manifest.
  const unsafe = listing.find((e) => e.name.startsWith('/') || e.name.includes('\\') || e.name.split('/').includes('..'));
  if (unsafe) return { ok: false, error: `unsafe entry name in package: ${unsafe.name}` };

  const files = listing.map((e) => ({ name: e.name, size: e.size }));
  const manifestEntry = listing.find((e) => e.name === 'plugin.json');
  if (!manifestEntry) return { ok: false, error: 'package has no plugin.json at its root', files };

  // Only the manifest is inflated — one small entry, after the size guard.
  let parsed: unknown;
  try {
    const entry = readOne(buf, 'plugin.json');
    parsed = JSON.parse(entry.toString('utf8'));
  } catch (err) {
    return { ok: false, error: `plugin.json could not be read: ${String(err)}`, files };
  }
  const result = validateManifest(parsed);
  if ('error' in result) return { ok: false, error: result.error, files };

  return {
    ok: true,
    manifest: result.manifest,
    name: resolveLocalized(result.manifest.name, 'en'),
    capabilities: result.manifest.capabilities ?? [],
    files,
  };
}

/**
 * Inflate one entry. Goes through `readZip`, which inflates everything — wasteful
 * for a single small file, but it is also the only path that verifies CRCs, and a
 * manifest read from an entry whose checksum was never checked is one we cannot act
 * on. The size guard has already run, so "everything" is bounded.
 */
function readOne(buf: Buffer, name: string): Buffer {
  const entry = readZip(buf).find((e) => e.name === name);
  if (!entry) throw new Error(`${name} is not in the package`);
  return entry.data;
}

/**
 * Install a package into `pluginsRoot`, under the id its own manifest declares.
 *
 * Refuses to overwrite: an existing folder is somebody's plugin — possibly one they
 * are editing — and "install" must never mean "replace what was there". Updating is
 * a separate decision the caller makes by removing the old one first.
 *
 * A failure mid-extract removes the partial folder, so a broken package cannot leave
 * a half-plugin behind for the panel to report as corrupt.
 */
export async function installPluginPackage(
  buf: Buffer,
  pluginsRoot: string,
): Promise<InstallPluginResult> {
  const info = inspectPluginPackage(buf);
  if (!info.ok || !info.manifest) return { ok: false, error: info.error ?? 'not a valid plugin package' };

  const id = info.manifest.id;
  const dir = path.join(pluginsRoot, id);
  if (existsSync(dir)) return { ok: false, error: `${id} is already installed here`, id };

  try {
    await mkdir(pluginsRoot, { recursive: true });
    extractZip(buf, dir);
    return { ok: true, id, dir };
  } catch (err) {
    await rm(dir, { recursive: true, force: true }).catch(() => {});
    return { ok: false, error: err instanceof Error ? err.message : String(err), id };
  }
}

/** Write packed bytes to a file the user chose. */
export async function writePackage(file: string, data: Buffer): Promise<void> {
  await writeFile(file, data);
}
