/**
 * @file    component.generated.ts
 * @brief   Auto-generated component metadata
 * @details Generated by EHT - DO NOT EDIT
 */

import type { AssetFieldType } from './scene';
import type { FieldMeta } from './component';
import type { Color, Entity, Quat, Vec2, Vec3, Vec4 } from './types';
import type { Dimension, Padding, VisualState } from './wasm.generated';

/**
 * Single-source-of-truth hash of the C++/TS boundary ABI (component
 * schema + pointer layouts). The WASM module exposes the same digest via
 * getAbiLayoutHash(); BuiltinBridge.connect() compares them and refuses to
 * run on mismatch, because mismatched offsets read the wrong heap bytes.
 */
export const ABI_LAYOUT_HASH = '124c9c3f323b74f1';

export interface AssetFieldMeta {
    field: string;
    type: AssetFieldType;
}

export interface SpineFieldMeta {
    skeletonField: string;
    atlasField: string;
}

export interface ComponentMetaEntry {
    defaults: Record<string, unknown>;
    assetFields: AssetFieldMeta[];
    spine?: SpineFieldMeta;
    entityFields: string[];
    colorFields: string[];
    animatableFields: string[];
    fields?: Record<string, FieldMeta>;
}

export const COMPONENT_META: Record<string, ComponentMetaEntry> = {
    BitmapText: {
        defaults: {
            text: '',
            color: { r: 1, g: 1, b: 1, a: 1 },
            fontSize: 1,
            align: 0,
            spacing: 0,
            layer: 0,
            font: 0,
            enabled: true,
        },
        assetFields: [{ field: 'font', type: 'font' as AssetFieldType }],
        entityFields: [],
        colorFields: ['color'],
        animatableFields: ['color.r', 'color.g', 'color.b', 'color.a'],
        fields: {
            fontSize: { min: 1 },
            align: { enum: [{ label: 'Left', value: 0 }, { label: 'Center', value: 1 }, { label: 'Right', value: 2 }] },
            layer: { step: 1 },
        },
    },
    BoxCollider: {
        defaults: {
            halfExtents: { x: 0.5, y: 0.5 },
            offset: { x: 0, y: 0 },
            density: 1,
            friction: 0.3,
            restitution: 0,
            isSensor: false,
            enabled: true,
            categoryBits: 0,
            maskBits: 0,
        },
        assetFields: [],
        entityFields: [],
        colorFields: [],
        animatableFields: [],
    },
    Camera: {
        defaults: {
            projectionType: 0,
            fov: 60,
            orthoSize: 5,
            nearPlane: 0.1,
            farPlane: 1000,
            aspectRatio: 0,
            isActive: false,
            priority: 0,
            viewport: { x: 0, y: 0, z: 1, w: 1 },
            clearFlags: 3,
        },
        assetFields: [],
        entityFields: [],
        colorFields: [],
        animatableFields: ['orthoSize'],
        fields: {
            projectionType: { enum: [{ label: 'Perspective', value: 0 }, { label: 'Orthographic', value: 1 }], tooltip: "Orthographic (2D) or Perspective projection." },
            fov: { min: 1, max: 179, unit: "°" },
            orthoSize: { min: 0, tooltip: "Half the visible height in world units (Orthographic)." },
            nearPlane: { min: 0, advanced: true },
            farPlane: { min: 0, advanced: true },
            aspectRatio: { advanced: true },
            priority: { step: 1, advanced: true },
            clearFlags: { tooltip: "Which buffers to clear before rendering this camera." },
        },
    },
    Canvas: {
        defaults: {
            designResolution: { x: 1920, y: 1080 },
            pixelsPerUnit: 100,
            scaleMode: 1,
            matchWidthOrHeight: 0.5,
            backgroundColor: { r: 0, g: 0, b: 0, a: 1 },
        },
        assetFields: [],
        entityFields: [],
        colorFields: ['backgroundColor'],
        animatableFields: [],
        fields: {
            pixelsPerUnit: { min: 1, tooltip: "Texture pixels mapped to one world unit." },
            scaleMode: { enum: [{ label: 'FixedWidth', value: 0 }, { label: 'FixedHeight', value: 1 }, { label: 'Expand', value: 2 }, { label: 'Shrink', value: 3 }, { label: 'Match', value: 4 }], tooltip: "How the canvas adapts the design resolution to the screen." },
            matchWidthOrHeight: { min: 0, max: 1, slider: true, tooltip: "0 matches width, 1 matches height (Match mode only)." },
        },
    },
    CapsuleCollider: {
        defaults: {
            radius: 0.25,
            halfHeight: 0.5,
            offset: { x: 0, y: 0 },
            density: 1,
            friction: 0.3,
            restitution: 0,
            isSensor: false,
            enabled: true,
            categoryBits: 0,
            maskBits: 0,
        },
        assetFields: [],
        entityFields: [],
        colorFields: [],
        animatableFields: [],
    },
    Children: {
        defaults: {
            entities: [],
        },
        assetFields: [],
        entityFields: ['entities'],
        colorFields: [],
        animatableFields: [],
    },
    CircleCollider: {
        defaults: {
            radius: 0.5,
            offset: { x: 0, y: 0 },
            density: 1,
            friction: 0.3,
            restitution: 0,
            isSensor: false,
            enabled: true,
            categoryBits: 0,
            maskBits: 0,
        },
        assetFields: [],
        entityFields: [],
        colorFields: [],
        animatableFields: [],
    },
    FlexContainer: {
        defaults: {
            direction: 0,
            wrap: 0,
            justifyContent: 0,
            alignItems: 3,
            alignContent: 0,
            gap: { x: 0, y: 0 },
            padding: { left: 0, top: 0, right: 0, bottom: 0 },
        },
        assetFields: [],
        entityFields: [],
        colorFields: [],
        animatableFields: [],
        fields: {
            direction: { enum: [{ label: 'Row', value: 0 }, { label: 'Column', value: 1 }, { label: 'RowReverse', value: 2 }, { label: 'ColumnReverse', value: 3 }] },
            wrap: { enum: [{ label: 'NoWrap', value: 0 }, { label: 'Wrap', value: 1 }] },
            justifyContent: { enum: [{ label: 'Start', value: 0 }, { label: 'Center', value: 1 }, { label: 'End', value: 2 }, { label: 'SpaceBetween', value: 3 }, { label: 'SpaceAround', value: 4 }, { label: 'SpaceEvenly', value: 5 }] },
            alignItems: { enum: [{ label: 'Start', value: 0 }, { label: 'Center', value: 1 }, { label: 'End', value: 2 }, { label: 'Stretch', value: 3 }] },
            alignContent: { enum: [{ label: 'Start', value: 0 }, { label: 'Center', value: 1 }, { label: 'End', value: 2 }, { label: 'Stretch', value: 3 }, { label: 'SpaceBetween', value: 4 }, { label: 'SpaceAround', value: 5 }] },
        },
    },
    Interactable: {
        defaults: {
            enabled: true,
            blockRaycast: true,
            raycastTarget: true,
        },
        assetFields: [],
        entityFields: [],
        colorFields: [],
        animatableFields: [],
    },
    Light2D: {
        defaults: {
            type: 0,
            color: { r: 1, g: 1, b: 1, a: 1 },
            intensity: 1,
            radius: 200,
            direction: { x: 0, y: 0 },
            innerAngle: 30,
            outerAngle: 45,
            shadowSoftness: 0,
            shadowDistance: 0,
            enabled: true,
        },
        assetFields: [],
        entityFields: [],
        colorFields: ['color'],
        animatableFields: ['color.r', 'color.g', 'color.b', 'color.a', 'intensity', 'radius', 'innerAngle', 'outerAngle', 'shadowSoftness', 'shadowDistance'],
        fields: {
            type: { tooltip: "Point, Directional, Ambient, or Spot." },
            intensity: { min: 0, tooltip: "Brightness multiplier of the light." },
            radius: { min: 0, tooltip: "Falloff reach in world units (Point / Spot)." },
            direction: { tooltip: "Aim direction (Directional / Spot).", advanced: true },
            innerAngle: { min: 0, max: 180, unit: "°", advanced: true },
            outerAngle: { min: 0, max: 180, unit: "°", advanced: true },
            shadowSoftness: { min: 0, tooltip: "Shadow softness (light-source size); 0 = hard edge." },
            shadowDistance: { min: 0, tooltip: "Directional shadow distance; 0 = no directional shadow.", advanced: true },
        },
    },
    Parent: {
        defaults: {
            entity: 0,
        },
        assetFields: [],
        entityFields: ['entity'],
        colorFields: [],
        animatableFields: [],
    },
    ParticleEmitter: {
        defaults: {
            rate: 10,
            burstCount: 0,
            burstInterval: 1,
            duration: 5,
            looping: true,
            playOnStart: true,
            maxParticles: 1000,
            lifetimeMin: 5,
            lifetimeMax: 5,
            shape: 3,
            shapeRadius: 100,
            shapeSize: { x: 100, y: 100 },
            shapeAngle: 25,
            speedMin: 500,
            speedMax: 500,
            angleSpreadMin: 0,
            angleSpreadMax: 360,
            startSizeMin: 100,
            startSizeMax: 100,
            endSizeMin: 100,
            endSizeMax: 100,
            sizeEasing: 0,
            startColor: { r: 1, g: 1, b: 1, a: 1 },
            endColor: { r: 1, g: 1, b: 1, a: 0 },
            colorEasing: 0,
            rotationMin: 0,
            rotationMax: 0,
            angularVelocityMin: 0,
            angularVelocityMax: 0,
            gravity: { x: 0, y: 0 },
            damping: 0,
            texture: 0,
            spriteColumns: 1,
            spriteRows: 1,
            spriteFPS: 10,
            spriteLoop: true,
            blendMode: 1,
            layer: 0,
            material: 0,
            simulationSpace: 0,
            enabled: true,
        },
        assetFields: [{ field: 'texture', type: 'texture' as AssetFieldType }, { field: 'material', type: 'material' as AssetFieldType }],
        entityFields: [],
        colorFields: ['startColor', 'endColor'],
        animatableFields: [],
        fields: {
            rate: { min: 0, category: "Emission" },
            burstCount: { min: 0, step: 1, category: "Emission" },
            burstInterval: { min: 0, category: "Emission" },
            duration: { min: 0, category: "Emission" },
            looping: { category: "Emission" },
            playOnStart: { category: "Emission" },
            maxParticles: { min: 1, step: 1, category: "Emission" },
            lifetimeMin: { min: 0, category: "Lifetime" },
            lifetimeMax: { min: 0, category: "Lifetime" },
            shape: { category: "Shape" },
            shapeRadius: { min: 0, category: "Shape" },
            shapeSize: { category: "Shape" },
            shapeAngle: { unit: "°", category: "Shape" },
            speedMin: { category: "Velocity" },
            speedMax: { category: "Velocity" },
            angleSpreadMin: { unit: "°", category: "Velocity" },
            angleSpreadMax: { unit: "°", category: "Velocity" },
            startSizeMin: { min: 0, category: "Size" },
            startSizeMax: { min: 0, category: "Size" },
            endSizeMin: { min: 0, category: "Size" },
            endSizeMax: { min: 0, category: "Size" },
            sizeEasing: { category: "Size" },
            startColor: { category: "Color" },
            endColor: { category: "Color" },
            colorEasing: { category: "Color" },
            rotationMin: { unit: "°", category: "Rotation" },
            rotationMax: { unit: "°", category: "Rotation" },
            angularVelocityMin: { category: "Rotation" },
            angularVelocityMax: { category: "Rotation" },
            gravity: { category: "Velocity" },
            damping: { min: 0, category: "Velocity" },
            texture: { category: "Texture" },
            spriteColumns: { min: 1, step: 1, category: "Texture" },
            spriteRows: { min: 1, step: 1, category: "Texture" },
            spriteFPS: { min: 0, category: "Texture" },
            spriteLoop: { category: "Texture" },
            blendMode: { category: "Rendering" },
            layer: { step: 1, category: "Rendering", enumSource: "sortingLayers" },
            material: { category: "Rendering" },
            simulationSpace: { category: "Rendering" },
        },
    },
    RigidBody: {
        defaults: {
            bodyType: 2,
            gravityScale: 1,
            linearDamping: 0,
            angularDamping: 0,
            fixedRotation: false,
            bullet: false,
            enabled: true,
        },
        assetFields: [],
        entityFields: [],
        colorFields: [],
        animatableFields: [],
        fields: {
            bodyType: { enum: [{ label: 'Static', value: 0 }, { label: 'Kinematic', value: 1 }, { label: 'Dynamic', value: 2 }] },
        },
    },
    SegmentCollider: {
        defaults: {
            point1: { x: -0.5, y: 0 },
            point2: { x: 0.5, y: 0 },
            density: 1,
            friction: 0.3,
            restitution: 0,
            isSensor: false,
            enabled: true,
            categoryBits: 0,
            maskBits: 0,
        },
        assetFields: [],
        entityFields: [],
        colorFields: [],
        animatableFields: [],
    },
    ShadowCaster2D: {
        defaults: {
            size: { x: 32, y: 32 },
            enabled: true,
        },
        assetFields: [],
        entityFields: [],
        colorFields: [],
        animatableFields: ['size.x', 'size.y'],
        fields: {
            size: { min: 0, tooltip: "Occluder box size in world units (centered on the entity)." },
        },
    },
    ShapeRenderer: {
        defaults: {
            shapeType: 0,
            color: { r: 1, g: 1, b: 1, a: 1 },
            size: { x: 100, y: 100 },
            cornerRadius: 0,
            layer: 0,
            enabled: true,
        },
        assetFields: [],
        entityFields: [],
        colorFields: ['color'],
        animatableFields: [],
        fields: {
            cornerRadius: { min: 0 },
            layer: { step: 1, enumSource: "sortingLayers" },
        },
    },
    SpineAnimation: {
        defaults: {
            skeletonPath: '',
            atlasPath: '',
            skin: '',
            animation: '',
            timeScale: 1,
            loop: true,
            playing: true,
            flipX: false,
            flipY: false,
            color: { r: 1, g: 1, b: 1, a: 1 },
            layer: 0,
            skeletonScale: 1,
            material: 0,
            enabled: true,
        },
        assetFields: [{ field: 'material', type: 'material' as AssetFieldType }],
        spine: { skeletonField: 'skeletonPath', atlasField: 'atlasPath' },
        entityFields: [],
        colorFields: ['color'],
        animatableFields: [],
        fields: {
            timeScale: { min: 0 },
            layer: { step: 1, enumSource: "sortingLayers" },
            skeletonScale: { min: 0 },
        },
    },
    Sprite: {
        defaults: {
            texture: 0,
            color: { r: 1, g: 1, b: 1, a: 1 },
            size: { x: 1, y: 1 },
            pivot: { x: 0.5, y: 0.5 },
            uvOffset: { x: 0, y: 0 },
            uvScale: { x: 1, y: 1 },
            layer: 0,
            flipX: false,
            flipY: false,
            tileSize: { x: 0, y: 0 },
            tileSpacing: { x: 0, y: 0 },
            material: 0,
            enabled: true,
        },
        assetFields: [{ field: 'texture', type: 'texture' as AssetFieldType }, { field: 'material', type: 'material' as AssetFieldType }],
        entityFields: [],
        colorFields: ['color'],
        animatableFields: ['color.r', 'color.g', 'color.b', 'color.a', 'size.x', 'size.y'],
        fields: {
            color: { tooltip: "Tint multiplied into the texture (white = unchanged)." },
            pivot: { tooltip: "Anchor point (0–1) the sprite rotates and scales about.", advanced: true },
            uvOffset: { advanced: true },
            uvScale: { advanced: true },
            layer: { step: 1, tooltip: "Sorting layer — controls draw order across sprites.", enumSource: "sortingLayers" },
            tileSize: { advanced: true },
            tileSpacing: { advanced: true },
            material: { advanced: true },
        },
    },
    StateMachine: {
        defaults: {
            current: '',
            previous: '',
        },
        assetFields: [],
        entityFields: [],
        colorFields: [],
        animatableFields: [],
    },
    StateVisuals: {
        defaults: {
            targetGraphic: 0,
            transitionFlags: 0,
            fadeDuration: 0,
            states: [],
        },
        assetFields: [],
        entityFields: ['targetGraphic'],
        colorFields: [],
        animatableFields: [],
    },
    TilemapLayer: {
        defaults: {
            cellSize: { x: 32, y: 32 },
            originOffset: { x: 0, y: 0 },
            tileset: 0,
            tilesetColumns: 1,
            tilesetRows: 1,
            renderLayer: 0,
            tintColor: { r: 1, g: 1, b: 1, a: 1 },
            opacity: 1,
            parallaxFactor: { x: 1, y: 1 },
            visible: true,
        },
        assetFields: [{ field: 'tileset', type: 'texture' as AssetFieldType }],
        entityFields: [],
        colorFields: ['tintColor'],
        animatableFields: ['tintColor.r', 'tintColor.g', 'tintColor.b', 'tintColor.a', 'opacity'],
        fields: {
            tilesetColumns: { min: 1, step: 1 },
            tilesetRows: { min: 1, step: 1 },
            renderLayer: { step: 1, enumSource: "sortingLayers" },
            opacity: { min: 0, max: 1, slider: true, tooltip: "Layer transparency (0 = invisible, 1 = opaque)." },
        },
    },
    Transform: {
        defaults: {
            position: { x: 0, y: 0, z: 0 },
            rotation: { w: 1, x: 0, y: 0, z: 0 },
            scale: { x: 1, y: 1, z: 1 },
            worldPosition: { x: 0, y: 0, z: 0 },
            worldRotation: { w: 1, x: 0, y: 0, z: 0 },
            worldScale: { x: 1, y: 1, z: 1 },
        },
        assetFields: [],
        entityFields: [],
        colorFields: [],
        animatableFields: ['position.x', 'position.y', 'position.z', 'rotation.z', 'scale.x', 'scale.y', 'scale.z'],
        fields: {
            position: { tooltip: "Local position in world units, relative to the parent." },
            rotation: { tooltip: "Rotation about the Z axis, in degrees." },
            scale: { tooltip: "Local scale per axis (1 = original size; negative flips)." },
        },
    },
    UIInteraction: {
        defaults: {
            hovered: false,
            pressed: false,
            justPressed: false,
            justReleased: false,
        },
        assetFields: [],
        entityFields: [],
        colorFields: [],
        animatableFields: [],
    },
    UIMask: {
        defaults: {
            enabled: true,
            mode: 0,
        },
        assetFields: [],
        entityFields: [],
        colorFields: [],
        animatableFields: [],
        fields: {
            mode: { enum: [{ label: 'Scissor', value: 0 }, { label: 'Stencil', value: 1 }] },
        },
    },
    UINode: {
        defaults: {
            position: 0,
            width: { value: 0, unit: 2 },
            height: { value: 0, unit: 2 },
            minWidth: { value: 0, unit: 2 },
            minHeight: { value: 0, unit: 2 },
            maxWidth: { value: 0, unit: 2 },
            maxHeight: { value: 0, unit: 2 },
            flexGrow: 0,
            flexShrink: 1,
            flexBasis: { value: 0, unit: 2 },
            alignSelf: 0,
            marginLeft: { value: 0, unit: 0 },
            marginTop: { value: 0, unit: 0 },
            marginRight: { value: 0, unit: 0 },
            marginBottom: { value: 0, unit: 0 },
            insetLeft: { value: 0, unit: 2 },
            insetTop: { value: 0, unit: 2 },
            insetRight: { value: 0, unit: 2 },
            insetBottom: { value: 0, unit: 2 },
        },
        assetFields: [],
        entityFields: [],
        colorFields: [],
        animatableFields: [],
        fields: {
            position: { enum: [{ label: 'Relative', value: 0 }, { label: 'Absolute', value: 1 }] },
            alignSelf: { enum: [{ label: 'Auto', value: 0 }, { label: 'Start', value: 1 }, { label: 'Center', value: 2 }, { label: 'End', value: 3 }, { label: 'Stretch', value: 4 }] },
        },
    },
    UIVisual: {
        defaults: {
            visualType: 0,
            texture: 0,
            color: { r: 1, g: 1, b: 1, a: 1 },
            uvOffset: { x: 0, y: 0 },
            uvScale: { x: 1, y: 1 },
            sliceBorder: { x: 0, y: 0, z: 0, w: 0 },
            tileSize: { x: 32, y: 32 },
            fillMethod: 0,
            fillOrigin: 0,
            fillAmount: 1,
            material: 0,
            enabled: true,
        },
        assetFields: [{ field: 'texture', type: 'texture' as AssetFieldType }, { field: 'material', type: 'material' as AssetFieldType }],
        entityFields: [],
        colorFields: ['color'],
        animatableFields: ['color.r', 'color.g', 'color.b', 'color.a', 'fillAmount'],
        fields: {
            visualType: { enum: [{ label: 'None', value: 0 }, { label: 'SolidColor', value: 1 }, { label: 'Image', value: 2 }, { label: 'NineSlice', value: 3 }, { label: 'Tiled', value: 4 }, { label: 'Filled', value: 5 }] },
            fillMethod: { enum: [{ label: 'Horizontal', value: 0 }, { label: 'Vertical', value: 1 }] },
            fillOrigin: { enum: [{ label: 'Left', value: 0 }, { label: 'Right', value: 1 }, { label: 'Bottom', value: 2 }, { label: 'Top', value: 3 }] },
        },
    },
    Velocity: {
        defaults: {
            linear: { x: 0, y: 0, z: 0 },
            angular: { x: 0, y: 0, z: 0 },
        },
        assetFields: [],
        entityFields: [],
        colorFields: [],
        animatableFields: [],
    },
};

// C++-backed builtin component data shapes — the ES_COMPONENT struct fields,
// generated so the TS field types cannot drift from the C++ structs. A consumer
// adds any TS-only authoring field (e.g. Camera.showFrustum) by extending these.

export interface BitmapTextData {
    text: string;
    color: Color;
    fontSize: number;
    align: number;
    spacing: number;
    layer: number;
    font: number;
    enabled: boolean;
}

export interface BoxColliderData {
    halfExtents: Vec2;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
    categoryBits: number;
    maskBits: number;
}

export interface CameraData {
    projectionType: number;
    fov: number;
    orthoSize: number;
    nearPlane: number;
    farPlane: number;
    aspectRatio: number;
    isActive: boolean;
    priority: number;
    viewport: Vec4;
    clearFlags: number;
}

export interface CanvasData {
    designResolution: Vec2;
    pixelsPerUnit: number;
    scaleMode: number;
    matchWidthOrHeight: number;
    backgroundColor: Color;
}

export interface CapsuleColliderData {
    radius: number;
    halfHeight: number;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
    categoryBits: number;
    maskBits: number;
}

export interface ChildrenData {
    entities: Entity[];
}

export interface CircleColliderData {
    radius: number;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
    categoryBits: number;
    maskBits: number;
}

export interface FlexContainerData {
    direction: number;
    wrap: number;
    justifyContent: number;
    alignItems: number;
    alignContent: number;
    gap: Vec2;
    padding: Padding;
}

export interface InteractableData {
    enabled: boolean;
    blockRaycast: boolean;
    raycastTarget: boolean;
}

export interface Light2DData {
    type: number;
    color: Color;
    intensity: number;
    radius: number;
    direction: Vec2;
    innerAngle: number;
    outerAngle: number;
    shadowSoftness: number;
    shadowDistance: number;
    enabled: boolean;
}

export interface ParentData {
    entity: Entity;
}

export interface ParticleEmitterData {
    rate: number;
    burstCount: number;
    burstInterval: number;
    duration: number;
    looping: boolean;
    playOnStart: boolean;
    maxParticles: number;
    lifetimeMin: number;
    lifetimeMax: number;
    shape: number;
    shapeRadius: number;
    shapeSize: Vec2;
    shapeAngle: number;
    speedMin: number;
    speedMax: number;
    angleSpreadMin: number;
    angleSpreadMax: number;
    startSizeMin: number;
    startSizeMax: number;
    endSizeMin: number;
    endSizeMax: number;
    sizeEasing: number;
    startColor: Color;
    endColor: Color;
    colorEasing: number;
    rotationMin: number;
    rotationMax: number;
    angularVelocityMin: number;
    angularVelocityMax: number;
    gravity: Vec2;
    damping: number;
    texture: number;
    spriteColumns: number;
    spriteRows: number;
    spriteFPS: number;
    spriteLoop: boolean;
    blendMode: number;
    layer: number;
    material: number;
    simulationSpace: number;
    enabled: boolean;
}

export interface RigidBodyData {
    bodyType: number;
    gravityScale: number;
    linearDamping: number;
    angularDamping: number;
    fixedRotation: boolean;
    bullet: boolean;
    enabled: boolean;
}

export interface SegmentColliderData {
    point1: Vec2;
    point2: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
    categoryBits: number;
    maskBits: number;
}

export interface ShadowCaster2DData {
    size: Vec2;
    enabled: boolean;
}

export interface ShapeRendererData {
    shapeType: number;
    color: Color;
    size: Vec2;
    cornerRadius: number;
    layer: number;
    enabled: boolean;
}

export interface SpineAnimationData {
    skeletonPath: string;
    atlasPath: string;
    skin: string;
    animation: string;
    timeScale: number;
    loop: boolean;
    playing: boolean;
    flipX: boolean;
    flipY: boolean;
    color: Color;
    layer: number;
    skeletonScale: number;
    material: number;
    enabled: boolean;
}

export interface SpriteData {
    texture: number;
    color: Color;
    size: Vec2;
    pivot: Vec2;
    uvOffset: Vec2;
    uvScale: Vec2;
    layer: number;
    flipX: boolean;
    flipY: boolean;
    tileSize: Vec2;
    tileSpacing: Vec2;
    material: number;
    enabled: boolean;
}

export interface StateMachineData {
    current: string;
    previous: string;
}

export interface StateVisualsData {
    targetGraphic: Entity;
    transitionFlags: number;
    fadeDuration: number;
    states: VisualState[];
}

export interface TilemapLayerData {
    cellSize: Vec2;
    originOffset: Vec2;
    tileset: number;
    tilesetColumns: number;
    tilesetRows: number;
    renderLayer: number;
    tintColor: Color;
    opacity: number;
    parallaxFactor: Vec2;
    visible: boolean;
}

export interface TransformData {
    position: Vec3;
    rotation: Quat;
    scale: Vec3;
    worldPosition: Vec3;
    worldRotation: Quat;
    worldScale: Vec3;
}

export interface UIInteractionData {
    hovered: boolean;
    pressed: boolean;
    justPressed: boolean;
    justReleased: boolean;
}

export interface UIMaskData {
    enabled: boolean;
    mode: number;
}

export interface UINodeData {
    position: number;
    width: Dimension;
    height: Dimension;
    minWidth: Dimension;
    minHeight: Dimension;
    maxWidth: Dimension;
    maxHeight: Dimension;
    flexGrow: number;
    flexShrink: number;
    flexBasis: Dimension;
    alignSelf: number;
    marginLeft: Dimension;
    marginTop: Dimension;
    marginRight: Dimension;
    marginBottom: Dimension;
    insetLeft: Dimension;
    insetTop: Dimension;
    insetRight: Dimension;
    insetBottom: Dimension;
}

export interface UIVisualData {
    visualType: number;
    texture: number;
    color: Color;
    uvOffset: Vec2;
    uvScale: Vec2;
    sliceBorder: Vec4;
    tileSize: Vec2;
    fillMethod: number;
    fillOrigin: number;
    fillAmount: number;
    material: number;
    enabled: boolean;
}

export interface VelocityData {
    linear: Vec3;
    angular: Vec3;
}
