/**
 * @file    wasm.generated.ts
 * @brief   ESEngine WASM Bindings TypeScript Definitions
 * @details Generated by EHT - DO NOT EDIT
 */

import type { Entity, Vec2, Vec3, Vec4, Quat } from './types';

// Additional Math Types
export interface UVec2 { x: number; y: number; }
export interface Padding { left: number; top: number; right: number; bottom: number; }
export interface Dimension { value: number; unit: number; }
export interface VisualState { name: string; r: number; g: number; b: number; a: number; sprite: number; scale: number; }
export type Mat4 = number[];

// Emscripten Vector Types
export interface VectorEntity {
    size(): number;
    get(index: number): number;
    push_back(value: number): void;
    set(index: number, value: number): boolean;
    delete(): void;
}

// Enums

export enum AlignContent {
    Start = 0,
    Center = 1,
    End = 2,
    Stretch = 3,
    SpaceBetween = 4,
    SpaceAround = 5,
}

export enum AlignItems {
    Start = 0,
    Center = 1,
    End = 2,
    Stretch = 3,
}

export enum AlignSelf {
    Auto = 0,
    Start = 1,
    Center = 2,
    End = 3,
    Stretch = 4,
}

export enum BodyType {
    Static = 0,
    Kinematic = 1,
    Dynamic = 2,
}

export enum CanvasScaleMode {
    FixedWidth = 0,
    FixedHeight = 1,
    Expand = 2,
    Shrink = 3,
    Match = 4,
}

export enum ClearFlags {
    Nothing = 0,
    Color = 1,
    Depth = 2,
    ColorAndDepth = 3,
}

export enum EmitterShape {
    Point = 0,
    Circle = 1,
    Rectangle = 2,
    Cone = 3,
}

export enum FlexDirection {
    Row = 0,
    Column = 1,
    RowReverse = 2,
    ColumnReverse = 3,
}

export enum FlexWrap {
    NoWrap = 0,
    Wrap = 1,
}

export enum JustifyContent {
    Start = 0,
    Center = 1,
    End = 2,
    SpaceBetween = 3,
    SpaceAround = 4,
    SpaceEvenly = 5,
}

export enum MaskMode {
    Scissor = 0,
    Stencil = 1,
}

export enum ProjectionType {
    Perspective = 0,
    Orthographic = 1,
}

export enum SimulationSpace {
    World = 0,
    Local = 1,
}

export enum TextAlign {
    Left = 0,
    Center = 1,
    Right = 2,
}

export enum UIFillMethod {
    Horizontal = 0,
    Vertical = 1,
}

export enum UIFillOrigin {
    Left = 0,
    Right = 1,
    Bottom = 2,
    Top = 3,
}

export enum UIPositionType {
    Relative = 0,
    Absolute = 1,
}

export enum UIVisualType {
    None = 0,
    SolidColor = 1,
    Image = 2,
    NineSlice = 3,
    Tiled = 4,
    Filled = 5,
}

// Components

export interface BitmapText {
    text: string;
    color: Vec4;
    fontSize: number;
    align: number;
    spacing: number;
    layer: number;
    font: number;
    enabled: boolean;
}

export interface BoxCollider {
    halfExtents: Vec2;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
    categoryBits: number;
    maskBits: number;
}

export interface Camera {
    projectionType: number;
    fov: number;
    orthoSize: number;
    nearPlane: number;
    farPlane: number;
    aspectRatio: number;
    isActive: boolean;
    priority: number;
    viewport: Vec4;
    clearFlags: number;
}

export interface Canvas {
    designResolution: UVec2;
    pixelsPerUnit: number;
    scaleMode: number;
    matchWidthOrHeight: number;
    backgroundColor: Vec4;
}

export interface CapsuleCollider {
    radius: number;
    halfHeight: number;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
    categoryBits: number;
    maskBits: number;
}

export interface Children {
    entities: VectorEntity;
}

export interface CircleCollider {
    radius: number;
    offset: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
    categoryBits: number;
    maskBits: number;
}

export interface FlexContainer {
    direction: number;
    wrap: number;
    justifyContent: number;
    alignItems: number;
    alignContent: number;
    gap: Vec2;
    padding: Padding;
}

export interface Interactable {
    enabled: boolean;
    blockRaycast: boolean;
    raycastTarget: boolean;
}

export interface Parent {
    entity: number;
}

export interface ParticleEmitter {
    rate: number;
    burstCount: number;
    burstInterval: number;
    duration: number;
    looping: boolean;
    playOnStart: boolean;
    maxParticles: number;
    lifetimeMin: number;
    lifetimeMax: number;
    shape: number;
    shapeRadius: number;
    shapeSize: Vec2;
    shapeAngle: number;
    speedMin: number;
    speedMax: number;
    angleSpreadMin: number;
    angleSpreadMax: number;
    startSizeMin: number;
    startSizeMax: number;
    endSizeMin: number;
    endSizeMax: number;
    sizeEasing: number;
    startColor: Vec4;
    endColor: Vec4;
    colorEasing: number;
    rotationMin: number;
    rotationMax: number;
    angularVelocityMin: number;
    angularVelocityMax: number;
    gravity: Vec2;
    damping: number;
    texture: number;
    spriteColumns: number;
    spriteRows: number;
    spriteFPS: number;
    spriteLoop: boolean;
    blendMode: number;
    layer: number;
    material: number;
    simulationSpace: number;
    enabled: boolean;
}

export interface RigidBody {
    bodyType: number;
    gravityScale: number;
    linearDamping: number;
    angularDamping: number;
    fixedRotation: boolean;
    bullet: boolean;
    enabled: boolean;
}

export interface SegmentCollider {
    point1: Vec2;
    point2: Vec2;
    density: number;
    friction: number;
    restitution: number;
    isSensor: boolean;
    enabled: boolean;
    categoryBits: number;
    maskBits: number;
}

export interface ShapeRenderer {
    shapeType: number;
    color: Vec4;
    size: Vec2;
    cornerRadius: number;
    layer: number;
    enabled: boolean;
}

export interface SpineAnimation {
    skeletonPath: string;
    atlasPath: string;
    skin: string;
    animation: string;
    timeScale: number;
    loop: boolean;
    playing: boolean;
    flipX: boolean;
    flipY: boolean;
    color: Vec4;
    layer: number;
    skeletonScale: number;
    material: number;
    enabled: boolean;
}

export interface Sprite {
    texture: number;
    color: Vec4;
    size: Vec2;
    pivot: Vec2;
    uvOffset: Vec2;
    uvScale: Vec2;
    layer: number;
    flipX: boolean;
    flipY: boolean;
    tileSize: Vec2;
    tileSpacing: Vec2;
    material: number;
    enabled: boolean;
}

export interface StateMachine {
    current: string;
    previous: string;
}

export interface StateVisuals {
    targetGraphic: number;
    transitionFlags: number;
    fadeDuration: number;
    states: VisualState[];
}

export interface TilemapLayer {
    cellSize: Vec2;
    originOffset: Vec2;
    tileset: number;
    tilesetColumns: number;
    tilesetRows: number;
    renderLayer: number;
    tintColor: Vec4;
    opacity: number;
    parallaxFactor: Vec2;
    visible: boolean;
}

export interface Transform {
    position: Vec3;
    rotation: Quat;
    scale: Vec3;
    worldPosition: Vec3;
    worldRotation: Quat;
    worldScale: Vec3;
}

export interface UIInteraction {
    hovered: boolean;
    pressed: boolean;
    justPressed: boolean;
    justReleased: boolean;
}

export interface UIMask {
    enabled: boolean;
    mode: number;
}

export interface UINode {
    position: number;
    width: Dimension;
    height: Dimension;
    minWidth: Dimension;
    minHeight: Dimension;
    maxWidth: Dimension;
    maxHeight: Dimension;
    flexGrow: number;
    flexShrink: number;
    flexBasis: Dimension;
    alignSelf: number;
    marginLeft: Dimension;
    marginTop: Dimension;
    marginRight: Dimension;
    marginBottom: Dimension;
    insetLeft: Dimension;
    insetTop: Dimension;
    insetRight: Dimension;
    insetBottom: Dimension;
}

export interface UIVisual {
    visualType: number;
    texture: number;
    color: Vec4;
    uvOffset: Vec2;
    uvScale: Vec2;
    sliceBorder: Vec4;
    tileSize: Vec2;
    fillMethod: number;
    fillOrigin: number;
    fillAmount: number;
    material: number;
    enabled: boolean;
}

export interface Velocity {
    linear: Vec3;
    angular: Vec3;
}

// Registry
export interface Registry {
    create(): Entity;
    destroy(entity: Entity): void;
    valid(entity: Entity): boolean;
    entityCount(): number;

    hasBitmapText(entity: Entity): boolean;
    getBitmapText(entity: Entity): BitmapText;
    addBitmapText(entity: Entity, component: BitmapText): void;
    removeBitmapText(entity: Entity): void;
    hasBoxCollider(entity: Entity): boolean;
    getBoxCollider(entity: Entity): BoxCollider;
    addBoxCollider(entity: Entity, component: BoxCollider): void;
    removeBoxCollider(entity: Entity): void;
    hasCamera(entity: Entity): boolean;
    getCamera(entity: Entity): Camera;
    addCamera(entity: Entity, component: Camera): void;
    removeCamera(entity: Entity): void;
    hasCanvas(entity: Entity): boolean;
    getCanvas(entity: Entity): Canvas;
    addCanvas(entity: Entity, component: Canvas): void;
    removeCanvas(entity: Entity): void;
    hasCapsuleCollider(entity: Entity): boolean;
    getCapsuleCollider(entity: Entity): CapsuleCollider;
    addCapsuleCollider(entity: Entity, component: CapsuleCollider): void;
    removeCapsuleCollider(entity: Entity): void;
    hasChildren(entity: Entity): boolean;
    getChildren(entity: Entity): Children;
    addChildren(entity: Entity, component: Children): void;
    removeChildren(entity: Entity): void;
    hasCircleCollider(entity: Entity): boolean;
    getCircleCollider(entity: Entity): CircleCollider;
    addCircleCollider(entity: Entity, component: CircleCollider): void;
    removeCircleCollider(entity: Entity): void;
    hasFlexContainer(entity: Entity): boolean;
    getFlexContainer(entity: Entity): FlexContainer;
    addFlexContainer(entity: Entity, component: FlexContainer): void;
    removeFlexContainer(entity: Entity): void;
    hasInteractable(entity: Entity): boolean;
    getInteractable(entity: Entity): Interactable;
    addInteractable(entity: Entity, component: Interactable): void;
    removeInteractable(entity: Entity): void;
    hasParent(entity: Entity): boolean;
    getParent(entity: Entity): Parent;
    addParent(entity: Entity, component: Parent): void;
    removeParent(entity: Entity): void;
    hasParticleEmitter(entity: Entity): boolean;
    getParticleEmitter(entity: Entity): ParticleEmitter;
    addParticleEmitter(entity: Entity, component: ParticleEmitter): void;
    removeParticleEmitter(entity: Entity): void;
    hasRigidBody(entity: Entity): boolean;
    getRigidBody(entity: Entity): RigidBody;
    addRigidBody(entity: Entity, component: RigidBody): void;
    removeRigidBody(entity: Entity): void;
    hasSegmentCollider(entity: Entity): boolean;
    getSegmentCollider(entity: Entity): SegmentCollider;
    addSegmentCollider(entity: Entity, component: SegmentCollider): void;
    removeSegmentCollider(entity: Entity): void;
    hasShapeRenderer(entity: Entity): boolean;
    getShapeRenderer(entity: Entity): ShapeRenderer;
    addShapeRenderer(entity: Entity, component: ShapeRenderer): void;
    removeShapeRenderer(entity: Entity): void;
    hasSpineAnimation(entity: Entity): boolean;
    getSpineAnimation(entity: Entity): SpineAnimation;
    addSpineAnimation(entity: Entity, component: SpineAnimation): void;
    removeSpineAnimation(entity: Entity): void;
    hasSprite(entity: Entity): boolean;
    getSprite(entity: Entity): Sprite;
    addSprite(entity: Entity, component: Sprite): void;
    removeSprite(entity: Entity): void;
    hasStateMachine(entity: Entity): boolean;
    getStateMachine(entity: Entity): StateMachine;
    addStateMachine(entity: Entity, component: StateMachine): void;
    removeStateMachine(entity: Entity): void;
    hasStateVisuals(entity: Entity): boolean;
    getStateVisuals(entity: Entity): StateVisuals;
    addStateVisuals(entity: Entity, component: StateVisuals): void;
    removeStateVisuals(entity: Entity): void;
    hasTilemapLayer(entity: Entity): boolean;
    getTilemapLayer(entity: Entity): TilemapLayer;
    addTilemapLayer(entity: Entity, component: TilemapLayer): void;
    removeTilemapLayer(entity: Entity): void;
    hasTransform(entity: Entity): boolean;
    getTransform(entity: Entity): Transform;
    addTransform(entity: Entity, component: Transform): void;
    removeTransform(entity: Entity): void;
    hasUIInteraction(entity: Entity): boolean;
    getUIInteraction(entity: Entity): UIInteraction;
    addUIInteraction(entity: Entity, component: UIInteraction): void;
    removeUIInteraction(entity: Entity): void;
    hasUIMask(entity: Entity): boolean;
    getUIMask(entity: Entity): UIMask;
    addUIMask(entity: Entity, component: UIMask): void;
    removeUIMask(entity: Entity): void;
    hasUINode(entity: Entity): boolean;
    getUINode(entity: Entity): UINode;
    addUINode(entity: Entity, component: UINode): void;
    removeUINode(entity: Entity): void;
    hasUIVisual(entity: Entity): boolean;
    getUIVisual(entity: Entity): UIVisual;
    addUIVisual(entity: Entity, component: UIVisual): void;
    removeUIVisual(entity: Entity): void;
    hasVelocity(entity: Entity): boolean;
    getVelocity(entity: Entity): Velocity;
    addVelocity(entity: Entity, component: Velocity): void;
    removeVelocity(entity: Entity): void;

    // Hierarchy Utilities
    setParent(child: Entity, parent: Entity): void;
}

// Module
export interface ESEngineModule {
    Registry: new () => Registry;
    /**
     * Authoritative list of component names this WASM build exposes
     * on the Registry. Used by BuiltinBridge to detect drift between
     * the shipped SDK and the actual WASM module.
     */
    getBuiltinComponentNames(): string[];
    BitmapText: new () => BitmapText;
    BoxCollider: new () => BoxCollider;
    Camera: new () => Camera;
    Canvas: new () => Canvas;
    CapsuleCollider: new () => CapsuleCollider;
    Children: new () => Children;
    CircleCollider: new () => CircleCollider;
    FlexContainer: new () => FlexContainer;
    Interactable: new () => Interactable;
    Parent: new () => Parent;
    ParticleEmitter: new () => ParticleEmitter;
    RigidBody: new () => RigidBody;
    SegmentCollider: new () => SegmentCollider;
    ShapeRenderer: new () => ShapeRenderer;
    SpineAnimation: new () => SpineAnimation;
    Sprite: new () => Sprite;
    StateMachine: new () => StateMachine;
    StateVisuals: new () => StateVisuals;
    TilemapLayer: new () => TilemapLayer;
    Transform: new () => Transform;
    UIInteraction: new () => UIInteraction;
    UIMask: new () => UIMask;
    UINode: new () => UINode;
    UIVisual: new () => UIVisual;
    Velocity: new () => Velocity;
}
