// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (c) 2024-present ESEngine Team
//
// Auto-generated by EHT (native_functions) — DO NOT EDIT.
//
// The engine entry points a native (embedded-Dawn) host binds, named as the
// wasm module names them — so an SDK plugin calls `api.uiLayout_update(...)`
// and reaches whichever core is present. Generated from the SAME bindings
// headers embind registers from, so the two surfaces cannot drift.
//
// Every member is optional: a core answers what it compiles. Entry points that
// take a heap pointer are NOT here — those need a real backend that decides how
// bytes cross (see RendererBackend), not a name forwarded.

export interface NativeEngineApi {
    engine_setCpuProfiling?(on: boolean): void;
    getUINodeComputedHeight?(registry: unknown, entity: number): number;
    getUINodeComputedWidth?(registry: unknown, entity: number): number;
    getUINodeHiddenInTree?(registry: unknown, entity: number): boolean;
    gl_enableErrorCheck?(enabled: boolean): void;
    particle_getAliveCount?(entity: number): number;
    particle_play?(registry: unknown, entity: number): void;
    particle_reset?(registry: unknown, entity: number): void;
    particle_stop?(registry: unknown, entity: number): void;
    particle_update?(registry: unknown, dt: number): void;
    registry_getCanvasEntity?(registry: unknown): number;
    registry_getGeneration?(registry: unknown, entity: number): number;
    renderFrame?(registry: unknown, viewportWidth: number, viewportHeight: number): void;
    renderer_beginFrame?(elapsedSec: number): void;
    renderer_captureNextFrame?(): void;
    renderer_clearAllClipRects?(): void;
    renderer_clearAllStencilMasks?(): void;
    renderer_clearEntityClipRect?(entity: number): void;
    renderer_clearEntityStencilMask?(entity: number): void;
    renderer_createTarget?(width: number, height: number, flags: number): number;
    renderer_diagnose?(): void;
    renderer_end?(): void;
    renderer_flush?(): void;
    renderer_getCapturedCameraCount?(): number;
    renderer_getCapturedEntityCount?(): number;
    renderer_getCapturedFrameSize?(): number;
    renderer_getCulled?(): number;
    renderer_getDrawCalls?(): number;
    renderer_getGpuTimeMs?(): number;
    renderer_getMeshes?(): number;
    renderer_getPreviewHeight?(): number;
    renderer_getPreviewSize?(): number;
    renderer_getPreviewWidth?(): number;
    renderer_getSnapshotHeight?(): number;
    renderer_getSnapshotSize?(): number;
    renderer_getSnapshotWidth?(): number;
    renderer_getSpine?(): number;
    renderer_getSprites?(): number;
    renderer_getTargetDepthTexture?(handle: number): number;
    renderer_getTargetTexture?(handle: number): number;
    renderer_getText?(): number;
    renderer_getTextureBytes?(): number;
    renderer_getTriangles?(): number;
    renderer_hasCapturedData?(): boolean;
    renderer_init?(width: number, height: number): void;
    renderer_pollPreviewReadback?(): number;
    renderer_pollSnapshotReadback?(): number;
    renderer_releaseTarget?(handle: number): void;
    renderer_renderMaterialPreview?(materialId: number, w: number, h: number): void;
    renderer_replayToDrawCall?(drawCallIndex: number): void;
    renderer_resize?(width: number, height: number): void;
    renderer_setClearColor?(r: number, g: number, b: number, a: number): void;
    renderer_setColorSpace?(linear: number): void;
    renderer_setEntityClipRect?(entity: number, x: number, y: number, w: number, h: number): void;
    renderer_setEntityStencilMask?(entity: number, refValue: number): void;
    renderer_setEntityStencilTest?(entity: number, refValue: number): void;
    renderer_setStage?(stage: number): void;
    renderer_setTextureParams?(textureId: number, minFilter: number, magFilter: number, wrapS: number, wrapT: number): void;
    renderer_setViewport?(x: number, y: number, w: number, h: number): void;
    renderer_setYSortLayers?(mask: number): void;
    renderer_submitAll?(registry: unknown, skipFlags: number, vpX: number, vpY: number, vpW: number, vpH: number): void;
    renderer_submitBitmapText?(registry: unknown): void;
    renderer_submitParticles?(registry: unknown): void;
    renderer_submitShapes?(registry: unknown): void;
    renderer_submitSpine?(registry: unknown): void;
    renderer_submitSprites?(registry: unknown): void;
    renderer_submitUIElements?(registry: unknown): void;
    renderer_updateTransforms?(registry: unknown): void;
    trail_clear?(registry: unknown, entity: number): void;
    trail_update?(registry: unknown, dt: number): void;
    transform_patchPosition?(registry: unknown, entity: number, x: number, y: number, z: number): void;
    transform_update?(registry: unknown): void;
    uiFlexLayout_update?(registry: unknown): void;
    uiHitTest_getHitEntity?(): number;
    uiHitTest_getHitEntityPrev?(): number;
    uiHitTest_pick?(registry: unknown, worldX: number, worldY: number): number;
    uiHitTest_pickAll?(registry: unknown, worldX: number, worldY: number): number;
    uiHitTest_pickResult?(index: number): number;
    uiHitTest_update?(registry: unknown, mouseWorldX: number, mouseWorldY: number, mouseDown: boolean, mousePressed: boolean, mouseReleased: boolean): void;
    uiLayout_update?(registry: unknown, camLeft: number, camBottom: number, camRight: number, camTop: number, propertyDirty: boolean): void;
    uiNode_computedHeight?(registry: unknown, entity: number): number;
    uiNode_computedWidth?(registry: unknown, entity: number): number;
    uiRenderOrder_update?(registry: unknown): void;
    uiTree_markAllDirty?(): void;
    uiTree_markDirty?(entity: number): void;
    uiTree_markStructureDirty?(): void;
    ui_getRenderOrder?(registry: unknown, entity: number): number;
}

// Not forwarded (they take a heap pointer): mesh2d_setGeometry, particle_set_color_lut, particle_set_size_lut, registry_batchSyncPhysicsTransforms, renderFrameWithMatrix, renderer_begin, renderer_submitSpineBatch, renderer_submitSpineBatchByEntity, renderer_submitTextBatch.

/** Build the API over a host scope (the QuickJS global object; a plain object
 *  in tests). A name the host did not bind simply stays absent. */
export function createNativeEngineApi(
    scope: Record<string, unknown> = globalThis as unknown as Record<string, unknown>,
): NativeEngineApi {
    const api: Record<string, unknown> = {};
    const bind = (name: string, host: string, dropFirst: boolean): void => {
        const fn = scope[host];
        if (typeof fn !== 'function') return;
        const call = fn as (...a: unknown[]) => unknown;
        api[name] = dropFirst
            ? (_registry: unknown, ...args: unknown[]) => call(...args)
            : (...args: unknown[]) => call(...args);
    };
    bind('engine_setCpuProfiling', 'es_engine_setCpuProfiling', false);
    bind('getUINodeComputedHeight', 'es_getUINodeComputedHeight', true);
    bind('getUINodeComputedWidth', 'es_getUINodeComputedWidth', true);
    bind('getUINodeHiddenInTree', 'es_getUINodeHiddenInTree', true);
    bind('gl_enableErrorCheck', 'es_gl_enableErrorCheck', false);
    bind('particle_getAliveCount', 'es_particle_getAliveCount', false);
    bind('particle_play', 'es_particle_play', true);
    bind('particle_reset', 'es_particle_reset', true);
    bind('particle_stop', 'es_particle_stop', true);
    bind('particle_update', 'es_particle_update', true);
    bind('registry_getCanvasEntity', 'es_registry_getCanvasEntity', true);
    bind('registry_getGeneration', 'es_registry_getGeneration', true);
    bind('renderFrame', 'es_renderFrame', true);
    bind('renderer_beginFrame', 'es_renderer_beginFrame', false);
    bind('renderer_captureNextFrame', 'es_renderer_captureNextFrame', false);
    bind('renderer_clearAllClipRects', 'es_renderer_clearAllClipRects', false);
    bind('renderer_clearAllStencilMasks', 'es_renderer_clearAllStencilMasks', false);
    bind('renderer_clearEntityClipRect', 'es_renderer_clearEntityClipRect', false);
    bind('renderer_clearEntityStencilMask', 'es_renderer_clearEntityStencilMask', false);
    bind('renderer_createTarget', 'es_renderer_createTarget', false);
    bind('renderer_diagnose', 'es_renderer_diagnose', false);
    bind('renderer_end', 'es_renderer_end', false);
    bind('renderer_flush', 'es_renderer_flush', false);
    bind('renderer_getCapturedCameraCount', 'es_renderer_getCapturedCameraCount', false);
    bind('renderer_getCapturedEntityCount', 'es_renderer_getCapturedEntityCount', false);
    bind('renderer_getCapturedFrameSize', 'es_renderer_getCapturedFrameSize', false);
    bind('renderer_getCulled', 'es_renderer_getCulled', false);
    bind('renderer_getDrawCalls', 'es_renderer_getDrawCalls', false);
    bind('renderer_getGpuTimeMs', 'es_renderer_getGpuTimeMs', false);
    bind('renderer_getMeshes', 'es_renderer_getMeshes', false);
    bind('renderer_getPreviewHeight', 'es_renderer_getPreviewHeight', false);
    bind('renderer_getPreviewSize', 'es_renderer_getPreviewSize', false);
    bind('renderer_getPreviewWidth', 'es_renderer_getPreviewWidth', false);
    bind('renderer_getSnapshotHeight', 'es_renderer_getSnapshotHeight', false);
    bind('renderer_getSnapshotSize', 'es_renderer_getSnapshotSize', false);
    bind('renderer_getSnapshotWidth', 'es_renderer_getSnapshotWidth', false);
    bind('renderer_getSpine', 'es_renderer_getSpine', false);
    bind('renderer_getSprites', 'es_renderer_getSprites', false);
    bind('renderer_getTargetDepthTexture', 'es_renderer_getTargetDepthTexture', false);
    bind('renderer_getTargetTexture', 'es_renderer_getTargetTexture', false);
    bind('renderer_getText', 'es_renderer_getText', false);
    bind('renderer_getTextureBytes', 'es_renderer_getTextureBytes', false);
    bind('renderer_getTriangles', 'es_renderer_getTriangles', false);
    bind('renderer_hasCapturedData', 'es_renderer_hasCapturedData', false);
    bind('renderer_init', 'es_renderer_init', false);
    bind('renderer_pollPreviewReadback', 'es_renderer_pollPreviewReadback', false);
    bind('renderer_pollSnapshotReadback', 'es_renderer_pollSnapshotReadback', false);
    bind('renderer_releaseTarget', 'es_renderer_releaseTarget', false);
    bind('renderer_renderMaterialPreview', 'es_renderer_renderMaterialPreview', false);
    bind('renderer_replayToDrawCall', 'es_renderer_replayToDrawCall', false);
    bind('renderer_resize', 'es_renderer_resize', false);
    bind('renderer_setClearColor', 'es_renderer_setClearColor', false);
    bind('renderer_setColorSpace', 'es_renderer_setColorSpace', false);
    bind('renderer_setEntityClipRect', 'es_renderer_setEntityClipRect', false);
    bind('renderer_setEntityStencilMask', 'es_renderer_setEntityStencilMask', false);
    bind('renderer_setEntityStencilTest', 'es_renderer_setEntityStencilTest', false);
    bind('renderer_setStage', 'es_renderer_setStage', false);
    bind('renderer_setTextureParams', 'es_renderer_setTextureParams', false);
    bind('renderer_setViewport', 'es_renderer_setViewport', false);
    bind('renderer_setYSortLayers', 'es_renderer_setYSortLayers', false);
    bind('renderer_submitAll', 'es_renderer_submitAll', true);
    bind('renderer_submitBitmapText', 'es_renderer_submitBitmapText', true);
    bind('renderer_submitParticles', 'es_renderer_submitParticles', true);
    bind('renderer_submitShapes', 'es_renderer_submitShapes', true);
    bind('renderer_submitSpine', 'es_renderer_submitSpine', true);
    bind('renderer_submitSprites', 'es_renderer_submitSprites', true);
    bind('renderer_submitUIElements', 'es_renderer_submitUIElements', true);
    bind('renderer_updateTransforms', 'es_renderer_updateTransforms', true);
    bind('trail_clear', 'es_trail_clear', true);
    bind('trail_update', 'es_trail_update', true);
    bind('transform_patchPosition', 'es_transform_patchPosition', true);
    bind('transform_update', 'es_transform_update', true);
    bind('uiFlexLayout_update', 'es_uiFlexLayout_update', true);
    bind('uiHitTest_getHitEntity', 'es_uiHitTest_getHitEntity', false);
    bind('uiHitTest_getHitEntityPrev', 'es_uiHitTest_getHitEntityPrev', false);
    bind('uiHitTest_pick', 'es_uiHitTest_pick', true);
    bind('uiHitTest_pickAll', 'es_uiHitTest_pickAll', true);
    bind('uiHitTest_pickResult', 'es_uiHitTest_pickResult', false);
    bind('uiHitTest_update', 'es_uiHitTest_update', true);
    bind('uiLayout_update', 'es_uiLayout_update', true);
    bind('uiNode_computedHeight', 'es_uiNode_computedHeight', true);
    bind('uiNode_computedWidth', 'es_uiNode_computedWidth', true);
    bind('uiRenderOrder_update', 'es_uiRenderOrder_update', true);
    bind('uiTree_markAllDirty', 'es_uiTree_markAllDirty', false);
    bind('uiTree_markDirty', 'es_uiTree_markDirty', false);
    bind('uiTree_markStructureDirty', 'es_uiTree_markStructureDirty', false);
    bind('ui_getRenderOrder', 'es_ui_getRenderOrder', true);
    return api as NativeEngineApi;
}
