// Generates the built-in UI widget prefabs from the factories (single source)
// and verifies the captured tree. Writing the .esprefab files is the codegen;
// the assertions are the guard that the factory still round-trips to a prefab.
import { describe, it, expect, afterAll } from 'vitest';
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import type { World } from '../src/ecs/world';
import type { PrefabData } from '../src/prefab/types';
import { widgetToPrefab } from '../src/ui/widgets/toPrefab';
import { createButton } from '../src/ui/widgets/button';
import { createToggle } from '../src/ui/widgets/toggle';
import { createSlider } from '../src/ui/widgets/slider';
import { createProgress } from '../src/ui/widgets/progress';
import { createDropdown } from '../src/ui/widgets/dropdown';
import { createDialog } from '../src/ui/widgets/dialog';
import { createTextInput } from '../src/ui/widgets/text-input';
import { UISlider } from '../src/ui/behavior/slider';
import { UIToggle } from '../src/ui/behavior/toggle';
import { UIDropdown } from '../src/ui/behavior/dropdown';
import { registerComponent } from '../src/ecs/component';
import { spawnUIEntity } from '../src/ui/core/compose';
import { UIMask, MaskMode } from '../src/ui/core/ui-mask';
import { UIPositionType } from '../src/ui/core/ui-node';
import { Interactable } from '../src/ui/input/interactable';
import { themeColors } from '../src/ui/theme/tokens';
import { markThemed } from '../src/ui/theme/theme-style';
import { px } from '../src/ui/core/dimension';

const OUT_DIR = resolve(__dirname, '../src/ui/widgets/prefabs');
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const noEvents = { on: () => {} } as any;
const c = themeColors();

function entityById(p: PrefabData, id: string) {
    return p.entities.find((e) => e.prefabEntityId === id)!;
}
function typesOf(p: PrefabData, id: string): string[] {
    return entityById(p, id).components.map((cc) => cc.type);
}

const GENERATED: Record<string, PrefabData> = {};

function generate(name: string, build: (w: World) => number): PrefabData {
    const prefab = widgetToPrefab(build, name);
    mkdirSync(OUT_DIR, { recursive: true });
    writeFileSync(resolve(OUT_DIR, `${name}.esprefab`), JSON.stringify(prefab, null, 2) + '\n');
    GENERATED[name] = prefab;
    return prefab;
}

// Emit the SDK-exported data module the editor's "Create → UI" menu instantiates.
afterAll(() => {
    const names = Object.keys(GENERATED);
    const body =
        '// AUTO-GENERATED by tests/ui-widget-prefabs.gen.test.ts — do not edit by hand.\n' +
        "import type { PrefabData } from '../../../prefab/types';\n\n" +
        `export const BUILTIN_UI_PREFABS: Record<string, PrefabData> = ${JSON.stringify(GENERATED, null, 2)};\n\n` +
        `export const BUILTIN_UI_WIDGET_NAMES = ${JSON.stringify(names)} as const;\n`;
    writeFileSync(resolve(OUT_DIR, 'generated.ts'), body);
});

describe('UI widget prefab codegen', () => {
    it('Button: factory → prefab captures the full clickable tree + label', () => {
        const prefab = generate('Button', (world) =>
            // No explicit states/colors: the factory's theme defaults also tag the
            // entities with ThemeStyle roles, so the prefab re-themes at runtime.
            createButton({
                world, events: noEvents,
                node: { width: px(140), height: px(40) },
                text: { content: 'Button', fontSize: 14 },
            }).entity as unknown as number,
        );

        const root = typesOf(prefab, prefab.rootEntityId);
        expect(root).toEqual(expect.arrayContaining([
            'Transform', 'UINode', 'UIVisual', 'Interactable', 'Focusable', 'UIController', 'UIGear',
        ]));
        const rootEnt = entityById(prefab, prefab.rootEntityId);
        expect(rootEnt.children.length).toBe(1);
        const label = entityById(prefab, rootEnt.children[0]!);
        expect(label.components.map((x) => x.type)).toEqual(expect.arrayContaining(['UINode', 'Text']));
        expect(label.parent).toBe(prefab.rootEntityId);
    });

    it('Toggle: box + checkmark child, behavior in UIToggle', () => {
        registerComponent('UIToggle', UIToggle);
        const prefab = generate('Toggle', (world) =>
            createToggle({
                world, events: noEvents,
                node: { width: px(28), height: px(28) },
                isOn: true,
            }).entity as unknown as number,
        );
        expect(typesOf(prefab, prefab.rootEntityId)).toEqual(expect.arrayContaining(
            ['UINode', 'Interactable', 'UIGear', 'UIToggle']));
        const rootEnt = entityById(prefab, prefab.rootEntityId);
        const toggleComp = rootEnt.components.find((cc) => cc.type === 'UIToggle')!;
        // The check-indicator ref is remapped to a prefab-local id.
        expect(rootEnt.children).toContain(toggleComp.data.check);
    });

    it('Slider: track + fill + handle', () => {
        // The suite-wide beforeEach clears user components; capture-side entity
        // ref remapping resolves UISlider by name, so put it back (the behavior
        // plugin does this in a real app).
        registerComponent('UISlider', UISlider);
        const prefab = generate('Slider', (world) =>
            createSlider({
                world, events: noEvents, node: { width: px(200), height: px(18) },
                min: 0, max: 100, step: 1, value: 50, handleWidth: 14,
            }).entity as unknown as number,
        );
        expect(entityById(prefab, prefab.rootEntityId).children.length).toBe(2);
        // The behavior component rides along, with its intra-prefab entity refs
        // remapped to prefab-local ids — an editor-placed slider is functional.
        const sliderComp = entityById(prefab, prefab.rootEntityId).components
            .find((cc) => cc.type === 'UISlider')!;
        expect(sliderComp).toBeDefined();
        const kids = entityById(prefab, prefab.rootEntityId).children;
        expect(kids).toContain(sliderComp.data.fill);
        expect(kids).toContain(sliderComp.data.handle);
    });

    it('Dialog: backdrop scrim + panel, dismissal data-driven by UIDialog', () => {
        const prefab = generate('Dialog', (world) =>
            createDialog({
                world, events: noEvents,
                startHidden: false, // an editor-placed dialog should be visible
            }).entity as unknown as number,
        );
        expect(typesOf(prefab, prefab.rootEntityId)).toEqual(expect.arrayContaining([
            'UINode', 'UIVisual', 'Interactable', 'UIDialog',
        ]));
        const rootEnt = entityById(prefab, prefab.rootEntityId);
        expect(rootEnt.children.length).toBe(1);
        expect(typesOf(prefab, rootEnt.children[0]!)).toEqual(
            expect.arrayContaining(['UINode', 'UIVisual', 'Interactable']));
    });

    it('TextInput: an editable field over the SDF input plugin', () => {
        const prefab = generate('TextInput', (world) =>
            createTextInput({
                world, events: noEvents,
                placeholder: 'Text…',
            }).entity as unknown as number,
        );
        expect(typesOf(prefab, prefab.rootEntityId)).toEqual(expect.arrayContaining([
            'UINode', 'Interactable', 'Focusable', 'TextInput', 'ThemeStyle',
        ]));
    });

    it('Progress: track + fill', () => {
        const prefab = generate('Progress', (world) =>
            createProgress({
                world, node: { width: px(200), height: px(14) },
                value: 0.4,
            }).entity as unknown as number,
        );
        expect(entityById(prefab, prefab.rootEntityId).children.length).toBe(1);
    });

    it('Dropdown: button + label, options + selection in UIDropdown (popup is runtime-only)', () => {
        registerComponent('UIDropdown', UIDropdown);
        const prefab = generate('Dropdown', (world) =>
            createDropdown<string>({
                world, events: noEvents,
                node: { width: px(150), height: px(34) },
                options: ['One', 'Two', 'Three'], optionToLabel: (o) => o, optionHeight: 30,
            }).entity as unknown as number,
        );
        const rootEnt = entityById(prefab, prefab.rootEntityId);
        expect(typesOf(prefab, prefab.rootEntityId)).toEqual(expect.arrayContaining(
            ['UINode', 'Interactable', 'UIDropdown']));
        const ddComp = rootEnt.components.find((cc) => cc.type === 'UIDropdown')!;
        expect(ddComp.data.options).toEqual(['One', 'Two', 'Three']);
        expect(rootEnt.children).toContain(ddComp.data.label);
    });

    it('ListView: a clipped viewport shell (items are populated by createListView in code)', () => {
        const prefab = generate('ListView', (world) => {
            // The serializable half of createListView: a sized viewport with a
            // Scissor mask + a hover hit-target, plus a placeholder label. Data and
            // item rows are runtime-only — wire them with createListView in code.
            const viewport = spawnUIEntity({
                world,
                node: { width: px(240), height: px(320) },
                visual: { color: c.control },
            });
            markThemed(world, viewport, { visual: 'control' });
            world.insert(viewport, UIMask, { enabled: true, mode: MaskMode.Scissor });
            world.insert(viewport, Interactable, { enabled: true, blockRaycast: true, raycastTarget: true });
            const label = spawnUIEntity({
                world, parent: viewport,
                node: { fill: true },
                text: { content: 'List View', color: c.text, fontSize: 14 },
            });
            markThemed(world, label, { text: 'text' });
            return viewport as unknown as number;
        });
        expect(typesOf(prefab, prefab.rootEntityId)).toEqual(expect.arrayContaining([
            'UINode', 'UIVisual', 'UIMask', 'Interactable',
        ]));
        expect(entityById(prefab, prefab.rootEntityId).children.length).toBe(1);
    });

    it('ScrollView: a clipped scroll viewport shell (scroll model wired by createScrollView)', () => {
        const prefab = generate('ScrollView', (world) => {
            // The serializable half of createScrollView: a Scissor-masked viewport
            // + a hit-target + an absolutely-placed content frame (taller than the
            // window so there is something to scroll). The scroll model — wheel /
            // drag / kinetic fling — is runtime-only; wire it with createScrollView.
            const viewport = spawnUIEntity({
                world,
                node: { width: px(240), height: px(320) },
                visual: { color: c.control },
            });
            markThemed(world, viewport, { visual: 'control' });
            world.insert(viewport, UIMask, { enabled: true, mode: MaskMode.Scissor });
            world.insert(viewport, Interactable, { enabled: true, blockRaycast: true, raycastTarget: true });
            spawnUIEntity({
                world, parent: viewport,
                node: {
                    position: UIPositionType.Absolute,
                    insetLeft: px(0), insetTop: px(0), width: px(240), height: px(640),
                },
            });
            return viewport as unknown as number;
        });
        expect(typesOf(prefab, prefab.rootEntityId)).toEqual(expect.arrayContaining([
            'UINode', 'UIVisual', 'UIMask', 'Interactable',
        ]));
        expect(entityById(prefab, prefab.rootEntityId).children.length).toBe(1);
    });
});
