// Auto-generated by EHT (aot_components) — DO NOT EDIT.
// The type half of the AOT contract: a manifest names a component, and a
// compiled system needs the bytes. Regenerate with `pnpm eht`.
#include "esengine/aot/AotComponents.generated.hpp"

#include <cstdint>
#include <cstring>

#include "esengine/ecs/Entity.hpp"
#include "esengine/ecs/Registry.hpp"
#include "esengine/ecs/components/BitmapText.hpp"
#include "esengine/ecs/components/Collider2D.hpp"
#include "esengine/ecs/components/RigidBody3D.hpp"
#include "esengine/ecs/components/Camera.hpp"
#include "esengine/ecs/components/Canvas.hpp"
#include "esengine/ecs/components/Hierarchy.hpp"
#include "esengine/ecs/components/Draggable.hpp"
#include "esengine/ecs/components/DragonBonesAnimation.hpp"
#include "esengine/ecs/components/FlexContainer.hpp"
#include "esengine/ecs/components/Interactable.hpp"
#include "esengine/ecs/components/Light.hpp"
#include "esengine/ecs/components/MeshRenderer.hpp"
#include "esengine/ecs/components/ParticleEmitter.hpp"
#include "esengine/ecs/components/ParticleForceField.hpp"
#include "esengine/ecs/components/RigidBody2D.hpp"
#include "esengine/ecs/components/ShadowCaster2D.hpp"
#include "esengine/ecs/components/ShapeRenderer.hpp"
#include "esengine/ecs/components/SpineAnimation.hpp"
#include "esengine/ecs/components/Sprite.hpp"
#include "esengine/ecs/components/TilemapLayer.hpp"
#include "esengine/ecs/components/TrailRenderer.hpp"
#include "esengine/ecs/components/Transform.hpp"
#include "esengine/ecs/components/UIInteraction.hpp"
#include "esengine/ecs/components/UIMask.hpp"
#include "esengine/ecs/components/UINode.hpp"
#include "esengine/ecs/components/UIScroll.hpp"
#include "esengine/ecs/components/UIVisual.hpp"
#include "esengine/ecs/components/Velocity.hpp"

namespace esengine::aot {

ComponentAt engineComponentAt(ecs::Registry& registry, const char* name) {
    if (std::strcmp(name, "BitmapText") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::BitmapText>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "BoxCollider2D") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::BoxCollider2D>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "BoxCollider3D") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::BoxCollider3D>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "Camera") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::Camera>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "Canvas") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::Canvas>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "CapsuleCollider2D") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::CapsuleCollider2D>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "CapsuleCollider3D") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::CapsuleCollider3D>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "CharacterController3D") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::CharacterController3D>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "Children") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::Children>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "CircleCollider2D") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::CircleCollider2D>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "ConvexCollider3D") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::ConvexCollider3D>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "Draggable") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::Draggable>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "DragonBonesAnimation") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::DragonBonesAnimation>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "FlexContainer") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::FlexContainer>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "Interactable") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::Interactable>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "Light") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::Light>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "MeshCollider3D") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::MeshCollider3D>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "MeshRenderer") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::MeshRenderer>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "MeshSkin") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::MeshSkin>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "Parent") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::Parent>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "ParticleEmitter") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::ParticleEmitter>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "ParticleForceField") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::ParticleForceField>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "RigidBody2D") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::RigidBody2D>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "RigidBody3D") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::RigidBody3D>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "SegmentCollider2D") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::SegmentCollider2D>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "ShadowCaster2D") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::ShadowCaster2D>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "ShapeRenderer") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::ShapeRenderer>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "SphereCollider3D") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::SphereCollider3D>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "SpineAnimation") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::SpineAnimation>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "Sprite") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::Sprite>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "TilemapLayer") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::TilemapLayer>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "TrailRenderer") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::TrailRenderer>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "Transform") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::Transform>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "UIInteraction") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::UIInteraction>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "UIMask") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::UIMask>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "UINode") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::UINode>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "UIScroll") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::UIScroll>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "UIVisual") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::UIVisual>(Entity::fromRaw(raw));
        };
    }
    if (std::strcmp(name, "Velocity") == 0) {
        return [&registry](std::uint32_t raw) -> void* {
            return registry.tryGet<esengine::ecs::Velocity>(Entity::fromRaw(raw));
        };
    }
    return {};
}

bool isEngineComponent(const char* name) {
    if (std::strcmp(name, "BitmapText") == 0) return true;
    if (std::strcmp(name, "BoxCollider2D") == 0) return true;
    if (std::strcmp(name, "BoxCollider3D") == 0) return true;
    if (std::strcmp(name, "Camera") == 0) return true;
    if (std::strcmp(name, "Canvas") == 0) return true;
    if (std::strcmp(name, "CapsuleCollider2D") == 0) return true;
    if (std::strcmp(name, "CapsuleCollider3D") == 0) return true;
    if (std::strcmp(name, "CharacterController3D") == 0) return true;
    if (std::strcmp(name, "Children") == 0) return true;
    if (std::strcmp(name, "CircleCollider2D") == 0) return true;
    if (std::strcmp(name, "ConvexCollider3D") == 0) return true;
    if (std::strcmp(name, "Draggable") == 0) return true;
    if (std::strcmp(name, "DragonBonesAnimation") == 0) return true;
    if (std::strcmp(name, "FlexContainer") == 0) return true;
    if (std::strcmp(name, "Interactable") == 0) return true;
    if (std::strcmp(name, "Light") == 0) return true;
    if (std::strcmp(name, "MeshCollider3D") == 0) return true;
    if (std::strcmp(name, "MeshRenderer") == 0) return true;
    if (std::strcmp(name, "MeshSkin") == 0) return true;
    if (std::strcmp(name, "Parent") == 0) return true;
    if (std::strcmp(name, "ParticleEmitter") == 0) return true;
    if (std::strcmp(name, "ParticleForceField") == 0) return true;
    if (std::strcmp(name, "RigidBody2D") == 0) return true;
    if (std::strcmp(name, "RigidBody3D") == 0) return true;
    if (std::strcmp(name, "SegmentCollider2D") == 0) return true;
    if (std::strcmp(name, "ShadowCaster2D") == 0) return true;
    if (std::strcmp(name, "ShapeRenderer") == 0) return true;
    if (std::strcmp(name, "SphereCollider3D") == 0) return true;
    if (std::strcmp(name, "SpineAnimation") == 0) return true;
    if (std::strcmp(name, "Sprite") == 0) return true;
    if (std::strcmp(name, "TilemapLayer") == 0) return true;
    if (std::strcmp(name, "TrailRenderer") == 0) return true;
    if (std::strcmp(name, "Transform") == 0) return true;
    if (std::strcmp(name, "UIInteraction") == 0) return true;
    if (std::strcmp(name, "UIMask") == 0) return true;
    if (std::strcmp(name, "UINode") == 0) return true;
    if (std::strcmp(name, "UIScroll") == 0) return true;
    if (std::strcmp(name, "UIVisual") == 0) return true;
    if (std::strcmp(name, "Velocity") == 0) return true;
    return false;
}

}  // namespace esengine::aot
