// Auto-generated by EHT (aot_components) — DO NOT EDIT.
// The type half of the AOT contract: a manifest names a component, and a
// compiled system needs the bytes. Regenerate with `pnpm eht`.
#pragma once

#include "esengine/aot/AotHost.hpp"

namespace esengine::ecs { class Registry; }

namespace esengine::aot {

/**
 * Where a named ENGINE component lives, for this registry.
 *
 * `tryGet`, never `getOrEmplace`: a resolver that created the component
 * would give one to every entity the query walked, and a row is kept only
 * when every component resolves — the absence IS the filter.
 *
 * No lazily-derived field is refreshed, because the interpreted side does
 * not refresh one either and it is the oracle. A component whose fields are
 * stale until a method runs cannot be read by a compiled system at all, and
 * that is a subset question rather than a resolver one.
 *
 * An unknown name yields an EMPTY resolver: a project component lives in the
 * script pool and is not this table's to answer for. Call it and it throws,
 * so a caller must ask `isEngineComponent` first.
 */
ComponentAt engineComponentAt(ecs::Registry& registry, const char* name);

/** Whether this table answers for that name, without building a resolver. */
bool isEngineComponent(const char* name);

}  // namespace esengine::aot
