/* GENERATED by @estella/compiler — do not edit. */
/* What this engine is, for a host opening a compiled module. */
#pragma once

#include "esengine/aot/estella_abi.h"

/* One per address width, because the width is IN the digest: a host that
   took the other one would refuse every module built for it. */
#define ES_ENGINE_ABI_DIGEST_32 0x6aac26f71f4dcdf4ULL
#define ES_ENGINE_ABI_DIGEST_64 0xa8244cac94602de0ULL
#define ES_ENGINE_ABI_DIGEST \
    (sizeof(es_addr_t) == 8 ? ES_ENGINE_ABI_DIGEST_64 : ES_ENGINE_ABI_DIGEST_32)
