/* GENERATED by @estella/compiler — do not edit. */
/* The Estella ABI, C side. */
#ifndef ESTELLA_ABI_H
#define ESTELLA_ABI_H

#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <math.h>

/* A fused multiply-add is MORE accurate than the double rounding JS does, and
   more accurate is still a different number. GCC does not implement this pragma
   and warns about it, so the flag in CFLAGS is the one that has to be there. */
#if defined(__clang__)
#pragma STDC FP_CONTRACT OFF
#endif

/* An address is a POINTER, and on wasm32 a pointer IS a 32-bit offset into
   linear memory — which is why one emitted source serves both back ends. The
   OFFSETS below are the contract; the address width is the machine, and it is
   mixed into the handshake so a 32-bit artifact cannot load into a 64-bit host.

   ES_ADDR_BASE is the other model: a host that owns one block and addresses it
   by offset. A wasm2c deployment is one, and so is the differential
   harness. Same structs, same offsets, one word wider or narrower. */
#if defined(ES_ADDR_BASE)
typedef uint32_t es_addr_t;
extern unsigned char *es_memory;
#define ES_PTR(a) (es_memory + (a))
#else
typedef uintptr_t es_addr_t;
#define ES_PTR(a) ((unsigned char *)(a))
#endif

/* The packed rows the host materialised: for each row, the entity and
   then one base address per component the query named, in that order. */
typedef struct EsQueryRows {
    es_addr_t rows;
    es_addr_t count;
} EsQueryRows;

/* A command: four u32, sixteen bytes, at every address width. */
typedef struct EsCmd {
    uint32_t kind;
    uint32_t a;
    uint32_t b;
    uint32_t c;
} EsCmd;

#define ES_CMD_DESPAWN 1u
#define ES_CMD_REMOVE  2u

/* 6 addresses, and a number that needs a reason to grow. */
typedef struct EsSysCtx {
    es_addr_t queries;
    es_addr_t resources;
    es_addr_t cmdBuf;
    es_addr_t cmdCap;
    es_addr_t cmdCount;
    es_addr_t events;
} EsSysCtx;

/* What a host needs in order to CALL a system without glue written by hand.
   The compiler knows a system's queries and resources -- that is what _params
   is -- so it says so here rather than leaving each host to be told twice. */
typedef struct EsQueryDecl {
    const char *const *comps;   /* component names, in the order the query names them */
    const unsigned char *mut;   /* 1 where the system may write that component */
    uint32_t count;
} EsQueryDecl;

typedef struct EsSystemDecl {
    const char *name;
    void (*fn)(es_addr_t);
    const EsQueryDecl *queries;
    const char *const *resources;
    uint32_t queryCount;
    uint32_t resourceCount;
} EsSystemDecl;

/* The C and TS sides of these structs have ONE author, and a side that drifts
   from it must fail to compile. The numbers below are written by that author
   (compiler/src/abi.ts) into this file; these three declarations are how C says
   no if a struct above ever stops matching them. */
typedef char es_check_sysctx[sizeof(EsSysCtx) == 6 * sizeof(es_addr_t) ? 1 : -1];
typedef char es_check_rows[sizeof(EsQueryRows) == 2 * sizeof(es_addr_t) ? 1 : -1];
typedef char es_check_cmd[sizeof(EsCmd) == 4 * 4 ? 1 : -1];

/* memcpy, not a cast through a typed pointer: a component base is whatever the
   host handed over, and a wider load through an under-aligned pointer is
   undefined even where the hardware would have allowed it. */
static inline double es_f32(const unsigned char *p) { float v; memcpy(&v, p, 4); return (double)v; }
static inline void es_set_f32(unsigned char *p, double v) { float f = (float)v; memcpy(p, &f, 4); }
static inline double es_f64(const unsigned char *p) { double v; memcpy(&v, p, 8); return v; }
static inline void es_set_f64(unsigned char *p, double v) { memcpy(p, &v, 8); }

/* A bool in the C++ structs is ONE byte. Reading it as a float would read three
   bytes of whatever follows it, which is a value rather than an error. */
static inline int es_bool(const unsigned char *p) { return *p != 0; }
static inline void es_set_bool(unsigned char *p, int v) { *p = (unsigned char)(v ? 1 : 0); }

/* ---------------------------------------------------------------------------
   Math. Only the operations ECMAScript specifies EXACTLY are in the subset, but
   "exactly specified" is not the same as "what libm does" — three of them
   differ, and each difference is one bit of one pixel that would take a day to
   find. So each is written out rather than forwarded.
   --------------------------------------------------------------------------- */
static inline double es_abs(double x) { return fabs(x); }
static inline double es_floor(double x) { return floor(x); }
static inline double es_ceil(double x) { return ceil(x); }
static inline double es_trunc(double x) { return trunc(x); }
static inline double es_sqrt(double x) { return sqrt(x); }

/* Math.sign returns x itself for NaN and for both zeroes, so the sign of zero
   survives — and the sign of zero is a distinct bit pattern in the image. */
static inline double es_sign(double x) {
    if (isnan(x) || x == 0.0) return x;
    return x > 0.0 ? 1.0 : -1.0;
}

/* C's round() breaks ties AWAY from zero; ECMAScript breaks them toward +Inf.
   And floor(x + 0.5) — the usual fix — is wrong for the double just below 0.5,
   where the addition itself rounds up to 1. Subtracting the floor is exact for
   every finite x, so the comparison sees the true fraction. */
static inline double es_round(double x) {
    if (!isfinite(x) || x == 0.0) return x;
    double f = floor(x);
    double r = (x - f) < 0.5 ? f : f + 1.0;
    /* Math.round(-0.2) is -0, and -0 is not the same bytes as +0. */
    return (r == 0.0 && x < 0.0) ? -0.0 : r;
}

/* fmin/fmax return the non-NaN operand and are free to pick either zero;
   Math.min/max propagate NaN and distinguish -0 from +0. */
static inline double es_min(double a, double b) {
    if (isnan(a) || isnan(b)) return (double)NAN;
    if (a == b) return signbit(a) ? a : b;
    return a < b ? a : b;
}
static inline double es_max(double a, double b) {
    if (isnan(a) || isnan(b)) return (double)NAN;
    if (a == b) return signbit(a) ? b : a;
    return a > b ? a : b;
}

/* JS % on doubles is the truncated remainder, which is fmod. */
static inline double es_rem(double a, double b) { return fmod(a, b); }

#endif /* ESTELLA_ABI_H */
