// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (c) 2024-present ESEngine Team
/**
 * @file  Per-vendor mini-game export profile.
 *
 * The export pipeline (exportMiniGame.ts) is shared by every mini-game vendor
 * (WeChat, Douyin, …): cook → manifest → scene transform → side-module scan →
 * bundle → emit config/entry → copy runtime. Only the vendor-specific emission
 * (config files, entry template) and the packaging suffix policy vary, and those
 * live here as DATA + two small emit hooks.
 *
 * Adding a vendor = one profile object, not a fork of the pipeline.
 */
import { WECHAT_MODULE_BUILD_TARGET } from '../bundle/sideModuleScan';
import type { RuntimeHost } from '../bundle/runtimeHosts';
import type { SizeBudget } from '../project/sizeBudget';

/**
 * A mini-game vendor's id. Open on purpose: the value is identity — the cook's
 * per-platform Import Settings key, the export result's `platform`, diagnostics
 * — and nothing in the pipeline branches on it, so a vendor the editor does not
 * ship can still be exported by handing {@link exportMiniGame} a profile.
 * Mirrors the SDK's `MiniGameVendor` (sdk/src/platform/minigame/api.ts).
 */
export type MiniGameVendor = 'wechat' | 'douyin' | (string & {});

/** Vendor-neutral facts the pipeline computes, handed to the config emitter. */
export interface MiniGameConfigContext {
    title: string;
    appid: string;
    orientation: 'portrait' | 'landscape';
    /** Lazy groups present in the cook, as vendor subpackage roots. */
    subPackages: ReadonlyArray<{ name: string; root: string }>;
    /** Custom suffixes the cook staged that need an explicit packer include rule. */
    includeSuffixes: string[];
    /** Whether this export actually bundled an open data context. Declaring one
     *  that is not there fails the host's compile, so the config names the
     *  directory only when the directory exists. */
    hasOpenData: boolean;
    /** Where it was bundled — {@link OPEN_DATA_DIR}, handed in rather than read
     *  from a constant so a project-authored profile emits the same name the
     *  pipeline actually wrote to. */
    openDataRoot: string;
}

/**
 * The directory an open data context is authored in and bundled to.
 *
 * A family constant, not vendor data: the hosts that have this capability let
 * the game pick the name, so the only thing a vendor could contribute is a
 * different arbitrary string. It is the same on both sides — `<project>/open-data/`
 * in, `<package>/open-data/` out — so there is one name to know.
 */
export const OPEN_DATA_DIR = 'open-data';

/** Vendor-neutral facts the pipeline computes, handed to the entry emitter. */
export interface MiniGameEntryContext {
    /** Optional modules the shipped scenes need (physics/spine/basis/videodec). */
    sideModules: ReadonlyArray<{ id: string; file: string }>;
    /** The engine glue filename staged into wasm/ (esengine.wxgame.js | esengine.js). */
    engineGlueFile: string;
    /** Package-relative directory those artifacts landed in, decided by the
     *  export's runtime layout. The entry asks for them WHERE THEY ARE. */
    runtimeDir: string;
    /** The host's API global (`wx` / `tt`), from the profile; null when the
     *  vendor did not say, in which case nothing is subpackaged. */
    hostGlobal: string | null;
    /** The 分包 holding the engine binary, when it is in one: the entry has to
     *  ask the host for it before booting, since the file is not in the package
     *  until then. Null when the binary ships in the main package. */
    engineSubpackage: string | null;
}

/**
 * The generated mini-game entry: require the engine glue + each side module,
 * then boot the bundle. Pure CommonJS with no vendor API in it — every host
 * loads JS the same way — so this is the family default, and a profile only
 * overrides it for an unusual loader.
 */
export function defaultMiniGameEntry(ctx: MiniGameEntryContext): string {
    const requires = ctx.sideModules
        .map((m) => `  ${JSON.stringify(m.id)}: asFactory(require('./${ctx.runtimeDir}/${m.file}.js')),`)
        .join('\n');
    const boot = `const asFactory = (m) => (typeof m === 'function' ? m : (m && m.default) || m);
const engineFactory = asFactory(require('./${ctx.runtimeDir}/${ctx.engineGlueFile}'));
const sideModuleFactories = {
${requires}
};
const bundle = require('./game-bundle.js');
bundle.boot(engineFactory, sideModuleFactories);`;
    if (!ctx.engineSubpackage) {
        return `'use strict';
// Generated by Estella exportGame (MiniGame entry).
${boot}
`;
    }
    // The host fetches the engine binary before anything can instantiate it, and
    // this runs BEFORE the bundle is parsed, so the runtime's own indicator
    // cannot cover the wait. Real byte progress, unlike every later stage.
    return `'use strict';
// Generated by Estella exportGame (MiniGame entry, engine in a subpackage).
var __g = ${ctx.hostGlobal};
__g.showLoading({ title: 'Fetching the engine 0%', mask: true });
var __task = __g.loadSubpackage({
  name: ${JSON.stringify(ctx.engineSubpackage)},
  success() {
${boot.split('\n').map((l) => (l ? `    ${l}` : l)).join('\n')}
  },
  fail(err) {
    __g.hideLoading();
    console.error('[estella] the engine subpackage ${ctx.engineSubpackage} did not load — the game cannot start', err);
  },
});
// Optional on the host: a version without it leaves the 0% notice up, which is
// still a package that says it is doing something.
if (__task && __task.onProgressUpdate) {
  __task.onProgressUpdate(function (p) {
    __g.showLoading({ title: 'Fetching the engine ' + Math.round(p.progress || 0) + '%', mask: true });
  });
}
`;
}

export interface MiniGameExportProfile {
    /** Vendor identity — the export result's `platform` + diagnostics. */
    readonly id: MiniGameVendor;
    /** SDK dist entry the bundle aliases `esengine` to (index.wechat.js). */
    readonly sdkEntryFile: string;
    /**
     * The same entry with no optional subsystems, when the vendor's SDK build has
     * one. An export that knows which subsystems its content uses takes this and
     * imports those back, so the package carries no others. Absent = always the
     * whole entry.
     */
    readonly sdkLeanEntryFile?: string;
    /** Runtime bootstrap fn imported from 'esengine' in the generated boot. */
    readonly runtimeInit: string;
    /**
     * An SDK export the generated entry CALLS before `runtimeInit` to install
     * the platform. A vendor whose SDK entry installs it as a module side
     * effect has no answer here that survives a bundler: the WeChat package
     * booted to "Platform not initialized" for exactly that reason.
     */
    readonly platformInit?: string;
    /** Engine glue filenames to look for in wasmDir, in preference order. */
    readonly engineGlueCandidates: readonly string[];
    /** esbuild target for the game bundle + glue down-level (real-device syntax floor). */
    readonly esTarget: 'es2017' | 'es2019' | 'es2020';
    /** Build-target name woven into "runtime not found" errors (`build -t <hint>`). */
    readonly wasmBuildHint: string;
    /** side-module id → the `build -t <target>` that produces it for THIS vendor.
     *  The optional modules (physics/basis/videodec/spine) are built per vendor
     *  runtime, so the "module missing" guidance cannot be a shared constant. */
    readonly sideModuleBuildTargets: Readonly<Record<string, string>>;
    /** Extensions the packer handles natively (no packOptions.include needed). */
    readonly nativeSuffixes: ReadonlySet<string>;
    /**
     * Every extension this host's packer will UPLOAD; anything staged outside it
     * ships as `<name>.<ext>.bin` (`unwrapRestagedPath` reads through that).
     * Null ⇒ no published list, so the package is staged exactly as cooked.
     * A list, not the known failures: an upload rule refuses where nobody looks.
     */
    readonly packerSuffixes: ReadonlySet<string> | null;
    /**
     * The global this host exposes its API on: `wx` for WeChat, `tt` for Douyin.
     * Taking it from the profile keeps the shared entry free of any vendor's
     * name; null means nothing can be subpackaged, there being nothing to ask.
     */
    readonly hostGlobal: string | null;
    /**
     * Whether this vendor's loader takes a `.wasm.br` path — a CAPABILITY;
     * spending the build time is `packaging.compressWasm`. WeChat's
     * `WXWebAssembly.instantiate` accepts one from base library 2.14.0, a floor
     * documented rather than probed: the loader cannot be asked.
     */
    readonly wasmBrotli: boolean;
    /** Subpackage root prefix (files stage under `<subpackageDir>/<name>/`). */
    readonly subpackageDir: string;
    /**
     * The entry script a subpackage root must carry, or absent when the vendor
     * asks for none. WeChat refuses to compile a 分包 whose root has no
     * `game.js` — a root full of assets and no entry is not a subpackage to it,
     * and the message names the missing FILE rather than the rule.
     */
    readonly subpackageEntry?: string;

    /**
     * What this host refuses to accept — the main package cap, the all-in cap.
     *
     * Every mini-game host has these limits and each states them differently, so
     * they are DATA like everything else here: a vendor the editor does not ship
     * declares its own and the build dialog reports it exactly as it reports
     * WeChat's. Built-in vendors leave this absent — their limits are the
     * platform's rule, not the export's, and live in
     * `src/project/sizeBudget.ts` where the settings UI can read them without
     * loading an export profile.
     */
    readonly sizeBudgets?: readonly SizeBudget[];

    /**
     * Absolute path of a module whose DEFAULT EXPORT is the runtime
     * `MiniGameProfile` — the host global plus any capability this vendor
     * overrides (its own video decoder, audio backend, socket, wasm loader).
     *
     * A vendor has two halves: this file describes PACKAGING, and that module
     * describes the RUNTIME. The built-in WeChat entry installs its own platform
     * on import, so it needs none; a project platform boots through
     * `esengine/minigame`, which deliberately installs nothing until the game
     * names a host — so the generated entry installs this one before booting.
     * Absent ⇒ the game is expected to install a platform itself.
     */
    readonly runtimeProfileModule?: string;

    /**
     * The same thing for a BUILT-IN vendor, whose profile module ships with the
     * pipeline rather than living in a project: a name out of RUNTIME_HOSTS,
     * resolved against the export's hostsDir. Declaring the path directly would
     * be wrong in a packaged editor, which bundles those sources elsewhere.
     */
    readonly runtimeProfileHost?: RuntimeHost;

    /** Emit the vendor config files (game.json + project.config.json). */
    emitConfigFiles(ctx: MiniGameConfigContext): Array<{ file: string; content: string }>;
    /** Emit the MiniGame entry the host runs (game.js). */
    emitEntry(ctx: MiniGameEntryContext): string;
}

// =============================================================================
// WeChat profile
// =============================================================================

/** WeChat's published code-package suffix whitelist (the "文件类型" table). */
const WECHAT_PACKER_SUFFIXES: ReadonlySet<string> = new Set(`png jpg jpeg gif svg js json cer obj dae fbx mtl stl 3ds mp3 pvr wav plist ttf fnt gz ccz m4a
    mp4 bmp atlas swf ani part proto bin sk mipmaps txt zip tt map ogg silk dbbin dbmv etc lmat lm
    ls lh lani lav lsani ltc aac astc br csv cur dat dds glb gltf ico ktx lmani lml pkm prefab
    scene wasm xml`.split(/\s+/).filter(Boolean));

export const wechatExportProfile: MiniGameExportProfile = {
    id: 'wechat',
    // The bundle aliases `esengine` → <sdkDir>/index.wechat.js (the wechat SDK build).
    sdkEntryFile: 'index.wechat.js',
    sdkLeanEntryFile: 'index.wechat.lean.js',
    runtimeInit: 'initWeChatRuntime',
    platformInit: 'initWeChatPlatform',
    // Require by the ACTUAL name in the wasm dir: the -t wechat build emits
    // esengine.wxgame.js; a web-aligned build, esengine.js.
    engineGlueCandidates: ['esengine.wxgame.js', 'esengine.js'],
    // Real-device WeChat rejects es2020 syntax (`??`, `?.`) even though devtools
    // accepts it; es2017 down-levels those while keeping async/await.
    esTarget: 'es2017',
    wasmBuildHint: 'wechat',
    hostGlobal: 'wx',
    sideModuleBuildTargets: WECHAT_MODULE_BUILD_TARGET,
    // Script + config WeChat's packer compiles itself; every OTHER staged custom
    // extension needs a packOptions.include rule (fs reads are otherwise denied).
    nativeSuffixes: new Set(['.js', '.json']),
    // developers.weixin.qq.com/minigame/dev/guide/base-ability/code-package.html,
    // "文件类型": only these may be uploaded.
    packerSuffixes: WECHAT_PACKER_SUFFIXES,
    // developers.weixin.qq.com/minigame/dev/framework/performance/wasm.html:
    // `WXWebAssembly.instantiate(path)` takes 「.wasm 和 .wasm.br」 from base library
    // 2.14.0 — and a package whose engine is one, in a subpackage, plays in devtools.
    wasmBrotli: true,
    subpackageDir: 'subpackages',
    subpackageEntry: 'game.js',

    emitConfigFiles(ctx) {
        const gameCfg: Record<string, unknown> = {
            deviceOrientation: ctx.orientation,
            showStatusBar: false,
        };
        // 开放数据域: named ONLY when this export bundled one. WeChat compiles
        // the directory the key points at, so declaring an absent context is a
        // build failure rather than a feature nobody uses.
        if (ctx.hasOpenData) {
            gameCfg.openDataContext = ctx.openDataRoot;
        }
        // WeChat 分包: each lazy group is a subpackage rooted at subpackages/<name>/.
        // The game calls Assets.loadGroup(name) → wx.loadSubpackage at runtime.
        if (ctx.subPackages.length > 0) {
            gameCfg.subPackages = ctx.subPackages.map((s) => ({ name: s.name, root: s.root }));
        }

        const projectCfg: Record<string, unknown> = {
            miniprogramRoot: './',
            projectname: ctx.title,
            appid: ctx.appid, // set in Project Settings → Packaging → WeChat (else fill in devtools)
            // bigPackageSizeSupport: devtools preview of a >4MB main package (upload
            // still enforces the limit — move heavy content to subpackages/ to ship).
            setting: { es6: false, minified: false, bigPackageSizeSupport: true },
            compileType: 'game',
            ...(ctx.includeSuffixes.length > 0
                ? { packOptions: { include: ctx.includeSuffixes.map((value) => ({ type: 'suffix', value })) } }
                : {}),
        };

        return [
            { file: 'game.json', content: JSON.stringify(gameCfg, null, 2) + '\n' },
            { file: 'project.config.json', content: JSON.stringify(projectCfg, null, 2) + '\n' },
        ];
    },

    emitEntry: defaultMiniGameEntry,
};

// =============================================================================
// Douyin profile
// =============================================================================

/**
 * Douyin (抖音) as a packaging profile. No SDK entry of its own — it goes through
 * the door a project vendor uses, `runtimeProfileHost`. A packer whitelist,
 * `.wasm.br` and a host wasm loader stay off until a device settles them:
 * claiming one early builds clean and fails at upload or at boot.
 */
export const douyinExportProfile: MiniGameExportProfile = {
    id: 'douyin',
    sdkEntryFile: 'index.minigame.js',
    runtimeInit: 'initMiniGameRuntime',
    runtimeProfileHost: 'douyinPlatformProfile',
    // No Douyin-specific engine build: the web artifact is what a `tt` host runs.
    engineGlueCandidates: ['esengine.js'],
    // Same floor as WeChat until a device says otherwise — down-levelling costs
    // nothing and a syntax error on a phone costs a release.
    esTarget: 'es2017',
    wasmBuildHint: 'web',
    hostGlobal: 'tt',
    sideModuleBuildTargets: {},
    // Assumed to match WeChat, not read from a Douyin doc: script and config are
    // what a mini-game packer compiles itself everywhere this checkout has looked.
    // Wrong here means a staged file the runtime cannot read, on a device.
    nativeSuffixes: new Set(['.js', '.json']),
    // No published list this checkout can cite, so nothing is restaged: staging a
    // file under a name the packer does not take is the failure that only shows at
    // upload, and inventing the list would be that failure with extra steps.
    packerSuffixes: null,
    // Not claimed until a device says it: `.wasm.br` is WeChat's documented path,
    // and shipping only the compressed file to a host that cannot read it is a
    // package that builds clean and never boots.
    wasmBrotli: false,
    subpackageDir: 'subpackages',
    subpackageEntry: 'game.js',

    emitConfigFiles(ctx) {
        const gameCfg: Record<string, unknown> = {
            deviceOrientation: ctx.orientation,
            showStatusBar: false,
        };
        if (ctx.subPackages.length > 0) {
            gameCfg.subPackages = ctx.subPackages.map((s) => ({ name: s.name, root: s.root }));
        }
        const projectCfg: Record<string, unknown> = {
            miniprogramRoot: './',
            projectname: ctx.title,
            appid: ctx.appid,
            compileType: 'game',
        };
        // `project.config.json`, the same name WeChat uses: the vendor's own CLI
        // (tt-minigame-ide-cli) and its Godot adaptation doc both name that file,
        // and nothing published names `project.tt.json`.
        return [
            { file: 'game.json', content: JSON.stringify(gameCfg, null, 2) + '\n' },
            { file: 'project.config.json', content: JSON.stringify(projectCfg, null, 2) + '\n' },
        ];
    },

    emitEntry: defaultMiniGameEntry,
};
