/**
 * @file    animTargets.generated.ts
 * @brief   Auto-generated animation target mappings
 * @details Generated by EHT - DO NOT EDIT
 */

export enum AnimTargetField {
    BitmapTextColorR = 0,
    BitmapTextColorG = 1,
    BitmapTextColorB = 2,
    BitmapTextColorA = 3,
    CameraOrthoSize = 4,
    SpriteColorR = 5,
    SpriteColorG = 6,
    SpriteColorB = 7,
    SpriteColorA = 8,
    SpriteSizeX = 9,
    SpriteSizeY = 10,
    TransformPositionX = 11,
    TransformPositionY = 12,
    TransformPositionZ = 13,
    TransformRotationZ = 14,
    TransformScaleX = 15,
    TransformScaleY = 16,
    TransformScaleZ = 17,
    UIRectAnchorMinX = 18,
    UIRectAnchorMinY = 19,
    UIRectAnchorMaxX = 20,
    UIRectAnchorMaxY = 21,
    UIRectOffsetMinX = 22,
    UIRectOffsetMinY = 23,
    UIRectOffsetMaxX = 24,
    UIRectOffsetMaxY = 25,
    UIRectPivotX = 26,
    UIRectPivotY = 27,
    UIRendererColorR = 28,
    UIRendererColorG = 29,
    UIRendererColorB = 30,
    UIRendererColorA = 31,
    CustomField = 32,
}

export enum AnimTargetComponent {
    BitmapText = 0,
    Camera = 1,
    Sprite = 2,
    Transform = 3,
    UIRect = 4,
    UIRenderer = 5,
    Custom = 6,
}

export const FIELD_MAP: Record<string, Record<string, AnimTargetField>> = {
    BitmapText: {
        'color.r': AnimTargetField.BitmapTextColorR,
        'color.g': AnimTargetField.BitmapTextColorG,
        'color.b': AnimTargetField.BitmapTextColorB,
        'color.a': AnimTargetField.BitmapTextColorA,
    },
    Camera: {
        'orthoSize': AnimTargetField.CameraOrthoSize,
    },
    Sprite: {
        'color.r': AnimTargetField.SpriteColorR,
        'color.g': AnimTargetField.SpriteColorG,
        'color.b': AnimTargetField.SpriteColorB,
        'color.a': AnimTargetField.SpriteColorA,
        'size.x': AnimTargetField.SpriteSizeX,
        'size.y': AnimTargetField.SpriteSizeY,
    },
    Transform: {
        'position.x': AnimTargetField.TransformPositionX,
        'position.y': AnimTargetField.TransformPositionY,
        'position.z': AnimTargetField.TransformPositionZ,
        'rotation.z': AnimTargetField.TransformRotationZ,
        'scale.x': AnimTargetField.TransformScaleX,
        'scale.y': AnimTargetField.TransformScaleY,
        'scale.z': AnimTargetField.TransformScaleZ,
    },
    UIRect: {
        'anchorMin.x': AnimTargetField.UIRectAnchorMinX,
        'anchorMin.y': AnimTargetField.UIRectAnchorMinY,
        'anchorMax.x': AnimTargetField.UIRectAnchorMaxX,
        'anchorMax.y': AnimTargetField.UIRectAnchorMaxY,
        'offsetMin.x': AnimTargetField.UIRectOffsetMinX,
        'offsetMin.y': AnimTargetField.UIRectOffsetMinY,
        'offsetMax.x': AnimTargetField.UIRectOffsetMaxX,
        'offsetMax.y': AnimTargetField.UIRectOffsetMaxY,
        'pivot.x': AnimTargetField.UIRectPivotX,
        'pivot.y': AnimTargetField.UIRectPivotY,
    },
    UIRenderer: {
        'color.r': AnimTargetField.UIRendererColorR,
        'color.g': AnimTargetField.UIRendererColorG,
        'color.b': AnimTargetField.UIRendererColorB,
        'color.a': AnimTargetField.UIRendererColorA,
    },
};

export const COMPONENT_MAP: Record<string, AnimTargetComponent> = {
    BitmapText: AnimTargetComponent.BitmapText,
    Camera: AnimTargetComponent.Camera,
    Sprite: AnimTargetComponent.Sprite,
    Transform: AnimTargetComponent.Transform,
    UIRect: AnimTargetComponent.UIRect,
    UIRenderer: AnimTargetComponent.UIRenderer,
};
