/**
 * @file    animTargets.generated.ts
 * @brief   Auto-generated animation target mappings
 * @details Generated by EHT - DO NOT EDIT
 */

export enum AnimTargetField {
    UIRectAnchorMinX = 0,
    UIRectAnchorMinY = 1,
    UIRectAnchorMaxX = 2,
    UIRectAnchorMaxY = 3,
    UIRectOffsetMinX = 4,
    UIRectOffsetMinY = 5,
    UIRectOffsetMaxX = 6,
    UIRectOffsetMaxY = 7,
    UIRectPivotX = 8,
    UIRectPivotY = 9,
    TransformPositionX = 10,
    TransformPositionY = 11,
    TransformPositionZ = 12,
    TransformRotationZ = 13,
    TransformScaleX = 14,
    TransformScaleY = 15,
    TransformScaleZ = 16,
    UIRendererColorR = 17,
    UIRendererColorG = 18,
    UIRendererColorB = 19,
    UIRendererColorA = 20,
    BitmapTextColorR = 21,
    BitmapTextColorG = 22,
    BitmapTextColorB = 23,
    BitmapTextColorA = 24,
    SpriteColorR = 25,
    SpriteColorG = 26,
    SpriteColorB = 27,
    SpriteColorA = 28,
    SpriteSizeX = 29,
    SpriteSizeY = 30,
    CameraOrthoSize = 31,
    CustomField = 32,
}

export enum AnimTargetComponent {
    UIRect = 0,
    Transform = 1,
    UIRenderer = 2,
    BitmapText = 3,
    Sprite = 4,
    Camera = 5,
    Custom = 6,
}

export const FIELD_MAP: Record<string, Record<string, AnimTargetField>> = {
    UIRect: {
        'anchorMin.x': AnimTargetField.UIRectAnchorMinX,
        'anchorMin.y': AnimTargetField.UIRectAnchorMinY,
        'anchorMax.x': AnimTargetField.UIRectAnchorMaxX,
        'anchorMax.y': AnimTargetField.UIRectAnchorMaxY,
        'offsetMin.x': AnimTargetField.UIRectOffsetMinX,
        'offsetMin.y': AnimTargetField.UIRectOffsetMinY,
        'offsetMax.x': AnimTargetField.UIRectOffsetMaxX,
        'offsetMax.y': AnimTargetField.UIRectOffsetMaxY,
        'pivot.x': AnimTargetField.UIRectPivotX,
        'pivot.y': AnimTargetField.UIRectPivotY,
    },
    Transform: {
        'position.x': AnimTargetField.TransformPositionX,
        'position.y': AnimTargetField.TransformPositionY,
        'position.z': AnimTargetField.TransformPositionZ,
        'rotation.z': AnimTargetField.TransformRotationZ,
        'scale.x': AnimTargetField.TransformScaleX,
        'scale.y': AnimTargetField.TransformScaleY,
        'scale.z': AnimTargetField.TransformScaleZ,
    },
    UIRenderer: {
        'color.r': AnimTargetField.UIRendererColorR,
        'color.g': AnimTargetField.UIRendererColorG,
        'color.b': AnimTargetField.UIRendererColorB,
        'color.a': AnimTargetField.UIRendererColorA,
    },
    BitmapText: {
        'color.r': AnimTargetField.BitmapTextColorR,
        'color.g': AnimTargetField.BitmapTextColorG,
        'color.b': AnimTargetField.BitmapTextColorB,
        'color.a': AnimTargetField.BitmapTextColorA,
    },
    Sprite: {
        'color.r': AnimTargetField.SpriteColorR,
        'color.g': AnimTargetField.SpriteColorG,
        'color.b': AnimTargetField.SpriteColorB,
        'color.a': AnimTargetField.SpriteColorA,
        'size.x': AnimTargetField.SpriteSizeX,
        'size.y': AnimTargetField.SpriteSizeY,
    },
    Camera: {
        'orthoSize': AnimTargetField.CameraOrthoSize,
    },
};

export const COMPONENT_MAP: Record<string, AnimTargetComponent> = {
    UIRect: AnimTargetComponent.UIRect,
    Transform: AnimTargetComponent.Transform,
    UIRenderer: AnimTargetComponent.UIRenderer,
    BitmapText: AnimTargetComponent.BitmapText,
    Sprite: AnimTargetComponent.Sprite,
    Camera: AnimTargetComponent.Camera,
};
