/**
 * @file    animTargets.generated.ts
 * @brief   Auto-generated animation target mappings
 * @details Generated by EHT - DO NOT EDIT
 */

export enum AnimTargetField {
    BitmapTextColorR = 0,
    BitmapTextColorG = 1,
    BitmapTextColorB = 2,
    BitmapTextColorA = 3,
    CameraOrthoSize = 4,
    SpriteColorR = 5,
    SpriteColorG = 6,
    SpriteColorB = 7,
    SpriteColorA = 8,
    SpriteSizeX = 9,
    SpriteSizeY = 10,
    TilemapLayerTintColorR = 11,
    TilemapLayerTintColorG = 12,
    TilemapLayerTintColorB = 13,
    TilemapLayerTintColorA = 14,
    TilemapLayerOpacity = 15,
    TransformPositionX = 16,
    TransformPositionY = 17,
    TransformPositionZ = 18,
    TransformRotationZ = 19,
    TransformScaleX = 20,
    TransformScaleY = 21,
    TransformScaleZ = 22,
    UIRectAnchorMinX = 23,
    UIRectAnchorMinY = 24,
    UIRectAnchorMaxX = 25,
    UIRectAnchorMaxY = 26,
    UIRectOffsetMinX = 27,
    UIRectOffsetMinY = 28,
    UIRectOffsetMaxX = 29,
    UIRectOffsetMaxY = 30,
    UIRectPivotX = 31,
    UIRectPivotY = 32,
    UIRendererColorR = 33,
    UIRendererColorG = 34,
    UIRendererColorB = 35,
    UIRendererColorA = 36,
    CustomField = 37,
}

export enum AnimTargetComponent {
    BitmapText = 0,
    Camera = 1,
    Sprite = 2,
    TilemapLayer = 3,
    Transform = 4,
    UIRect = 5,
    UIRenderer = 6,
    Custom = 7,
}

export const FIELD_MAP: Record<string, Record<string, AnimTargetField>> = {
    BitmapText: {
        'color.r': AnimTargetField.BitmapTextColorR,
        'color.g': AnimTargetField.BitmapTextColorG,
        'color.b': AnimTargetField.BitmapTextColorB,
        'color.a': AnimTargetField.BitmapTextColorA,
    },
    Camera: {
        'orthoSize': AnimTargetField.CameraOrthoSize,
    },
    Sprite: {
        'color.r': AnimTargetField.SpriteColorR,
        'color.g': AnimTargetField.SpriteColorG,
        'color.b': AnimTargetField.SpriteColorB,
        'color.a': AnimTargetField.SpriteColorA,
        'size.x': AnimTargetField.SpriteSizeX,
        'size.y': AnimTargetField.SpriteSizeY,
    },
    TilemapLayer: {
        'tintColor.r': AnimTargetField.TilemapLayerTintColorR,
        'tintColor.g': AnimTargetField.TilemapLayerTintColorG,
        'tintColor.b': AnimTargetField.TilemapLayerTintColorB,
        'tintColor.a': AnimTargetField.TilemapLayerTintColorA,
        'opacity': AnimTargetField.TilemapLayerOpacity,
    },
    Transform: {
        'position.x': AnimTargetField.TransformPositionX,
        'position.y': AnimTargetField.TransformPositionY,
        'position.z': AnimTargetField.TransformPositionZ,
        'rotation.z': AnimTargetField.TransformRotationZ,
        'scale.x': AnimTargetField.TransformScaleX,
        'scale.y': AnimTargetField.TransformScaleY,
        'scale.z': AnimTargetField.TransformScaleZ,
    },
    UIRect: {
        'anchorMin.x': AnimTargetField.UIRectAnchorMinX,
        'anchorMin.y': AnimTargetField.UIRectAnchorMinY,
        'anchorMax.x': AnimTargetField.UIRectAnchorMaxX,
        'anchorMax.y': AnimTargetField.UIRectAnchorMaxY,
        'offsetMin.x': AnimTargetField.UIRectOffsetMinX,
        'offsetMin.y': AnimTargetField.UIRectOffsetMinY,
        'offsetMax.x': AnimTargetField.UIRectOffsetMaxX,
        'offsetMax.y': AnimTargetField.UIRectOffsetMaxY,
        'pivot.x': AnimTargetField.UIRectPivotX,
        'pivot.y': AnimTargetField.UIRectPivotY,
    },
    UIRenderer: {
        'color.r': AnimTargetField.UIRendererColorR,
        'color.g': AnimTargetField.UIRendererColorG,
        'color.b': AnimTargetField.UIRendererColorB,
        'color.a': AnimTargetField.UIRendererColorA,
    },
};

export const COMPONENT_MAP: Record<string, AnimTargetComponent> = {
    BitmapText: AnimTargetComponent.BitmapText,
    Camera: AnimTargetComponent.Camera,
    Sprite: AnimTargetComponent.Sprite,
    TilemapLayer: AnimTargetComponent.TilemapLayer,
    Transform: AnimTargetComponent.Transform,
    UIRect: AnimTargetComponent.UIRect,
    UIRenderer: AnimTargetComponent.UIRenderer,
};
